### ISSUE TITLE
用lede最新源码编译可道云，打开可道云提示这个。。求大佬帮忙看看，每更新php8之前没问题

### ISSUE THREAD

**Issue by hexsen929** [Lienol/openwrt-package#10]
Fatal error: Cannot acquire reference to $GLOBALS in /mnt/sdc1/kodexplorer/app/function/web.function.php on line 824

**Comment by Lienol** [comment]
不看commit描述吗？

**Comment by Lienol** [comment]
The OpenWrt Master already use PHP 8 and remove the PHP 7.

The kodbox seem not to support PHP Version >= 8.1.0, Please wait for the kodbox updates.
