### ISSUE TITLE
酸酸乳服务端无法走passwall的代理流量

### ISSUE THREAD

**Issue by WROIATE** [Lienol/openwrt-package#101]
环境：固件为lienol源码编译的x86_64固件
问题：连接路由器上的ssr python server或者ssr server时无法走passwall的流量，可以确定已经连接成功，不知道是什么原因，求指教

**Comment by ilovyan** [comment]
我也遇到了，以前勇Lean的固件，里面的可以开启作为服务端供其他人使用。passwall不行。

**Comment by wefuxkgfw** [comment]
> 我也遇到了，以前勇Lean的固件，里面的可以开启作为服务端供其他人使用。passwall不行。

别急，Li大会慢慢修复的，好饭不怕晚哦

**Comment by Lienol** [comment]
本机代理模式 选GFW

**Comment by WROIATE** [comment]
> 本机代理模式 选GFW

我这因为有些特殊情况，希望能走全局代理，请问有什么方法吗？

**Comment by Lienol** [comment]
已经开放，非特殊情况不建议使用此模式，否则出现的任何问题本人一概不回答！
