### ISSUE TITLE
passwall启动速度慢

### ISSUE THREAD

**Issue by garypang13** [Lienol/openwrt-package#102]
在修改passwall设置后点保存应用,passwall启动速度慢,特别是开启haproxy后,从保存到能正常上网得十几二十秒,

**Comment by Lienol** [comment]
换软路由就快了

**Comment by garypang13** [comment]
用的就是软路由 I3+8G内存 用SSR plus保存和切换都是秒完成的.

**Comment by wefuxkgfw** [comment]
> 用的就是软路由 I3+8G内存 用SSR plus保存和切换都是秒完成的.

Lienol近期会参考lua重构的，也会秒完成，请等待更新。
