### ISSUE TITLE
严重bug报到，在开启passwall后，如果在dhcp/dns页面修改dns缓存为0，会导致整个openwrt缓慢且无法上网。

### ISSUE THREAD

**Issue by lylus** [Lienol/openwrt-package#103]
严重bug报到，在开启passwall后，如果在dhcp/dns页面修改dns缓存为0，会导致整个openwrt缓慢且无法上网。之后无法怎么改回来都上不了网，且openwrt反应缓慢，只有重刷才能解决。

**Comment by Lienol** [comment]
默认不好？不背这锅，反正这个dns缓存无论我设置什么都会卡死，无论有没有开passwall
