### ISSUE TITLE
关于订阅节点的问题

### ISSUE THREAD

**Issue by marlboro3420** [Lienol/openwrt-package#107]
你好，我是发了邮件的那个。然后订阅地址是有两个v2ray节点和一个ss节点，但是在passwall里面订阅显示如下图[
![20200106141204](https://user-images.githubusercontent.com/10370066/71798973-dc6f6a80-308e-11ea-9faa-3c3a2b5df739.png)
](url)
是不正确的，在lean ssr + 是正确的三个节点（2v,1ss）.
现在环境是openwrt19 + passwall包。昨天试了最新的full镜像也是一样的显示。

**Comment by Lienol** [comment]
更新最新源码试试

**Comment by marlboro3420** [comment]
正常了，可以关闭了
