### ISSUE TITLE
L大，openwrt 19分支从大概12月开始，编译就会报错，有空请帮看看

### ISSUE THREAD

**Issue by lllrrr2** [Lienol/openwrt-package#11]
![image](https://user-images.githubusercontent.com/61368564/147385819-296954cf-0bde-4deb-b471-e231684ffa0b.png)

之前的一直都正常。

**Comment by lllrrr** [comment]
我有重装系统，18版本和20版本的ubuntu都一样

**Comment by Lienol** [comment]
Cannot find appropriate Ninja process on this system.

试下 apt-get install ninja-build

**Comment by lllrrr2** [comment]
![image](https://user-images.githubusercontent.com/61368564/147479519-a95ec19a-815b-41a4-9c8f-16af59ca69f3.png)
装完apt-get install ninja-build 现在的报错提示不一样了

**Comment by Lienol** [comment]
有试过重拉源码吗？

**Comment by lllrrr2** [comment]
有，我在ubuntu20系统下，库是重新git的，我用21分支编译没有问题，用19分支就报这个错

**Comment by Lienol** [comment]
重拉最新源码，再试下

**Comment by lllrrr2** [comment]
重新拉了，还是会报
![image](https://user-images.githubusercontent.com/61368564/147576097-c8004b5b-3183-4177-9a53-85449c6583a7.png)

**Comment by Lienol** [comment]
无法复现

**Comment by Lienol** [comment]
试一下
`make tools/ninja/compile`
然后再编译

**Comment by lllrrr2** [comment]
> 试一下 `make tools/ninja/compile` 然后再编译

这次成功了，谢谢Li大
