### ISSUE TITLE
dnsmasq 崩溃和dns设置问题

### ISSUE THREAD

**Issue by JoeHoy233** [Lienol/openwrt-package#115]
dnsmasq崩溃，日志如下
daemon.crit dnsmasq[5421]: illegal repeated keyword at line 5 of /tmp/dnsmasq.d/dnsmasq-passwall.conf
daemon.crit dnsmasq[5421]: FAILED to start up
daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
第五行是cache-size=2048
另外，openwrt的dnsmasq源码已经切换到/tmp/resolv.conf.d/resolv.conf.auto
并软链接至/tmp/resolv.conf，而不再是/tmp/resolv.conf.auto，这会当设置为运营商dns时，并不会生效

**Comment by Lienol** [comment]
清空一下 /etc/dnsmasq.conf内容，然后重启路由器。

**Comment by JoeHoy233** [comment]
清空dnsmasq.conf后解决崩溃问题了
