### ISSUE TITLE
编译文件助手/文件浏览器无法启用

### ISSUE THREAD

**Issue by bobotoy** [Lienol/openwrt-package#116]
使用lean-lede源码加上大佬的插件编译arm64固件，文件助手fileassistant插件无法启用，打开后空白，文件浏览器filebrowser无法运行。希望得到帮助，不知道缺少了什么依赖。

**Comment by Lienol** [comment]
进入fileassistant界面，F12 - Network - F5，看看有没有红色的。
或者把编译文件 .config上传上来我测试下

**Comment by wefuxkgfw** [comment]
> 使用lean-lede源码加上大佬的插件编译arm64固件，文件助手fileassistant插件无法启用，打开后空白，文件浏览器filebrowser无法运行。希望得到帮助，不知道缺少了什么依赖。

你不要自己把lienol的luci包添加到大雕的源码，Lienol帮你添加好了，你用lienol修改的大雕源码编译：https://github.com/Lienol/lean-lede

**Comment by wefuxkgfw** [comment]
> 进入fileassistant界面，F12 - Network - F5，看看有没有红色的。
> 或者把编译文件 .config上传上来我测试下

老哥你把你的提示app单独使用方法删了吧，省得他们自己搞又问这么多重复得issue。不要让他们知道添加luci包使用方法，就给他们两个修改得源码编译就行了。

**Comment by bobotoy** [comment]
[](url)

> 进入fileassistant界面，F12 - Network - F5，看看有没有红色的。
> 或者把编译文件 .config上传上来我测试下

https://github.com/bobotoy/openwrt-actions/blob/master/lean-lede-arrch64

**Comment by bobotoy** [comment]
> > 使用lean-lede源码加上大佬的插件编译arm64固件，文件助手fileassistant插件无法启用，打开后空白，文件浏览器filebrowser无法运行。希望得到帮助，不知道缺少了什么依赖。
> 
> 你不要自己把lienol的luci包添加到大雕的源码，Lienol帮你添加好了，你用lienol修改的大雕源码编译：https://github.com/Lienol/lean-lede
我确实用的大佬的这个移植脚本

**Comment by bobotoy** [comment]
> > 进入fileassistant界面，F12 - Network - F5，看看有没有红色的。
> > 或者把编译文件 .config上传上来我测试下
> 
> 老哥你把你的提示app单独使用方法删了吧，省得他们自己搞又问这么多重复得issue。不要让他们知道添加luci包使用方法，就给他们两个修改得源码编译就行了。

兄弟，请理解一下小白，每个人都是从小白走过来，授人以鱼不如授人以渔，作为我自己发起issue肯定是先查看历史issue，再谷歌百度，实在无法解决再过来请教的。

**Comment by bobotoy** [comment]
> 进入fileassistant界面，F12 - Network - F5，看看有没有红色的。
> 或者把编译文件 .config上传上来我测试下

F12 - Network - F5，操作下来没有发现任何红色
附上.config链接
https://github.com/bobotoy/openwrt-actions/blob/master/lean-lede-arrch64

**Comment by Lienol** [comment]
![image](https://user-images.githubusercontent.com/23146169/72136354-93d3ec00-33c3-11ea-93b2-13e33f36a830.png)
测试正常
