### ISSUE TITLE
passwall插件正常翻墙，但是ping谷歌显示不通！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#117]
![image](https://user-images.githubusercontent.com/45259624/72065962-654e0680-331a-11ea-8bfb-aa346404b693.png)
本人是官方19.07编译。。。。

**Comment by zxlhhyccc** [comment]
第二，这个一般是怎么选择？
![image](https://user-images.githubusercontent.com/45259624/72066198-f2915b00-331a-11ea-81a6-9cd7a0602098.png)

**Comment by zxlhhyccc** [comment]
第三，节点实际正常，但显示超时：
![image](https://user-images.githubusercontent.com/45259624/72066289-1eacdc00-331b-11ea-8066-3047105d356a.png)

**Comment by Lienol** [comment]
系统日志，passwall日志发下（敏感东西打码）。
顺便把/etc/dnsmasq.conf内容清空一下，重启一下看看

**Comment by zxlhhyccc** [comment]
> 系统日志，passwall日志发下（敏感东西打码）。
> 顺便把/etc/dnsmasq.conf内容清空一下，重启一下看看

Thu Jan  9 21:51:57 2020 user.info mwan3track[5271]: Check (ping) failed for target "8.8.4.4" on interface wan (eth0.2)
Thu Jan  9 21:52:00 2020 cron.info crond[31251]: USER root pid 1991 cmd nohup /usr/share/passwall/monitor.sh > /dev/null 2>&1
Thu Jan  9 21:52:37 2020 user.info mwan3track[5271]: Check (ping) failed for target "8.8.8.8" on interface wan (eth0.2)
Thu Jan  9 21:52:39 2020 user.info mwan3track[5271]: Check (ping) failed for target "208.67.222.222" on interface wan (eth0.2)
Thu Jan  9 21:53:01 2020 daemon.info dnsmasq[30058]: exiting on receipt of SIGTERM
Thu Jan  9 21:53:01 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Jan  9 21:53:01 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: started, version 2.80 cachesize 150
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: DNS service limited to local subnets
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC no-ID loop-detect inotify dumpfile
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq-dhcp[3412]: DHCP, IP range 192.168.10.100 -- 192.168.10.249, lease time 12h
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: using local addresses only for domain test
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: using local addresses only for domain onion
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: using local addresses only for domain localhost
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: using local addresses only for domain local
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: using local addresses only for domain invalid
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: using local addresses only for domain bind
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: using nameserver 127.0.0.1#5333
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: using local addresses only for domain lan
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: read /etc/hosts - 4 addresses
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq[3412]: read /tmp/hosts/dhcp.cfg01411c - 1 addresses
Thu Jan  9 21:53:05 2020 daemon.info dnsmasq-dhcp[3412]: read /etc/ethers - 0 addresses
Thu Jan  9 21:53:05 2020 cron.info crond[3453]: crond (busybox 1.30.1) started, log level 5
Thu Jan  9 21:53:07 2020 daemon.info dnsmasq[3412]: exiting on receipt of SIGTERM
Thu Jan  9 21:53:07 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Jan  9 21:53:07 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Jan  9 21:53:08 2020 user.info mwan3track[5271]: Check (ping) failed for target "8.8.8.8" on interface wan (eth0.2)
Thu Jan  9 21:53:10 2020 user.info mwan3track[5271]: Check (ping) failed for target "208.67.222.222" on interface wan (eth0.2)
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: started, version 2.80 cachesize 2048
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: DNS service limited to local subnets
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC no-ID loop-detect inotify dumpfile
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq-dhcp[3846]: DHCP, IP range 192.168.10.100 -- 192.168.10.249, lease time 12h
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using local addresses only for domain test
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using local addresses only for domain onion
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using local addresses only for domain localhost
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using local addresses only for domain local
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using local addresses only for domain invalid
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using local addresses only for domain bind
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zzux.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zzcloud.me
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zzcartoon.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zyzc9.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zyns.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zynamics.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zynaima.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zvereff.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zuola.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zuo.la
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zuobiao.me
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zsrhao.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zspeeder.me
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zpn.im
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zozotown.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zorrovpn.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zoozle.net
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zootool.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zoogvpn.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zonghexinwen.net
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zonghexinwen.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zonaeuropa.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zomobo.net
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zodgame.us
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zmw.cn
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zkaip.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zippyshare.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain ziporn.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zinio.com
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using nameserver 127.0.0.1#7913 for domain zim.vn
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: using 5569 more nameservers
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: read /etc/hosts - 4 addresses
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq[3846]: read /tmp/hosts/dhcp.cfg01411c - 1 addresses
Thu Jan  9 21:53:11 2020 daemon.info dnsmasq-dhcp[3846]: read /etc/ethers - 0 addresses
Thu Jan  9 21:53:14 2020 daemon.info dnsmasq[3846]: exiting on receipt of SIGTERM
Thu Jan  9 21:53:14 2020 cron.info crond[4226]: crond (busybox 1.30.1) started, log level 5
Thu Jan  9 21:53:14 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Thu Jan  9 21:53:14 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Jan  9 21:53:17 2020 daemon.err uhttpd[2878]: netstat: showing only processes with your user ID
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: started, version 2.80 cachesize 2048
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: DNS service limited to local subnets
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC no-ID loop-detect inotify dumpfile
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq-dhcp[4419]: DHCP, IP range 192.168.10.100 -- 192.168.10.249, lease time 12h
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using local addresses only for domain test
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using local addresses only for domain onion
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using local addresses only for domain localhost
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using local addresses only for domain local
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using local addresses only for domain invalid
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using local addresses only for domain bind
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zzux.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zzcloud.me
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zzcartoon.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zyzc9.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zyns.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zynamics.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zynaima.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zvereff.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zuola.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zuo.la
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zuobiao.me
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zsrhao.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zspeeder.me
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zpn.im
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zozotown.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zorrovpn.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zoozle.net
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zootool.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zoogvpn.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zonghexinwen.net
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zonghexinwen.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zonaeuropa.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zomobo.net
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zodgame.us
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zmw.cn
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zkaip.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zippyshare.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain ziporn.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zinio.com
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using nameserver 127.0.0.1#7913 for domain zim.vn
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: using 5569 more nameservers
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: read /etc/hosts - 4 addresses
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq[4419]: read /tmp/hosts/dhcp.cfg01411c - 1 addresses
Thu Jan  9 21:53:17 2020 daemon.info dnsmasq-dhcp[4419]: read /etc/ethers - 0 addresses

**Comment by zxlhhyccc** [comment]
![image](https://user-images.githubusercontent.com/45259624/72073422-d1d10180-332a-11ea-922a-39ed9a371943.png)

**Comment by zxlhhyccc** [comment]
![image](https://user-images.githubusercontent.com/45259624/72073478-f88f3800-332a-11ea-93c9-17fa9336b00a.png)

**Comment by zxlhhyccc** [comment]
谷歌检测不通引起这个错误：
Thu Jan  9 21:46:33 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:34 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:35 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:35 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:36 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:36 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:37 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:38 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:39 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:40 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:40 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:40 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:41 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:42 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:42 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:43 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:44 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:45 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:45 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:46 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:47 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:48 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:48 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:49 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:50 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:50 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:50 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:51 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:52 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:53 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:54 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:54 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:55 2020 daemon.err uhttpd[2878]: uci: Entry not found
Thu Jan  9 21:46:55 2020 daemon.err uhttpd[2878]: uci: Entry not found

**Comment by zxlhhyccc** [comment]
> 系统日志，passwall日志发下（敏感东西打码）。
> 顺便把/etc/dnsmasq.conf内容清空一下，重启一下看看

看到大佬更新了passwall，是不是解决谷歌ping不通问题？

**Comment by Lienol** [comment]
你是多线接入？开了mwan3规则？

**Comment by zxlhhyccc** [comment]
> 你是多线接入？开了mwan3规则？

我是二级路由，一级是单线多拨。。。。这个会有影响么？

**Comment by Lienol** [comment]
官方坑不少。
你可以试试用我源码(https://github.com/Lienol/openwrt) 编译，已经默认帮你们排了好多坑了。

**Comment by Lienol** [comment]
你是以前的版本直接保留配置升级上来的吗？
黑白名单 - IP白名单看看有没有 8888 8844 208.67.222.222 208.67.220.220 删掉

**Comment by zxlhhyccc** [comment]
大佬，现在可以了。。。。谢谢！
