### ISSUE TITLE
求加入luci-app-smbd的支持

### ISSUE THREAD

**Issue by MxCen** [Lienol/openwrt-package#119]
自己加入后，报依赖错误

WARNING: Makefile 'package/my-extra/smbd/Makefile' has a dependency on 'kmod-crypto-arc4', which does not exist

luci地址：
https://github.com/Andy2244/openwrt-extra

**Comment by zxlhhyccc** [comment]
> 自己加入后，报依赖错误
> 
> WARNING: Makefile 'package/my-extra/smbd/Makefile' has a dependency on 'kmod-crypto-arc4', which does not exist
> 
> luci地址：
> https://github.com/Andy2244/openwrt-extra

自己添加依赖包就是了。。。。
