### ISSUE TITLE
！passwall订阅无法下载，下载失败！见截图！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#12]
![JW91{YB$6K08{7M{J60JUIF](https://user-images.githubusercontent.com/45259624/60769631-d6f78e80-a104-11e9-8109-1bc4827d393a.png)

**Comment by zxlhhyccc** [comment]
通过链接添加服务器也无效。。。。
![5L70S4YKTA5(I%S4BYA~8N3](https://user-images.githubusercontent.com/45259624/60769758-4c179380-a106-11e9-8baf-98618a219744.png)
![@CYU0VH~E}N%U1FQZ)S2通过链接添加服务器也无效。。。。
![5L70S4YKTA5(I%S4BYA~8N3](https://user-images.githubusercontent.com/45259624/60769758-4c179380-a106-11e9-8baf-98618a219744.png)
C](https://user-images.githubusercontent.com/45259624/60769766-5f2a6380-a106-11e9-8fe1-726fa1028ed2.png)

**Comment by Lienol** [comment]
不存在此问题！！！
请检查链接是否有误！！！

**Comment by zxlhhyccc** [comment]
> 不存在此问题！！！
> 请检查链接是否有误！！！

链接没有错误，几个人测试均无法下载。。。

**Comment by Lienol** [comment]
> > 不存在此问题！！！
> > 请检查链接是否有误！！！
> 
> 链接没有错误，几个人测试均无法下载。。。

有能力的话，自己修复好发PR。
也可以发到我邮箱给我测试

**Comment by zxlhhyccc** [comment]
> > > 不存在此问题！！！
> > > 请检查链接是否有误！！！
> > 
> > 
> > 链接没有错误，几个人测试均无法下载。。。
> 
> 有能力的话，自己修复好发PR。
> 也可以发到我邮箱给我测试

同一个订阅SSR链接，在大雕的源码上可以订阅，在passwall上不行

**Comment by Lienol** [comment]
> > > > 不存在此问题！！！
> > > > 请检查链接是否有误！！！
> > > 
> > > 
> > > 链接没有错误，几个人测试均无法下载。。。
> > 
> > 
> > 有能力的话，自己修复好发PR。
> > 也可以发到我邮箱给我测试
> 
> 同一个订阅SSR链接，在大雕的源码上可以订阅，在passwall上不行

可以的话发个订阅链接到我邮箱测试
