### ISSUE TITLE
Qbittorrent display issue

### ISSUE THREAD

**Issue by xcyll** [Lienol/openwrt-package#12]
Compiled branch: lienol/openwrt ... branches(main) 
Only luci-app-qbittorrent(qbittorrent) is selected under the nas menu
After booting , luci-app-qbittorrent doesn't show up in the openwrt menu bar
(But it can be found in the installed software)

**Comment by Lienol** [comment]
What the luci branch use ?
If the js luci branch, maybe not add 'nas' menu in the menu.d file.

**Comment by xcyll** [comment]
> What the luci branch use ?
> If the js luci branch, maybe not add 'nas' menu in the menu.d file.

src-git luci https://github.com/Lienol/openwrt-luci.git;main
，(src-git other https://github.com/Lienol/openwrt-package.git;other)

**Comment by Lienol** [comment]
I have been updated on the LUCI source code.
Please update feeds and then compile.

**Comment by xcyll** [comment]
Tested OK, thanks!
