### ISSUE TITLE
GFW模式不工作

### ISSUE THREAD

**Issue by JingenChen** [Lienol/openwrt-package#124]
按截图的方式配置默认代理模式为GFW，客户端无法访问google，youtube等被墙的网站，改成大陆白名单模式后正常。固件版本：OpenWrt 19.07 / LuCI my-18.06 branch (git-20.008.64235-87ec2e2)

<img width="644" alt="Screen Shot 2020-01-10 at 3 55 01 PM" src="https://user-images.githubusercontent.com/7324423/72144853-34caa300-33d4-11ea-8f9d-34402ad37315.png">

**Comment by hpcex** [comment]
我也有这个问题，固件版本：OpenWrt 19.07 / LuCI my-18.06 branch (git-20.008.64235-87ec2e2)，请问是已经修复了吗？
