### ISSUE TITLE
passwall在添加节点报错

### ISSUE THREAD

**Issue by zcluo** [Lienol/openwrt-package#125]
/usr/lib/lua/luci/model/cbi/passwall/node_config.lua:7: attempt to index field 'cbi' (a nil value)
stack traceback:
	/usr/lib/lua/luci/model/cbi/passwall/node_config.lua:7: in function 'get_customed_path'
	/usr/lib/lua/luci/model/cbi/passwall/node_config.lua:11: in function 'is_finded'
	/usr/lib/lua/luci/model/cbi/passwall/node_config.lua:63: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1242: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:926: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:440: in function </usr/lib/lua/luci/dispatcher.lua:439>

**Comment by Lienol** [comment]
看README

**Comment by zcluo** [comment]
> 看README

我按README做了，，如果你使用的是Luci19，请编译时选上"luci","luci-compat","luci-lib-ipkg"后编译这几个也有选
