### ISSUE TITLE
我有来了,问题反馈

### ISSUE THREAD

**Issue by fuqiang03** [Lienol/openwrt-package#131]
Trojan无法启动,只能生成配置文件
![QQ截图20200112193950](https://user-images.githubusercontent.com/26851715/72218245-e0f6c000-3573-11ea-8886-80fc421099c8.png)

**Comment by Lienol** [comment]
没证书怎么启动

**Comment by fuqiang03** [comment]
证书? ca 证书?

**Comment by Lienol** [comment]
需要https证书才可以运行
