### ISSUE TITLE
make menuconfig

### ISSUE THREAD

**Issue by sheiy** [Lienol/openwrt-package#134]
WARNING: Makefile 'package/feeds/lienol/luci-app-passwall/Makefile' has a dependency on 'kcptun-client', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-proto-modemmanager/Makefile' has a dependency on 'modemmanager', which does not exist
tmp/.config-package.in:137545:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:137545:	symbol PACKAGE_vpn-policy-routing depends on PACKAGE_vpnbypass
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:137565:	symbol PACKAGE_vpnbypass depends on PACKAGE_vpn-policy-routing

**Comment by Lienol** [comment]
和官方packages kcptun冲突

**Comment by zxlhhyccc** [comment]
> 和官方packages kcptun冲突

这个不是冲突，是缺少依赖包引起的，到master里找到这些依赖包添加到对应目录下就可以了。。。

**Comment by jikuohong** [comment]
> > 和官方软件包kcptun冲突
> 
> 这个不是冲突，是通常依赖包引起的，到master里找到这些依赖包添加到对应目录下就可以了。。。。

能不能详细说下，怎么解决缺少依赖包？
