### ISSUE TITLE
负载均衡:运行失败严重拖慢passwall的启动速度

### ISSUE THREAD

**Issue by garypang13** [Lienol/openwrt-package#135]
passwall每次修改保存,在日志看都能看到这条提示:负载均衡:运行失败,然后要等monitor.sh检测到haproxy没有启动再重启整个passwall,到第二次启动负载均衡才能成功,导致整个修改保存过程需要10秒左右.

**Comment by garypang13** [comment]
原来是nohup $haproxy_bin -f $HAPROXY_FILE 2>&1写错了,
应该是
nohup $haproxy_bin -f $HAPROXY_FILE /dev/null 2>&1
我看上一个commit已经修复了这个问题.

**Comment by Lienol** [comment]
你更新源码再看看会不会

**Comment by garypang13** [comment]
> 你更新源码再看看会不会

已经修复了,感谢.
