### ISSUE TITLE
大神，编译无问题，运行错误见内文，请教如何处理

### ISSUE THREAD

**Issue by hzjnet** [Lienol/openwrt-package#14]
首页出现：
/usr/lib/lua/luci/model/cbi/passwall/api/kcptun.lua:7: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/model/cbi/passwall/api/kcptun.lua:7: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/luci/controller/passwall.lua:5: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:586: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:613: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:279: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:144: in function </usr/lib/lua/luci/dispatcher.lua:143>

环境是master版本20190706-14日版本的openwrt,passwall版本是最新，passwall是mode状态编译无问题，而集成后就出现上面报错！

**Comment by Lienol** [comment]
你用的是lede 17吗？现在git pull更新一下再编译看看。

**Comment by hzjnet** [comment]
> 你用的是lede 17吗？现在git pull更新一下再编译看看。

是master版本，不是lede 17;我更新后log不全了 ，只有3个commit了，而且提示softethervpn没找到，而17016版本就一切正常

**Comment by Lienol** [comment]
> > 你用的是lede 17吗？现在git pull更新一下再编译看看。
> 
> 是master版本，不是lede 17;我更新后log不全了 ，只有3个commit了，而且提示softethervpn没找到，而17016版本就一切正常； 再去试试；测试了不行，还是提示：
> 
> /usr/lib/lua/luci/model/cbi/passwall/api/v2ray.lua:7: module 'luci.model.ipkg' not found:
> no field package.preload['luci.model.ipkg']
> no file './luci/model/ipkg.lua'
> no file '/usr/share/lua/luci/model/ipkg.lua'
> no file '/usr/share/lua/luci/model/ipkg/init.lua'
> no file '/usr/lib/lua/luci/model/ipkg.lua'
> no file '/usr/lib/lua/luci/model/ipkg/init.lua'
> no file './luci/model/ipkg.so'
> no file '/usr/lib/lua/luci/model/ipkg.so'
> no file '/usr/lib/lua/loadall.so'
> no file './luci.so'
> no file '/usr/lib/lua/luci.so'
> no file '/usr/lib/lua/loadall.so'
> stack traceback:
> [C]: in function 'require'
> /usr/lib/lua/luci/model/cbi/passwall/api/v2ray.lua:7: in main chunk
> [C]: in function 'require'
> /usr/lib/lua/luci/controller/passwall.lua:7: in main chunk
> [C]: in function 'require'
> /usr/lib/lua/luci/dispatcher.lua:586: in function 'createindex'
> /usr/lib/lua/luci/dispatcher.lua:613: in function 'createtree'
> /usr/lib/lua/luci/dispatcher.lua:279: in function 'dispatch'
> /usr/lib/lua/luci/dispatcher.lua:144: in function </usr/lib/lua/luci/dispatcher.lua:143>

官方openwrt的master吗？luci也是官方master？

**Comment by Lienol** [comment]
若使用官方最新luci源码，请把luci-lib-ipkg给选上*再编译
