### ISSUE TITLE
Network Shares issue

### ISSUE THREAD

**Issue by xcyll** [Lienol/openwrt-package#14]
All compilation branches are main 

src-git packages https://github.com/Lienol/openwrt-packages.git;main
src-git luci https://github.com/Lienol/openwrt-luci.git;main

ksmbd & samba4 cannot be used normally——Shared storage cannot be opened
[Separately compiled and tested]

After uninstalling, I installed samba4 in the software center and it can be used normally

**Comment by xcyll** [comment]
It can be used normally after upgrading [ksmbd-server] directly in the software center

**Comment by Lienol** [comment]
vi /etc/config/ksmbd or samba4
enabled set '1'
and then reboot service.

**Comment by xcyll** [comment]
Thanks for your advice.
