### ISSUE TITLE
Lienol大，这是bug吗？

### ISSUE THREAD

**Issue by stztao** [Lienol/openwrt-package#141]
用你源码编译的原版op，系统一直无法恢复配置的备份，保存没问题。按提交一直提示：备份存档似乎不是有效的 gzip 文件

**Comment by Lienol** [comment]
什么机器，x64没问题

**Comment by stztao** [comment]
是x64，用的你官方源码编译，其他一切正常就是恢复备份一直提示格式无效，换Lean版本又正常可以恢复备份，最近改用你官源这版很好用，就是这个问题不知出在哪有点郁闷
