### ISSUE TITLE
add some luci package

### ISSUE THREAD

**Issue by rufengsuixing** [Lienol/openwrt-package#143]
https://github.com/rufengsuixing/luci-app-onliner
https://github.com/rufengsuixing/luci-app-zerotier
https://github.com/rufengsuixing/luci-app-usb3disable
https://github.com/rufengsuixing/luci-app-syncdial
还有一个自认写的很丑的
https://github.com/rufengsuixing/luci-app-autoipsetadder

另外gfwlist可以考虑使用cdn www.jsdelivr.com
附上我的转换脚本 https://github.com/rufengsuixing/gfwlist2dnsmasq-rules

**Comment by Lienol** [comment]
Good, Thank.

**Comment by lllrrr** [comment]
支持支持
