### ISSUE TITLE
passwall 3.3.25-20200114的问题 可能是bug？

### ISSUE THREAD

**Issue by aglent** [Lienol/openwrt-package#145]
设置为：
DNS解析方式：chinadns-ng
chinadns-ng国内dns：默认114
chinadns-ng可信dns：内置的Google DNS
大陆白名单模式
DHCP/DNS：忽略解析文件

现象：无法解析不在gfwlist列表内的被污染域名
比如dig dlercloud.com -p 7913
返回的是可信dns的IP 104.26.2.204 这是正确的
但是dig dlercloud.com 返回的ip是被污染的69.171.235.64 导致网站无法打开

我回退到前几天编译的含 passwall 3.2.22-20200114 的固件 其他设置一样
dig dlercloud.com 就能返回和7913端口一样的ip 网站能正常打开

所可能是新版passwall的bug？

**Comment by aglent** [comment]
passwall 3.3.26 似乎又正常 明天我再确认下

**Comment by wefuxkgfw** [comment]
@aglent 感谢反馈

**Comment by aglent** [comment]
确认passwall 3.3.26正常 不存在这个问题了
感谢！
