### ISSUE TITLE
经测试确认，最近几个版本passwall均因为守护进程问题引起系统日志中uttpd的错误！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#146]

**Comment by zxlhhyccc** [comment]
![image](https://user-images.githubusercontent.com/45259624/72437271-55806780-37dd-11ea-9b75-fb5883069abf.png)

**Comment by zxlhhyccc** [comment]
Wed Jan 15 23:16:00 2020 cron.info crond[8790]: USER root pid 17656 cmd nohup /usr/share/passwall/monitor.sh > /dev/null 2>&1
Wed Jan 15 23:16:18 2020 daemon.err uhttpd[3152]: netstat: showing only processes with your user ID
Wed Jan 15 23:16:23 2020 daemon.err uhttpd[3152]: netstat: showing only processes with your user ID

**Comment by wefuxkgfw** [comment]
厉害了…

**Comment by AndyWii** [comment]
怎么解决呢问题是？
