### ISSUE TITLE
passwall使用tcping替换ping检测节点时，节点的延迟显示的是超时，改为仅ping，节点延迟正常显示！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#147]
![image](https://user-images.githubusercontent.com/45259624/72449924-6d171a80-37f4-11ea-928f-856a7dacc021.png)
![image](https://user-images.githubusercontent.com/45259624/72450085-b5363d00-37f4-11ea-809b-074ed83fb66c.png)

**Comment by Lienol** [comment]
输入命令 tcping -p 端口 域名
看看

**Comment by wefuxkgfw** [comment]
@Lienol 测试

**Comment by wefuxkgfw** [comment]
@zxlhhyccc …

**Comment by zxlhhyccc** [comment]
> 输入命令 tcping -p 端口 域名
> 看看
![image](https://user-images.githubusercontent.com/45259624/72452914-4b6c6200-37f9-11ea-836b-b03617487823.png)

**Comment by Lienol** [comment]
怎么和我的tcping不一样？你用的哪个源码编译的？什么机器？

**Comment by bzzjh** [comment]
Lienol里继承的是这样的

root@OpenWrt:~# tcping
No hostname given
tcping, (C) 2003 folkert@vanheusden.com

hostname        hostname (e.g. localhost)
-p portnr       portnumber (e.g. 80)
-c count        how many times to connect
-i interval     delay between each connect
-f              flood connect (no delays)
-q              quiet, only returncode

root@OpenWrt:~#

**Comment by zxlhhyccc** [comment]
> 怎么和我的tcping不一样？你用的哪个源码编译的？什么机器？

用的就是你的tcping源码编译的，openwrt是官方的19.07正式版。。。。

**Comment by Lienol** [comment]
> > 怎么和我的tcping不一样？你用的哪个源码编译的？什么机器？
> 
> 用的是别人的tcping源码编译的，支持IPV4和IPV6，openwrt是官方的19.07正式版。。。。理论上应该是一样的吧？

命令参数都不一样。。。

**Comment by zxlhhyccc** [comment]
> > > 怎么和我的tcping不一样？你用的哪个源码编译的？什么机器？
> > 
> > 
> > 用的是别人的tcping源码编译的，支持IPV4和IPV6，openwrt是官方的19.07正式版。。。。理论上应该是一样的吧？
> 
> 命令参数都不一样。。。

那我改成你的tcping源码编译试试。。。。

**Comment by zxlhhyccc** [comment]
> > > 怎么和我的tcping不一样？你用的哪个源码编译的？什么机器？
> > 
> > 
> > 用的是别人的tcping源码编译的，支持IPV4和IPV6，openwrt是官方的19.07正式版。。。。理论上应该是一样的吧？
> 
> 命令参数都不一样。。。

用你的tcping源码ping延迟正常了，谢谢大佬！
