### ISSUE TITLE
希望passwall有自己的故障转移而非借助haproxy

### ISSUE THREAD

**Issue by garypang13** [Lienol/openwrt-package#149]
一个节点出现故障,90%的情况那个节点Ip还是通的,只是被阻断无法翻墙了而已.haproxy对此完全无能为力,会频繁在挂了的节点间切换.

ssr plus 对这种情况也是一样的问题,但是ssr plus改了循环切换时间后可完全保证在指定时间内不会再切换到挂了的节点,因为这个原因我只能放弃passwall而改用SSR PLUS

另外增加haproxy也就增加了一项不稳定因素,haproxy一旦出现任何问题,就会导致线路挂掉或间歇性断流,实际使用过程中也确实出现过因haproxy导致的一些问题,

**Comment by Lienol** [comment]
其实有的，只不过没完善好

**Comment by garypang13** [comment]
好的,我在源码里找找看,期待能尽快完善好!
