### ISSUE TITLE
passwall下网易云解锁失效

### ISSUE THREAD

**Issue by WROIATE** [Lienol/openwrt-package#150]
环境：1月14日编译固件
问题：passwall开启ssr时网易云解锁无效

**Comment by lllrrr** [comment]
同样用网易云，解锁没问题

**Comment by binsee** [comment]
建议你补充说明你所使用的 云音乐app版本、平台
Lienol使用的还是老版本的luci-app-unblockmusic包，建议看一下我更新的  https://github.com/binsee/luci-app-unblockmusic
我给上游发了新的修复分支 ，建议看下
https://github.com/binsee/luci-app-unblockmusic/tree/new-sh
https://github.com/maxlicheng/luci-app-unblockmusic/pull/104

**Comment by lllrrr** [comment]
我用的是project-openwrt的包，官方的18.06.6源码，没有问题

**Comment by WROIATE** [comment]
> 建议你补充说明你所使用的 云音乐app版本、平台
> 
> Lienol使用的还是老版本的luci-app-unblockmusic包，建议看一下我更新的 https://github.com/binsee/luci-app-unblockmusic
> 我给上游发了新的修复分支 ，建议看下
> https://github.com/binsee/luci-app-unblockmusic/tree/new-sh
> [maxlicheng/luci-app-unblockmusic#104](https://github.com/maxlicheng/luci-app-unblockmusic/pull/104)

我用你的这个关了passwall都不行了（而且好像连网都上不了了，这个issue我发了三次，分别关了passwall、你的插件，发现把你的插件关了而且重启路由才能联网）。。。看了你的readme我猜可能是ipv6的问题，我passwall挂的是ipv6的地址，有没有什么解决办法可以开着ipv6来呢？我主要是为了在学校免流开的ipv6的，还有就是又没可能是dns问题？因为免流所以我开的是全局。

网易云是2.7.1(build198242)，windows客户端

**Comment by Lienol** [comment]
输入 iptables -t nat -L 看看

**Comment by WROIATE** [comment]
> 输入 iptables -t nat -L 看看

我明天试试，出门了电脑不在手边

**Comment by cjameslynn** [comment]
端口填写5200，而不是Lienol固件界面上提示的5201。经测试可用

**Comment by WROIATE** [comment]
> 端口填写5200，而不是Lienol固件界面上提示的5201。经测试可用

开全局代理ipv6可以？

**Comment by binsee** [comment]
网易云似乎没有开启ipv6服务器，只有ipv4，所以如果你开ipv6全局，如果不能通过ipv6连接代理服务器，由代理服务器转接ipv4连接，那肯定用不了。
我这边用的都是ipv4，没有测试ipv6使用方案，所以不是很清楚。

建议你通过httping这种工具来检测下使用ipv6全局代理，测试只支持ipv4的站点是否正常访问。
另外之前Lienol说的很对，贴一下防火墙信息，再补充一下路由表信息，更好判断。

`luci-app-unblockmusic`这个插件，要根据 `/etc/init.d/unblockmusic`内容来判断版本，好几个版本都不好用，存在各种问题，我只使用自己调整的版本（修复后的代码提交给上游但并没有还没被接受，且各路由器插件源内的版本都很老，难用的版本）。

**Comment by WROIATE** [comment]
> 网易云似乎没有开启ipv6服务器，只有ipv4，所以如果你开ipv6全局，如果不能通过ipv6连接代理服务器，由代理服务器转接ipv4连接，那肯定用不了。
> 我这边用的都是ipv4，没有测试ipv6使用方案，所以不是很清楚。
> 
> 建议你通过httping这种工具来检测下使用ipv6全局代理，测试只支持ipv4的站点是否正常访问。
> 另外之前Lienol说的很对，贴一下防火墙信息，再补充一下路由表信息，更好判断。
> 
> `luci-app-unblockmusic`这个插件，要根据 `/etc/init.d/unblockmusic`内容来判断版本，好几个版本都不好用，存在各种问题，我只使用自己调整的版本（修复后的代码提交给上游但并没有还没被接受，且各路由器插件源内的版本都很老，难用的版本）。

访问IPv4这个倒是没问题，我ssr主要是通过ipv6连接我的服务器，而我服务器是可以通过ipv4访问网易云的，这点没问题，并且我平时开全局是能够正常上网听歌的。

**Comment by WROIATE** [comment]
> 输入 iptables -t nat -L 看看

Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
cloud_music  tcp  --  anywhere             anywhere             tcp dpt:www match-set music dst
prerouting_rule  all  --  anywhere             anywhere             /* !fw3: Custom prerouting rule chain */
PSW        all  --  anywhere             anywhere            
zone_lan_prerouting  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_prerouting  all  --  anywhere             anywhere             /* !fw3 */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere             match-set laniplist dst /* PassWall */
REDIRECT   tcp  --  anywhere             resolver1.opendns.com  multiport dports 1:65535 /* PassWall */ redir ports 1041
REDIRECT   tcp  --  anywhere             dns.google           multiport dports 1:65535 /* PassWall */ redir ports 1041
RETURN     all  --  anywhere             anywhere             match-set vpsiplist dst /* PassWall */
RETURN     all  --  anywhere             anywhere             match-set whitelist dst /* PassWall */
REDIRECT   tcp  --  anywhere             anywhere             multiport dports 1:65535 match-set router dst /* PassWall */ redir ports 1041
REDIRECT   tcp  --  anywhere             anywhere             multiport dports 1:65535 match-set blacklist dst /* PassWall */ redir ports 1041
REDIRECT   tcp  --  anywhere             anywhere             multiport dports 1:65535 /* PassWall */ redir ports 1041

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
postrouting_rule  all  --  anywhere             anywhere             /* !fw3: Custom postrouting rule chain */
zone_lan_postrouting  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_postrouting  all  --  anywhere             anywhere             /* !fw3 */

Chain MINIUPNPD (2 references)
target     prot opt source               destination         

Chain MINIUPNPD-POSTROUTING (2 references)
target     prot opt source               destination         

Chain PSW (1 references)
target     prot opt source               destination         
DNAT       udp  --  anywhere             anywhere             udp dpt:domain to:192.168.1.1
RETURN     all  --  anywhere             anywhere             match-set laniplist dst
REDIRECT   tcp  --  anywhere             dns.google           multiport dports 1:65535 redir ports 1041
REDIRECT   tcp  --  anywhere             resolver1.opendns.com  multiport dports 1:65535 redir ports 1041
RETURN     all  --  anywhere             anywhere             match-set vpsiplist dst
RETURN     all  --  anywhere             anywhere             match-set whitelist dst
PSW_ACL    all  --  anywhere             anywhere            

Chain PSW_ACL (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  myphone        anywhere             match-set blacklist dst /* phone */ redir ports 1041
PSW_CHN1   tcp  -- myphone        anywhere            [goto]  multiport dports 1:65535 /* phone */
REDIRECT   tcp  --  anywhere             anywhere             match-set blacklist dst /* Default */ redir ports 1041
PSW_GLO1   tcp  --  anywhere             anywhere             multiport dports 1:65535 /* Default */

Chain PSW_CHN1 (1 references)
target     prot opt source               destination         
RETURN     tcp  --  anywhere             anywhere             match-set chnroute dst
REDIRECT   tcp  --  anywhere             anywhere             redir ports 1041

Chain PSW_GAME1 (0 references)
target     prot opt source               destination         
RETURN     tcp  --  anywhere             anywhere             match-set chnroute dst

Chain PSW_GFW1 (0 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             anywhere             match-set router dst redir ports 1041
REDIRECT   tcp  --  anywhere             anywhere             match-set gfwlist dst redir ports 1041

Chain PSW_GLO1 (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             anywhere             redir ports 1041

Chain PSW_HOME1 (0 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             anywhere             match-set chnroute dst redir ports 1041

Chain cloud_music (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             0.0.0.0/8           
RETURN     all  --  anywhere             10.0.0.0/8          
RETURN     all  --  anywhere             127.0.0.0/8         
RETURN     all  --  anywhere             169.254.0.0/16      
RETURN     all  --  anywhere             172.16.0.0/12       
RETURN     all  --  anywhere             192.168.0.0/16      
RETURN     all  --  anywhere             base-address.mcast.net/4 
RETURN     all  --  anywhere             240.0.0.0/4         
REDIRECT   tcp  --  anywhere             anywhere             redir ports 5202

Chain postrouting_lan_rule (1 references)
target     prot opt source               destination         

Chain postrouting_rule (1 references)
target     prot opt source               destination         

Chain postrouting_wan_rule (1 references)
target     prot opt source               destination         

Chain prerouting_lan_rule (1 references)
target     prot opt source               destination         

Chain prerouting_rule (1 references)
target     prot opt source               destination         

Chain prerouting_wan_rule (1 references)
target     prot opt source               destination         

Chain zone_lan_postrouting (1 references)
target     prot opt source               destination         
postrouting_lan_rule  all  --  anywhere             anywhere             /* !fw3: Custom lan postrouting rule chain */
SNAT       tcp  --  192.168.1.0/24       computer.lan          tcp dpt:3389 /* !fw3: RDP (reflection) */ to:192.168.1.1
SNAT       udp  --  192.168.1.0/24       computer.lan          udp dpt:3389 /* !fw3: RDP (reflection) */ to:192.168.1.1
SNAT       tcp  --  192.168.1.0/24       Nas.lan              tcp dpt:ftp /* !fw3: FTP (reflection) */ to:192.168.1.1
SNAT       tcp  --  192.168.1.0/24       Router.lan        tcp dpt:ssh /* !fw3: SSH (reflection) */ to:192.168.1.1
SNAT       tcp  --  192.168.1.0/24       Centos7.lan          tcp dpt:ssh /* !fw3: SSH7 (reflection) */ to:192.168.1.1
SNAT       tcp  --  192.168.1.0/24       win7.lan             tcp dpt:3389 /* !fw3: RDP7 (reflection) */ to:192.168.1.1
SNAT       tcp  --  192.168.1.0/24       Router.lan        tcp dpt:socks /* !fw3: socks (reflection) */ to:192.168.1.1
SNAT       udp  --  192.168.1.0/24       Router.lan        udp dpt:socks /* !fw3: socks (reflection) */ to:192.168.1.1

Chain zone_lan_prerouting (1 references)
target     prot opt source               destination         
prerouting_lan_rule  all  --  anywhere             anywhere             /* !fw3: Custom lan prerouting rule chain */
DNAT       tcp  --  192.168.1.0/24      MY_IP        tcp dpt:2333 /* !fw3: RDP (reflection) */ to:192.168.1.100:3389
DNAT       udp  --  192.168.1.0/24       MY_IP         udp dpt:2333 /* !fw3: RDP (reflection) */ to:192.168.1.100:3389
DNAT       tcp  --  192.168.1.0/24       MY_IP        tcp dpt:1611 /* !fw3: FTP (reflection) */ to:192.168.1.102:21
DNAT       tcp  --  192.168.1.0/24       MY_IP         tcp dpt:2222 /* !fw3: SSH (reflection) */ to:192.168.1.1:22
DNAT       tcp  --  192.168.1.0/24      MY_IP         tcp dpt:22222 /* !fw3: SSH7 (reflection) */ to:192.168.1.103:22
DNAT       tcp  --  192.168.1.0/24       MY_IP         tcp dpt:2334 /* !fw3: RDP7 (reflection) */ to:192.168.1.104:3389
DNAT       tcp  --  192.168.1.0/24      MY_IP        tcp dpt:10080 /* !fw3: socks (reflection) */ to:192.168.1.1:1080
DNAT       udp  --  192.168.1.0/24         MY_IP      udp dpt:10080 /* !fw3: socks (reflection) */ to:192.168.1.1:1080

Chain zone_wan_postrouting (1 references)
target     prot opt source               destination         
postrouting_wan_rule  all  --  anywhere             anywhere             /* !fw3: Custom wan postrouting rule chain */
MINIUPNPD-POSTROUTING  all  --  anywhere             anywhere            
MINIUPNPD-POSTROUTING  all  --  anywhere             anywhere            
FULLCONENAT  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_wan_prerouting (1 references)
target     prot opt source               destination         
prerouting_wan_rule  all  --  anywhere             anywhere             /* !fw3: Custom wan prerouting rule chain */
DNAT       tcp  --  anywhere             anywhere             tcp dpt:2333 /* !fw3: RDP */ to:192.168.1.100:3389
DNAT       udp  --  anywhere             anywhere             udp dpt:2333 /* !fw3: RDP */ to:192.168.1.100:3389
DNAT       tcp  --  anywhere             anywhere             tcp dpt:1611 /* !fw3: FTP */ to:192.168.1.102:21
DNAT       tcp  --  anywhere             anywhere             tcp dpt:2222 /* !fw3: SSH */ to:192.168.1.1:22
DNAT       tcp  --  anywhere             anywhere             tcp dpt:22222 /* !fw3: SSH7 */ to:192.168.1.103:22
DNAT       tcp  --  anywhere             anywhere             tcp dpt:2334 /* !fw3: RDP7 */ to:192.168.1.104:3389
DNAT       tcp  --  anywhere             anywhere             tcp dpt:10080 /* !fw3: socks */ to:192.168.1.1:1080
DNAT       udp  --  anywhere             anywhere             udp dpt:10080 /* !fw3: socks */ to:192.168.1.1:1080
FULLCONENAT  all  --  anywhere             anywhere             /* !fw3 */
MINIUPNPD  all  --  anywhere             anywhere            
MINIUPNPD  all  --  anywhere             anywhere

**Comment by binsee** [comment]
```
Chain cloud_music (1 references)
target prot opt source destination
RETURN all -- anywhere 0.0.0.0/8
RETURN all -- anywhere 10.0.0.0/8
RETURN all -- anywhere 127.0.0.0/8
RETURN all -- anywhere 169.254.0.0/16
RETURN all -- anywhere 172.16.0.0/12
RETURN all -- anywhere 192.168.0.0/16
RETURN all -- anywhere base-address.mcast.net/4
RETURN all -- anywhere 240.0.0.0/4
REDIRECT tcp -- anywhere anywhere redir ports 5202
```

这不是我改写后的版本，
请看
https://github.com/binsee/luci-app-unblockmusic/blob/new-sh/app/root/etc/init.d/unblockmusic

你可以安装我编译的这个包 https://github.com/binsee/luci-app-unblockmusic/releases/tag/v2.2.3

**Comment by WROIATE** [comment]
> ```
> Chain cloud_music (1 references)
> target prot opt source destination
> RETURN all -- anywhere 0.0.0.0/8
> RETURN all -- anywhere 10.0.0.0/8
> RETURN all -- anywhere 127.0.0.0/8
> RETURN all -- anywhere 169.254.0.0/16
> RETURN all -- anywhere 172.16.0.0/12
> RETURN all -- anywhere 192.168.0.0/16
> RETURN all -- anywhere base-address.mcast.net/4
> RETURN all -- anywhere 240.0.0.0/4
> REDIRECT tcp -- anywhere anywhere redir ports 5202
> ```
> 
> 这不是我改写后的版本，
> 请看
> https://github.com/binsee/luci-app-unblockmusic/blob/new-sh/app/root/etc/init.d/unblockmusic
> 
> 你可以安装我编译的这个包 https://github.com/binsee/luci-app-unblockmusic/releases/tag/v2.2.3

这个是lienol的，我这是会他的，你的那个版本之前试了一下直接连网都上不了了（笑哭），我再试一次你这个

**Comment by binsee** [comment]
lienol固件中的`luci-app-unblockmusic`是L大改写的，反正写的奇奇怪怪的。

我比较奇怪你说的上不了网是怎么回事，首先这个插件不应该会导致连**ping**外网都ping不通的情况，但可能会导致出现其他无法正常上网的情况
请按以下步骤测试：
1. `ping 119.29.29.29` 测试ping外网ip，看网络是否通畅，包括ping你的ipv6服务器，测试网络是否断了。
    这一步可以使用`tcping`来测试，更准确。可以了解下ping和tcping的区别
2. `nslookup qq.com` 测试dns解析，分别解析国内和国外的网站域名，确定dns解析是否出问题
    在路由器上可以运行`ps | grep dnsmasq`，间隔几秒多运行几次看看pid值是否会变，来确定dns解析服务是否异常
3. `curl http://163.com` 测试访问网站是否正常

这个插件有一个bug，脚本在某些故障情况下会不断重启，脚本内会重启`dnsmasq`服务，导致dns解析一直不能正常，因此会无法打开网站，但不会影响到ping外网ip。
如果你遇到的是这个情况，使用我release的那个 v2.2.3 包应该可以解决。

**Comment by WROIATE** [comment]
> lienol固件中的`luci-app-unblockmusic`是L大改写的，反正写的奇奇怪怪的。
> 
> 我比较奇怪你说的上不了网是怎么回事，首先这个插件不应该会导致连**ping**外网都ping不通的情况，但可能会导致出现其他无法正常上网的情况
> 请按以下步骤测试：
> 
> 1. `ping 119.29.29.29` 测试ping外网ip，看网络是否通畅，包括ping你的ipv6服务器，测试网络是否断了。
>    这一步可以使用`tcping`来测试，更准确。可以了解下ping和tcping的区别
> 2. `nslookup qq.com` 测试dns解析，分别解析国内和国外的网站域名，确定dns解析是否出问题
>    在路由器上可以运行`ps | grep dnsmasq`，间隔几秒多运行几次看看pid值是否会变，来确定dns解析服务是否异常
> 3. `curl http://163.com` 测试访问网站是否正常
> 
> 这个插件有一个bug，脚本在某些故障情况下会不断重启，脚本内会重启`dnsmasq`服务，导致dns解析一直不能正常，因此会无法打开网站，但不会影响到ping外网ip。
> 如果你遇到的是这个情况，使用我release的那个 v2.2.3 包应该可以解决。

你这个安装包不行，直接打不开
![Snipaste_2020-01-20_22-42-02](https://user-images.githubusercontent.com/44677306/72735163-35ceb200-3bd6-11ea-8146-353d4ef8ed79.png)

**Comment by binsee** [comment]
哦，对，抱歉，这个包需要重新编译，是我的失误
你也可以运行以下命令暂时处理
```
sed -i 's/\r//g' /usr/lib/lua/luci/view/unblockmusic/unblockmusic_status.htm
```
