### ISSUE TITLE
passwall启动守护进程后系统日志出现关于netstat用户ID方面的报错，关掉就正常！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#151]
Thu Jan 16 17:46:29 2020 cron.info crond[18333]: crond (busybox 1.30.1) started, log level 5
Thu Jan 16 17:48:00 2020 cron.info crond[18333]: USER root pid 20750 cmd nohup /usr/share/passwall/monitor.sh > /dev/null 2>&1
Thu Jan 16 17:50:00 2020 cron.info crond[18333]: USER root pid 24120 cmd nohup /usr/share/passwall/monitor.sh > /dev/null 2>&1
Thu Jan 16 17:51:44 2020 daemon.err uhttpd[4331]: netstat: showing only processes with your user ID
Thu Jan 16 17:52:00 2020 cron.info crond[18333]: USER root pid 26405 cmd nohup /usr/share/passwall/monitor.sh > /dev/null 2>&1
Thu Jan 16 17:53:03 2020 daemon.err uhttpd[4331]: netstat: showing only processes with your user ID

**Comment by Lienol** [comment]
不影响使用的，我有空优化一下

**Comment by zxlhhyccc** [comment]
> 不影响使用的，我有空优化一下

我提的这个用户ID问题关闭了，应该是解决了，但是，我重新编译使用启动守护进程仍然发现用户ID问题，只是出现的次数好像减少了一些。另外，在启动passwall前必须先勾选守护进程，否则用户ID问题仍然不停的出现，而且会导致在系统日志中出现：daemon.err uhttpd[14841]: uci: Entry not found

**Comment by zxlhhyccc** [comment]
经测试，启动守护进程后，系统日志中会出现大量的：daemon.err uhttpd[14841]: uci: Entry not found
