### ISSUE TITLE
如何关闭passwall内置的PDNSD缓存？

### ISSUE THREAD

**Issue by aglent** [Lienol/openwrt-package#152]
DNS转发为chinadns-ng
可信dns为pdnsd+tcp解析dns
因为pdnsd带有缓存 可能会导致chinadns-ng判断失误 有些国内网站会返回在国外的ip

我注释了 /etc/pdnsd.conf里的perm_cache语句 但不起作用
后来发现pdnsd的配置文件是动态生成的 /var/etc/passwall/pdnsd/pdnsd.conf
在server块内 有cache语句 应该是这个原因
但不知道如何禁用cache
哪位知道的指点下 谢谢！

**Comment by aglent** [comment]
不知道是不是server块里的cache = on语句的原因 现在pdnsd的缓存还在
www.guancha.cn这个网站的ip经常会获取到香港的ip（因为我的代理是香港节点）
大师如何能解决下更好 没法解决也没关系 我也可以用dns2sock解析 这个是正常的

**Comment by Lienol** [comment]
你测试下，如果可以，帮忙发个pr好吗

**Comment by aglent** [comment]
> 
> 
> 你测试下，如果可以，帮忙发个pr好吗

pr 是什么 需要怎么做

**Comment by hyird** [comment]
> > 你测试下，如果可以，帮忙发个pr好吗
> 
> pr 是什么 需要怎么做

pull requset
