### ISSUE TITLE
开关passwall导致dnsmasq.conf被覆盖

### ISSUE THREAD

**Issue by PatrikYang** [Lienol/openwrt-package#154]
使用lean 最新源码+lienol大大的openwrt-package编译的固件
由于要使用上海的4K IPTV，所以在/etc/dnsmasq.conf中增加了dhcp-option配置
现在发现只要关闭passwall再重新打开passwall，都会将/etc/dnsmasq.conf中添加的配置清空，查看passwall日志发现“dnsmasq：生成配置文件并重启服务。”
对照/etc/dnsmasq.conf的修改时间与日志符合，说明是passwall覆盖了/etc/dnsmasq.conf
请问lienol大大如何解决该问题

**Comment by binsee** [comment]
**你设置错地方了**

通过命令查看dnsmasq服务启动参数如下：
```
root@OpenWrt:~# ps | grep dnsmasq
 8109 dnsmasq   1328 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf.cfg01411c -k -x /var/run/dnsmasq/dnsmasq.cfg01411c.pid
 8214 root      1072 S    grep dnsmasq
```

`/var/etc/dnsmasq.conf.cfg01411c` 内容如下：
```
# auto-generated config file from /etc/config/dhcp
conf-file=/etc/dnsmasq.conf
dhcp-authoritative
domain-needed
filterwin2k
localise-queries
read-ethers
enable-ubus
expand-hosts
bind-dynamic
domain=lan
server=/lan/
dhcp-leasefile=/tmp/dhcp.leases
dhcp-script=/usr/lib/dnsmasq/dhcp-script.sh
resolv-file=/tmp/resolv.conf.auto
stop-dns-rebind
rebind-localhost-ok
dhcp-broadcast=tag:needs-broadcast
addn-hosts=/tmp/hosts
conf-dir=/tmp/dnsmasq.d
user=dnsmasq
group=dnsmasq


dhcp-ignore-names=tag:dhcp_bogus_hostname
conf-file=/usr/share/dnsmasq/dhcpbogushostname.conf

srv-host=_vlmcs._tcp,OpenWrt,1688,0,100
```

正确的设置方法应当到 `网络 - 接口 - LAN`  接口界面下方的 `DHCP服务器 - 高级设置 - DHCP选项`，在此项中设置

![image](https://user-images.githubusercontent.com/5285894/72656979-300c7d00-39da-11ea-8e4d-616eb241c9cd.png)
此配置会写入到文件 `/etc/config/dhcp`

```
config dhcp 'lan'
	option interface 'lan'
	option start '100'
	option limit '150'
	option leasetime '12h'
	list dhcp_option '6,10.0.0.5,10.0.0.2'
```

**dnsmasq**服务启动时会从`/etc/config/dhcp`文件中读取配置，动态生成配置文件

**Comment by PatrikYang** [comment]
非常感谢耐心解答 @binsee

**Comment by binsee** [comment]
解决了的话就Close吧

**Comment by PatrikYang** [comment]
实际测试好像有些问题，添加后整个网络非常缓慢
添加的内容如下
dhcp-option-force=125,00:00:00:00:3a:02:06:48:47:57:2d:43:54:03:04:5a:58:48:4e:0a:02:20:00:0b:02:00:55:0d:02:00:2e:3c:1e:00:00:01:00:02:03:43:50:45:03:0e:45:38:20:45:50:4f:4e:20:52:4f:55:54:45:52:04:03:31:2e:30                                           
dhcp-option=15 
dhcp-option=28
dhcp-option=60,00:00:01:06:35:75:61:71:69:6E:02:0A:48:47:55:34:32:31:4E:20:76:33:03:0A:48:47:55:34:32:31:4E:20:76:33:04:10:32:30:30:2E:55:59:59:2E:30:2E:41:2E:30:2E:53:48:05:04:00:01:00:50
