### ISSUE TITLE
希望最后能把passwall的自动切换完善下

### ISSUE THREAD

**Issue by garypang13** [Lienol/openwrt-package#155]
测试了改代码能强制开启自动切换,设置好备用节点,但是完全不起作用,应该是这个功能还没做好才没开放出来,希望最后能把这个功能完善下.辛苦了.

**Comment by hyird** [comment]
你不会用吧  haproxy

**Comment by garypang13** [comment]
> 你不会用吧 haproxy

自动切换和haproxy负载均衡是两个功能,就和SSR PLUS+的自动切换一样,现在passwall只是用haproxy来实现了类似自动切换的功能而已,但其实passwall是有独立的自动切换功能的,在代码里能找到,只是还没完善好所以把入口隐藏掉了.

**Comment by hyird** [comment]
> wall是有独立的自动切换功能的,在代码里能找到,只是还没完善好所以把入口隐藏掉了.

哦 明白了 我现在就是haproxy 伪自动切换。

**Comment by wefuxkgfw** [comment]
@garypang13 测试

**Comment by viagram** [comment]
支持这个观点。

**Comment by CirnoSalt** [comment]
附议，比如像是隔壁H大老毛子的，虽然总体上不如OP的科学插件，但是在自动切换这一点上就非常省心，支持自动切换到延迟最低的节点，甚至还可以设置节点名称关键词黑名单来防止切换到机场高比率节点。

**Comment by Lienol** [comment]
目前能用，但暂时不支持自动切回主节点（因为在想一个比较靠谱的方案）。
可以找几个比较稳定的节点作为备用节点，效果还是不错的

**Comment by bzdk** [comment]
@Lienol 的确，目前可以切换到备用节点，但是不支持在主节点恢复正常后切换回主节点。
