### ISSUE TITLE
希望能支持局域网内部ip的白名单设置

### ISSUE THREAD

**Issue by flyhigao** [Lienol/openwrt-package#156]
发现现有功能只支持公网ip的白名单
可是局域网内部ip也需要设置白名单

**Comment by WROIATE** [comment]
直接在白名单那设置ip地址段，把你的局域网地址段输进去

**Comment by binsee** [comment]
你的意思是不让局域网内特定ip走passwall吗？在**访问设置**界面中添加这个ip，`代理模式`选择`不代理`

**Comment by flyhigao** [comment]
> 直接在白名单那设置ip地址段，把你的局域网地址段输进去
就是这个功能不支持内网ip白名单，输了也没用

**Comment by flyhigao** [comment]
> 你的意思是不让局域网内特定ip走passwall吗？在**访问设置**界面中添加这个ip，`代理模式`选择`不代理`

多谢，之前没看到这个功能，可以生效。
