### ISSUE TITLE
希望可以内置serverchan插件

### ISSUE THREAD

**Issue by binsee** [Lienol/openwrt-package#159]
serverchan是一个向微信推送消息的服务，`luci-app-serverchan`插件可以让路由器向微信推送消息，如设备上下线、外网ip变动、设备负载情况等，对于部分人还是有用的。
因此希望可以在固件内直接集成

比较好用的包项目地址：https://github.com/tty228/luci-app-serverchan

支持内置此插件的，可以点个 +1，以便Lienol参考有多少人希望添加

**Comment by leo8912** [comment]
支持。。

**Comment by cjameslynn** [comment]
+0

**Comment by WROIATE** [comment]
这个用shell写个脚本发邮件就行，具体教程网上挺多，用ssmtp发邮件，剩下的条件判断ip变动shell挺简单的，把脚本加到计划任务里每隔一段时间检查一次就行

**Comment by hyird** [comment]
这个插件速度感人 延迟比较大  还不太准备  还想是因为wifi休眠的关系

**Comment by danety** [comment]
支持

**Comment by lloyd18** [comment]
上次用了卡死，一直占用CPU 20% 就不敢再用了
