### ISSUE TITLE
编译更新后的luci-app-filebrowser，仍无法下载版本，见报错截图！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#16]
![96OT82~RD9_H_V5PYA_SK0W](https://user-images.githubusercontent.com/45259624/61473231-94616c00-a9b8-11e9-9ca9-16891176569f.png)

**Comment by Lienol** [comment]
MIPS架构官方没有编译好的包。
下次发Issues麻烦发机型

**Comment by zxlhhyccc** [comment]
嗯嗯，是斐讯K3。。。。

**Comment by Lienol** [comment]
我用朋友的k3试是可以的...

**Comment by zxlhhyccc** [comment]
我是直接卸载插件重新安装更新后的，不行，我再试试重新编译固件刷机。。。。
