### ISSUE TITLE
passwall最新版本遇到一个非常奇怪的问题，用旧版的节点配置文件恢复能正常运行，但手工输入节点却无法运行！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#162]

**Comment by zxlhhyccc** [comment]
手动设置配置无法运行：
![O3I4 DEK}23GA3PP%XCAX7K](https://user-images.githubusercontent.com/45259624/72683294-0dc94b00-3b11-11ea-912d-99bef1f48d8e.png)
以前的配置文件替换后能正常运行：
![image](https://user-images.githubusercontent.com/45259624/72683307-2b96b000-3b11-11ea-9b8b-2556ef86dacf.png)

添加节点的配置绝对正确。。。。

**Comment by zxlhhyccc** [comment]
已找到不能运行的原因，源码的配置文件缺少一行指定v2ray的代码，加上就正常了，代码是：
option v2ray_protocol 'vmess'

**Comment by Lienol** [comment]
Fixed
