### ISSUE TITLE
V2Ray 负载均衡 UDP 显示 未运行

### ISSUE THREAD

**Issue by HueLiu** [Lienol/openwrt-package#167]
Hi Lienol,

2020.01.21 版本的固件中新添加的 V2Ray 负载均衡的功能似乎有点小问题需要向你核实情况:P

- 浏览器隐私模式下操作
- 设置 TCP 为 V2Ray 负载均衡节点
- 设置 UDP 节点为“V2Ray负载均衡节点”或“与TCP节点相同”
- 提交保存后，日志提示「运行完成！」，且实测能够正常进行代理访问网页，但 Passwall 首页界面顶部的 UDP 图示提示未运行。

可能需要核实一下是 Feature 还是 Bug :)

Thank you.

**Comment by xiaorouji** [comment]
是因为写的时候漏了 抱歉，已经修复
