### ISSUE TITLE
发现一个添加节点的bug

### ISSUE THREAD

**Issue by hyird** [Lienol/openwrt-package#168]
如题目 在节点列表 点击 “添加” 然后 直接返回的情况下 就会出现500内部服务错误

**Comment by hyird** [comment]
发现了原因  在节点列表 点击 “添加” 然后 直接返回的情况  /etc/config/passwall 会多出一行 config nodes 下方无任何内容 这样就会导致 500内部服务器错误 删除就好 希望能够尽快修复

**Comment by zxlhhyccc** [comment]
> 如题目 在节点列表 点击 “添加” 然后 直接返回的情况下 就会出现500内部服务错误

确实是这个情况，希望大佬百忙中修复一下。。。。

**Comment by Lienol** [comment]
听说修复了，你们更新最新源码试试

**Comment by hyird** [comment]
> 听说修复了，你们更新最新源码试试

还有就是argon主题的 登录界面 没有背景 除了 argon_dark
