### ISSUE TITLE
用官方19.07源码自行编译控制台能ping通baidu但是界面显示连接失败

### ISSUE THREAD

**Issue by sheiy** [Lienol/openwrt-package#169]
![image](https://user-images.githubusercontent.com/12210038/72824389-21f77e80-3cb0-11ea-8a07-a7ac77bfb647.png)
![image](https://user-images.githubusercontent.com/12210038/72824417-2d4aaa00-3cb0-11ea-9090-fa5bde84d4e2.png)
google ping不通 是编译的时候什么东西选露了嘛？

**Comment by sheiy** [comment]
我试试，感谢大佬这么晚回复，谢谢啊

**Comment by sheiy** [comment]
@zxlhhyccc 用官方master分支一样的问题

[config.txt](https://github.com/Lienol/openwrt-package/files/4094751/config.txt)
这是我的.config文件

**Comment by Lienol** [comment]
没有wget或curl

**Comment by sheiy** [comment]
可以了，感谢，
opkg update 会去拉这个http://downloads.openwrt.org/snapshots/packages/x86_64/lienol/Packages.gz

**Comment by sheiy** [comment]
勾选：
network------->file transfer------->wget和curl和wget-nossl

**Comment by sheiy** [comment]
使用dnsmq-full不要dnsmq

**Comment by sheiy** [comment]
还有readme里的那三个依赖

**Comment by sheiy** [comment]
修改 /etc/opkg/distfeeds.conf 把Lienol那一行注释掉 不然opkg update会报错
