### ISSUE TITLE
小问题反馈

### ISSUE THREAD

**Issue by fuqiang03** [Lienol/openwrt-package#17]
![QQ截图20191018114619](https://user-images.githubusercontent.com/26851715/67064388-00f92c00-f19d-11e9-8557-90fc337a13b7.png)
页面停留几秒中就会这样 无限了

**Comment by Lienol** [comment]
更新最新源码再试试

**Comment by fuqiang03** [comment]
![QQ截图20191018191806](https://user-images.githubusercontent.com/26851715/67090215-180b3e80-f1dc-11e9-959f-ba912c7e4a74.png)
不在刷新了 已经好了
