### ISSUE TITLE
重启后负载均衡不能自动开启

### ISSUE THREAD

**Issue by Zack0617** [Lienol/openwrt-package#170]
系统是官方19.07.0,设置好负载均衡且正常运行，重启系统后主页面显示负载均衡未运行，只能手动重启一次才能运行。

**Comment by Lienol** [comment]
系统 - 启动项 找到 haproxy，按一下第一个按钮，变成 “已禁用”，重启后再试试

**Comment by Zack0617** [comment]
换回官方18.06.6没有这个问题了，感觉还是1806兼容性更好，访问控制那里添加的选项在1907下显示不全，1806下就正常。
