### ISSUE TITLE
升级不能保存配置

### ISSUE THREAD

**Issue by hyird** [Lienol/openwrt-package#174]
1。 刚刚编译最新的ipk  安装最新的ipk 配置就会丢 设置全变成默认的了。
2.。 希望在没有安装chiandns-ng 或者dns2sock的情况下能够隐藏 选项

**Comment by Lienol** [comment]
单独安装ipk是这样的

**Comment by Kaiyuan** [comment]
> 单独安装ipk是这样的

能不能增加以下配置文件保存？通常都是单独安装 ipk，而且升级也是单独更新 ipk。不可能每次更新都重刷固件的。

**Comment by wefuxkgfw** [comment]
> 
> 
> > 单独安装ipk是这样的
> 
> 能不能增加以下配置文件保存？通常都是单独安装 ipk，而且升级也是单独更新 ipk。不可能每次更新都重刷固件的。

固件也可以保留配置升级。。
