### ISSUE TITLE
luci-app-passwall BUG

### ISSUE THREAD

**Issue by lyin888** [Lienol/openwrt-package#177]
luci-app-passwall 的访问控制添加选项的时候chrome浏览器无法选择IP与MAC，用chrome选择保存后没有IP与MAC，自定义也无法填写，切换IE才搞定，不知道这个问题是luci-app-passwall的锅还是chrome的锅。

忘记说明了，源码用的coolsnowwolf L大雕的.

**Comment by aglent** [comment]
firefox 70 没发现这个问题

**Comment by kang-mk** [comment]
chrome木有发现这个问题
