### ISSUE TITLE
局域网有一台比特彗星下载的专用电脑请问如何设置password的访问控制？

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#179]
这台机器因为比特彗星和迅雷里面需要用到这个trackerlist
https://github.com/ngosang/trackerslist
也就是需要让他翻墙，但是实际上bt下载的视频又不希望他走v2ray的通道。
但是有时候如果访问rarbg或者其他网站又需要翻墙。
这台机器要怎么设置，才不会影响
https://github.com/ngosang/trackerslist
又可以不用占用gcp服务器的流量？
请赐教。谢谢了。

**Comment by Lienol** [comment]
自己结合 访问控制 TCP/UDP转发端口 黑白名单 使用

**Comment by norikohxb** [comment]
bt下载更新trackerlist 这个是采用tcp还是udp？
https://github.com/ngosang/trackerslist
这个
是采用tcp的吧，怎么在自定义设置里面，让192.168.6.99（下载机器）只能tcp代理，udp不代理？

**Comment by hyird** [comment]
比特彗星 监听的端口可以设置固定 自己设置那个端口不走passwall就好
