### ISSUE TITLE
passwall里面的谷歌连接不通

### ISSUE THREAD

**Issue by czxinshui** [Lienol/openwrt-package#18]

**Comment by Lienol** [comment]
路由器本机黑名单有没有加入google.com？

**Comment by czxinshui** [comment]
> 路由器本机黑名单有没有加入google.com？

你好，问题已经解决了，是因为广告屏蔽插件开启引起的，加入白名单可以解决。
现在反映一件其他的事。
SSR插件中的【服务端列表】【节点备注】也就是节点名称这一项。名称有点优化过头，显示的只有"订阅_[vip1]"其他任何信息都有，如果可以 请问是否可以修改得更容易看一点。

下面图片就是你的版本区和LEAN的区别。

https://imgchr.com/i/KaqMnK
