### ISSUE TITLE
有时候会突然上不了谷歌

### ISSUE THREAD

**Issue by XiaoliChan** [Lienol/openwrt-package#180]
有时候会突然上不了谷歌，但是在页面检测访问谷歌是正常的，还有就是能不能把udpspeeder+udp2raw也添加进页面，既然是游戏模式的话

**Comment by wefuxkgfw** [comment]
@XiaoliChan 看下频道的tips…

**Comment by wefuxkgfw** [comment]
@XiaoliChan https://t.me/passwall/840

**Comment by XiaoliChan** [comment]
> @XiaoliChan https://t.me/passwall/840

我并不是单臂路由

**Comment by wefuxkgfw** [comment]
@XiaoliChan ？？？？单臂路由那个是解决访问不了国内网站的…
你不是说偶尔上不了谷歌的吗…
NTM在逗我？

**Comment by XiaoliChan** [comment]
> @XiaoliChan ？？？？单臂路由那个是解决访问不了国内网站的…
> 你不是说偶尔上不了谷歌的吗…
> NTM在逗我？

...看走眼了....
