### ISSUE TITLE
不能获得http代理端口。希望passwall高级设置中的代理配置添加HTTP代理端口设置功能。

### ISSUE THREAD

**Issue by wojuzi** [Lienol/openwrt-package#181]
因为在特殊情况下需要使用代理，不论是安卓手机还是win10自带代理设置都只支持HTTP端口代理，然而passwall只有socks5代理端口设置，没有HTTP端口代理设置，希望作者大大能够辛苦添加。另外，有没有默认的HTTP代理端口？80和443我都试过，没有用。希望作者大大能够告知？感激不尽。
![image](https://user-images.githubusercontent.com/52819651/73264986-f7a54400-420e-11ea-80cc-498f8dcb62a6.png)

**Comment by Lienol** [comment]
没有

**Comment by kukat** [comment]
同求http代理

**Comment by Lienol** [comment]
没这个需求，socks还不够用吗？

**Comment by wefuxkgfw** [comment]
> 
> 
> 没这个需求，socks还不够用吗？

个别App本身允许的代理设置，比如推，特只允能用http代理。

**Comment by EdmundFlint** [comment]
感谢大大，同希望有这功能

**Comment by sheiy** [comment]
+1

**Comment by kukat** [comment]
暂时先用polipo转换一下也能用

```
opkg install polipo
```
配置文件在 /etc/config/polipo
重点是允许访问的ip段，也就是你的内网ip段
	list 'allowedClients' '192.168.0.0/24'
和上级代理的配置
	option socksParentProxy '127.0.0.1:1080'
	option socksProxyType socks5

example
```
# polipo daemon configuration
config 'polipo' 'daemon'
	# daemonise polipo (fork in background)
	option 'daemonise' '1'
	# where polipo will store its process pid
	option 'pidFile' '/var/run/polipo.pid'

config 'polipo' 'general'
	option 'enabled' '1'
	# address on which polipo will listen, 0.0.0.0 means all addresses
	option 'proxyAddress' '0.0.0.0'
	# port on which polipo will listen, default is 8123
	#option 'proxyPort' '8123'
	# list of allowed clients to connect
	list 'allowedClients' '192.168.0.0/24'
	#list 'allowedClients' '127.0.0.1'
	#list 'allowedClients' '192.168.2.1'
	# how much RAM memory should Polipo use (in bytes).
	option 'chunkHighMark' '1048576'
	# enable disk cache index and serverlist of integrated polipo web interface
	#option 'disableIndexing' '0'
	#option 'disableServersList' '0'
	# disable loging to syslog
	option 'logSyslog' '0'
	# set log file location (disabled when not set)
	#option 'logFile' '/mnt/usbdrive/polipo/log'
	option socksParentProxy '127.0.0.1:1080'
	option socksProxyType socks5

config 'polipo' 'cache'
	# disk cache location, you should always use external storage device
	# (disabled when not set)
	#option 'diskCacheRoot' '/mnt/usbdrive-p2/polipo/cache'
	# disk cache cleanup settings
	#option 'diskCacheUnlinkTime' '20d'
	#option 'diskCacheTruncateTime' '5d'
	#option 'diskCacheTruncateSize' '3145728'
	# set to 1 if proxy is used by multiple users
	#option 'cacheIsShared' '1'

config 'polipo' 'pmm'
	# poor man's multiplexing semgnet size to fetch
	#option 'pmmSize' '8192'
```

**Comment by Xuchengen** [comment]
我建议添加HTTP代理，Java开发工具IDEA代理只支持HTTP代理。

**Comment by sheiy** [comment]
> 我建议添加HTTP代理，Java开发工具IDEA代理只支持HTTP代理。

idea支持socket啊

**Comment by lovestudygithub** [comment]
> 
> 
> 暂时先用polipo转换一下也能用
> 
> ```
> opkg install polipo
> ```
> 
> 配置文件在 /etc/config/polipo
> 重点是允许访问的ip段，也就是你的内网ip段
> 
> ```
> 	list 'allowedClients' '192.168.0.0/24'
> ```
> 
> 和上级代理的配置
> 
> ```
> 	option socksParentProxy '127.0.0.1:1080'
> 	option socksProxyType socks5
> ```
> 
> example
> 
> ```
> # polipo daemon configuration
> config 'polipo' 'daemon'
> 	# daemonise polipo (fork in background)
> 	option 'daemonise' '1'
> 	# where polipo will store its process pid
> 	option 'pidFile' '/var/run/polipo.pid'
> 
> config 'polipo' 'general'
> 	option 'enabled' '1'
> 	# address on which polipo will listen, 0.0.0.0 means all addresses
> 	option 'proxyAddress' '0.0.0.0'
> 	# port on which polipo will listen, default is 8123
> 	#option 'proxyPort' '8123'
> 	# list of allowed clients to connect
> 	list 'allowedClients' '192.168.0.0/24'
> 	#list 'allowedClients' '127.0.0.1'
> 	#list 'allowedClients' '192.168.2.1'
> 	# how much RAM memory should Polipo use (in bytes).
> 	option 'chunkHighMark' '1048576'
> 	# enable disk cache index and serverlist of integrated polipo web interface
> 	#option 'disableIndexing' '0'
> 	#option 'disableServersList' '0'
> 	# disable loging to syslog
> 	option 'logSyslog' '0'
> 	# set log file location (disabled when not set)
> 	#option 'logFile' '/mnt/usbdrive/polipo/log'
> 	option socksParentProxy '127.0.0.1:1080'
> 	option socksProxyType socks5
> 
> config 'polipo' 'cache'
> 	# disk cache location, you should always use external storage device
> 	# (disabled when not set)
> 	#option 'diskCacheRoot' '/mnt/usbdrive-p2/polipo/cache'
> 	# disk cache cleanup settings
> 	#option 'diskCacheUnlinkTime' '20d'
> 	#option 'diskCacheTruncateTime' '5d'
> 	#option 'diskCacheTruncateSize' '3145728'
> 	# set to 1 if proxy is used by multiple users
> 	#option 'cacheIsShared' '1'
> 
> config 'polipo' 'pmm'
> 	# poor man's multiplexing semgnet size to fetch
> 	#option 'pmmSize' '8192'
> ```

感谢提供这个办法。
