### ISSUE TITLE
passwall插件复用ip

### ISSUE THREAD

**Issue by klever1988** [Lienol/openwrt-package#184]
在保存配置，插件重启的时候，之前由pdnsd解析保存的ip规则会被清空，浏览器和操作系统因为有解析缓存，不会再次请求pdnsd重新解析ip，导致除非清空缓存，否则很长时间无法打开被q网站

所以能不能改进一下，在重启插件的时候，继承前期解析生成的ip

**Comment by ShanStone** [comment]
复用可能会导致更换不同地区节点时请求cdn资源时舍近求远，上网速度因此变慢，所以还是手动刷新一下dns吧
