### ISSUE TITLE
更新是用git pull吗，这个错误是什么原因？

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#185]
可尝试本人基于大雕源码 跟着README操作即可
编译命令如下:

1. 首先装好 Ubuntu 64bit，推荐  Ubuntu  14 LTS x64

2. 命令行输入 sudo apt-get update ，然后输入
sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler

3. git clone https://github.com/Lienol/lean-lede 命令下载好源代码，然后 cd lean-lede 进入目录

4. ./scripts/feeds update -a
   ./scripts/feeds install -a
   make menuconfig 

5. 最后选好你要的路由，输入 make -j1 V=s （-j1 后面是线程数。第一次编译推荐用单线程，国内请尽量全局科学上网）即可开始编译你要的固件了。

本套代码保证肯定可以编译成功。里面包括了 R9 所有源代码，包括 IPK 的。

之后如果要升级源代码？
是不是也是用  git pull来升级呢？
直接在 lean-lede目录下
直接git pull对吗？

git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by Lienol** [comment]
git pull --rebase
如果不行就
git fetch --all
git reset --hard origin/master
git pull
