### ISSUE TITLE
可否直接提供编译好的 x64 平台 ipk

### ISSUE THREAD

**Issue by Kaiyuan** [Lienol/openwrt-package#187]
我使用的是原版 OpenWrt。

因为新手编译，我卡在 OpenWrt 原版固件编译上，有几个依赖弄不好所以不成功，结果就无法编译 ipk 出来，用的是别人编译的 ipk，但是别人编译的更新不快，旧版有 BUG 时候无法快速更新到新版。

如果每个修 BUG 版本更新时候能提供编译好的 ipk 的话就好了。

我还在弄我的几个没弄好的依赖...

**Comment by Lienol** [comment]
如果你不想排坑的话，建议直接使用
[基于大雕源码](https://github.com/Lienol/lean-lede)
或
[基于官方openwrt19.07分支源码](https://github.com/Lienol/openwrt)

**Comment by cielpy** [comment]
想问一下，[基于官方openwrt19.07分支源码](https://github.com/Lienol/openwrt) 这个和 OpenWrt 原版的 19.07 相比有什么特色或者差别呢？

**Comment by cielpy** [comment]
可以用 Docker 编译安装，应该不用踩坑，已经测试可以编译通过了 

项目 https://github.com/cielpy/DockerOpenWrtPackagesBuilder 

项目介绍和使用 https://imciel.com/2021/03/23/build-openwrt-packages-with-docker-openwrt-sdk/
