### ISSUE TITLE
lienol为什么今天把您的passwall编译到nano pi R1S会

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#189]
为什么编译到nano pi R1S里面去
菜单名字，变成了 飘扬过来还看你？
而编译到x86里面是   正确的上网方式
这个名字是您修改的还是我哪里编译错了？

**Comment by Lienol** [comment]
？？？？？？

**Comment by norikohxb** [comment]
VPN
正确上网姿势 √

变成了
VPN
漂洋过海来看你

**Comment by norikohxb** [comment]
我今天刚编译的。

**Comment by norikohxb** [comment]
麻烦您拨冗看一下贴图

https://www.right.com.cn/forum/thread-2543169-1-1.html
我不知道要怎么在github上传贴图。
借用恩山的给你看看

**Comment by Lienol** [comment]
你确定用的是我的源码？

**Comment by norikohxb** [comment]
可尝试本人基于大雕源码 跟着README操作即可
从你这里进去
到了这里
https://github.com/Lienol/lean-lede
这个是你的对吧
git pull更新
然后
cp -r /home/vehxb/lean-lede/package/feeds/lienol  /home/vehxb/friendlywrt-h5/friendlywrt/package/feeds/
把你的feeds都复制到 friendlywrt的package的feeds里面

然后编译。这里面有错吗？

**Comment by norikohxb** [comment]
我也编译您的x86的
今天刚编译好您的x86的
https://github.com/Lienol/lean-lede

按照这个编译。编译出来的最新版本的，菜单是  正确上网姿势。

编译好了这个肯定是您的最新的
然后我把编译您x86的这个目录的feeds 复制到 friendlywrt里面去嫁接
cp -r /home/vehxb/lean-lede/package/feeds/lienol  /home/vehxb/friendlywrt-h5/friendlywrt/package/feeds/
这句没有毛病吧。
复制过后。在friendlywrt目录里面执行了一次
./scripts/feeds update -a && ./scripts/feeds install -a
rm -rf ./tmp && rm -rf .config	
make menuconfig
配置菜单，然后开始编译。

更新friendlywrt-h5官方固件
cd friendlywrt-h5
repo sync --no-clone-bundle

 ./build.sh nanopi_r1s.mk

**Comment by norikohxb** [comment]
不过这个friendlywrt-h5\friendlywrt\package
里面也复制了最新的lean大的package
cp -r  /home/vehxb/lede/package/lean /home/vehxb/friendlywrt-h5/friendlywrt/package/

难道是lean大的那个make menuconfig 把您的这个该名称为 “漂洋过海来看你”

**Comment by norikohxb** [comment]
因为没有发布如何编译R1S+您的passwall的教程，我是觉得你的passwall好像在yotuube测速是会快一些，更容易拉到最大宽带。所以我就把你的passwall，加入到R1S里面去。我这样加对不对？

**Comment by norikohxb** [comment]
坐等大神解答。我这边是不是哪个步骤没有做对？

**Comment by Lienol** [comment]
估计是你用的那个 friendlywrt 源码 里面的改动吧

**Comment by norikohxb** [comment]
之前不会，在之前的一个版本是不会的，但是我今天更新了friendlwrt，因为既然要编译都要弄最新的
friendlywrt我用最新的
lean package我用最新的
你的 lienol我用最新的。
唯一的解释就是r1s的friendly把你的名字叫做 “漂洋过海来看你了”

能否请教一下，为什么按照你的git hub里面的教程编译了openwrt，是没有网卡的，无法修改i，也找不到network这个配置文件。

**Comment by norikohxb** [comment]
https://github.com/Lienol/openwrt-package/issues/188
这个能帮我解答一下吗
我编译lean的，编译你的git hub的你在lean op上修改的这个也都可以轻松成功
编译r1s也可以成功，就是编译openwrt，编译完毕是没有网卡属性的

**Comment by norikohxb** [comment]
我搞定了我的openwrt了，谢谢你的提醒

**Comment by gjgj3368** [comment]
> #188
> 这个能帮我解答一下吗
> 我编译lean的，编译你的git hub的你在lean op上修改的这个也都可以轻松成功
> 编译r1s也可以成功，就是编译openwrt，编译完毕是没有网卡属性的

兄弟，我也想知道，这是什么原因？求赐教。
