### ISSUE TITLE
负载均衡一启用 就反复的运行

### ISSUE THREAD

**Issue by billy-zheng** [Lienol/openwrt-package#19]
J1900软路由，openwrt系统，passwall 版本：2.0-80-20190824

负载均衡启动后，整个插件就反复启动，从日志上就能出来，每隔几分钟，脚本重新启动一次。不知道是什么原因？

**Comment by Lienol** [comment]
更新最新源码再试试

**Comment by billy-zheng** [comment]
你好，因为没找到ipk文件，昨天把share/passwall下的所有sh文件替换了旧版的文件，也修改了文件权限。结果是插件无法运行，无法启动任何一个服务器。日志那里也不出现任何消息。

**Comment by billy-zheng** [comment]
你好。在win10上安装WSL ubuntu，但是想单独编译这个ipk的时候一直报错。 以前没弄过这个，请问能否帮忙编译一个。

**Comment by billy-zheng** [comment]
已经自己编译并安装成功，目前新版没有出现旧版负载均衡反复启动的问题，但出来个新的bug，ssr的订阅连接填进去后，点更新保存没反应。节点目前需要手工导入。
