### ISSUE TITLE
请教lienol大可尝试本人基于官方openwrt19.07分支源码 神秘的优化速度！

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#190]
https://github.com/Lienol/openwrt

我用这个编译完毕是35MB对吗？然后我复制到esxi的虚拟机里面是找不到网卡配置文件
也就是没有ip的，网络是没有启动的
这个问题出在哪里，
lienol能否帮忙一下

**Comment by Lienol** [comment]
Target Images ---> Root filesystem partition size 看看

**Comment by norikohxb** [comment]
谢谢你，马上试试看，非常感谢

**Comment by norikohxb** [comment]
*** Root filesystem images ***                                                      x x  
  x x                 [ ] ext4  ----                                                                          x x  
  x x                 [*] squashfs  --->                                                                      x x  
  x x                 [*] Build GRUB images (Linux x86 or x86_64 host only)                                   x x  
  x x                 [*]   Use Console Terminal (in addition to Serial)                                      x x  
  x x                 (ttyS0) Serial port device                                                              x x  
  x x                 (115200) Serial port baud rate                                                          x x  
  x x                 [ ] Use RTE/CTS on serial console                                                       x x  
  x x                 ()  Extra kernel boot options                                                           x x  
  x x                 (0) Seconds to wait before booting the default entry                                    x x  
  x x                 (OpenWrt) Title for the menu entry in GRUB                                              x x  
  x x                 [ ] Build VirtualBox image files (VDI)                                                  x x  
  x x                 [ ] Build VMware image files (VMDK)                                                     x x  
  x x                 [ ] Pad images to filesystem size (for JFFS2)                                           x x  
  x x                 [*] GZip images                                                                         x x  
  x x                     *** Image Options ***                                                               x x  
  x x                 (16) Kernel partition size (in MB)                                                      x x  
  x x                 (160) Root filesystem partition size (in MB)                                            x x  
  x x                 ()  Root partition on target device   

我进入了，请问是哪个选项？能否更具体一点？

**Comment by norikohxb** [comment]
是勾选ext4 吗？
不勾选这个我就无法得到网卡配置？

**Comment by norikohxb** [comment]
root filesystem partition size in MB=160MB
但是编译之后是35MB

**Comment by norikohxb** [comment]
帮忙一下咯，这个问题困扰我很久了很想要用用你的openwrt19.07分支源码
