### ISSUE TITLE
请教lienol大可尝试本人基于官方openwrt19.07分支源码 神秘的优化速度

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#191]
https://github.com/Lienol/openwrt

我用这个编译完毕是35MB对吗？然后我复制到esxi的虚拟机里面是找不到网卡配置文件
也就是没有ip的，网络是没有启动的
这个问题出在哪里，
lienol能否帮忙一下
root filesystem partition size in MB=160MB
但是编译之后是35MB

**Comment by flyhigao** [comment]
我刚好昨天编译了，放在kvm虚拟机里用。双网卡一切正常。
我猜你创建虚拟机没有加网卡？

**Comment by norikohxb** [comment]
我手贱，把 image里面的那个pad给去掉了lean大的精简是可以去掉的。
谢谢你了
