### ISSUE TITLE
lienol大你的2个作品哪个好一些？

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#192]
https://github.com/Lienol/openwrt

https://github.com/Lienol/lean-lede

lienol 大，我现在这几个都编译成功了，非常感谢你提供的教程

这两个都是出自您手
你觉得这两个哪个好一些？
我都编译好了，从代码优化上来说
这两个你觉得哪个好一点？

**Comment by wefuxkgfw** [comment]
上边一个。因为luci特别优化过了。
