### ISSUE TITLE
socks节点选择增加自动跟随TCP服务器选项，就像UDP服务器有个“与TCP节点相同”

### ISSUE THREAD

**Issue by hahaher123** [Lienol/openwrt-package#196]
Lienol大佬你好：
      我现在使用您的passwall插件上网时，外网dns解析使用“dns2socks+socks5节点解析dns”模式，此时需要选择开启socks节点，当我更换不同地区tcp节点时，socks节点也必须手动更换，可否增加一个类似UDP节点的“与TCP节点相同”选项，自动跟随切换到相同的TCP节点上。

**Comment by hyird** [comment]
这个可以有

**Comment by kang-mk** [comment]
这个可以有

**Comment by bingrenyg** [comment]
同求
