### ISSUE TITLE
argon mod : update	之后所有的argon主题都不能应用了

### ISSUE THREAD

**Issue by kang-mk** [Lienol/openwrt-package#198]
如题，所有的argon主题设置之后无效，还是原来的主题，其他主题正常，自己编译的和Lienol大佬自己openwrt-actions编译的都一样的问题

**Comment by greennyreborn** [comment]
最新的commit 还是有这个问题

**Comment by kang-mk** [comment]
themes : argon-mod : fix bug and format	
前天好像反馈过之后，就修复了啊，我编译了一版，已经没问题了
