### ISSUE TITLE
passwall希望可以增加一个恢复默认设置的功能

### ISSUE THREAD

**Issue by kang-mk** [Lienol/openwrt-package#199]
希望可以增加一个passwall插件恢复默认设置的功能，如果passwall设置错误，导致出现错误，或者比如现在的passwall更新速度快，默认参数也有都在调整，如果直接从之前的固件升级上来的，很多设置都还是旧的参数，还需要对比新版固件更新了什么参数
如果有passwall恢复默认设置的功能就方便很多了，直接恢复默认设置，再重新设置就好了，否则就只能重新恢复固件的默认设置，那连其他的所有插件的设置和防火墙端口转发等等也全部恢复了，再次设置就会麻烦很多

**Comment by Lienol** [comment]
不错的建议

**Comment by Lienol** [comment]
不错的建议

**Comment by wefuxkgfw** [comment]
竟然采纳了…
