### ISSUE TITLE
请教在.config文件选择了以下三个依赖会出现nginx冲突。。。

### ISSUE THREAD

**Issue by hexsen929** [Lienol/openwrt-package#2]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-kodexplorer:
 * 	nginx-ssl
 * 	php7-fastcgi
 * 	php7-mod-dom
 * opkg_install_cmd: Cannot install package luci-app-kodexplorer.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/song/lede'
package/Makefile:108: recipe for target '/home/song/lede/staging_dir/target-x86_64_musl/stamp/.package_install' failed
make[1]: *** [/home/song/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/song/lede'
/home/song/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by 759071793** [comment]
使用lede最新源码编译的，编译之前把lean原来的 luci-app-kodexplorer删除替换的Lienol大佬的文件
