### ISSUE TITLE
SSR节点名称过于简约，以后是否会升级？

### ISSUE THREAD

**Issue by czxinshui** [Lienol/openwrt-package#20]
你好，现在反映一件事。
在SSR插件中的【服务端列表】【节点备注】也就是节点名称这一项。名称有点优化过头，显示的只有"订阅_[vip1]"其他任何信息都有，如果可以 请问是否可以修改得更容易看一点。

下面图片就是你的版本区和LEAN的区别。

https://imgchr.com/i/KaqMnK

**Comment by Lienol** [comment]
有空就会更新，最好提供下订阅地址

**Comment by czxinshui** [comment]
> 有空就会更新，最好提供下订阅地址
您已经5天没更新了。没被请喝茶吧

**Comment by czxinshui** [comment]
测试了5个机场的节点。可以看到完整的了。谢谢。如果可以。在订阅后面能显示机场的名字。毕竟5个订阅地址放下去很是很乱的
