### ISSUE TITLE
lienol大大求助一下。

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#200]
我要把您的passwall编译到friendywrt H5 里面去
运行了这个命令
cp -r /home/vehxb/lean-lede/package/feeds/lienol  /home/vehxb/friendlywrt-h5/friendlywrt/package/feeds/
为何复制到目标文件夹里面的 leinol的文件夹全部变成红色的，也不可以进入。
原来在你的目录里面的每个目录都是淡蓝色，到了目标文件夹全部变成红色

**Comment by norikohxb** [comment]
我最后只好用xshell的复制，
在命令提示符里面用cp的命令，复制到目的地都是红色，请问如何解决这个问题

**Comment by Lienol** [comment]
没用过friendlywrt不清楚，实际上应该差不多。
我的openwrt-package README已经有使用方法
