### ISSUE TITLE
Trojan 默认规则列表是否可以添加下 etsy.com 谢谢 老哥 Lienol

### ISSUE THREAD

**Issue by chnexpats** [Lienol/openwrt-package#201]
Trojan 默认规则列表是否可以添加下 etsy.com 谢谢 老哥 Lienol，其他协议都没问题，大陆白名单 或者 GFW 模式都不能打开这个网站，麻烦老哥帮添加下下，谢谢啦。

**Comment by Lienol** [comment]
自己加入黑名单
