### ISSUE TITLE
passwall里面建议新增一个负载均衡的自动添加节点功能

### ISSUE THREAD

**Issue by kang-mk** [Lienol/openwrt-package#202]
passwall里面建议新增一个负载均衡的自动添加节点功能
现有的模式下开启负载均衡之后需要手动在节点里面添加负载均衡的节点
如果可以在开启负载均衡的时候自带添加一个现有的负载均衡节点就会方便很多
关闭负载均衡的时候倒是可以默认直接删除

**Comment by zlkent** [comment]
是的，之前用koolshare的ss插件，会自动添加，比较方便，刚更换成passwall后没看到，以为处理机制不一样，查了教程才发现要自己手动加，这对新用户可能会造成困惑。
另外，负债均衡的添加节点功能略繁琐，希望可以实现koolshare里自带的ss添加方法，只要选中一个服务器，点击添加就自动添加到列表里，并且选中框自动跳到下一个服务器，这样只要点击添加按钮就能完成大量的服务器添加了。

**Comment by kang-mk** [comment]
@zlkent 哈哈，之前我用LEAN大固件的时候，SSR和负载均衡的插件完全是分开的，搞的我一头雾水，后来搜索了不少教程才弄明白，负载均衡的原理，才学会的设置，否则就是一脸懵逼

**Comment by dabster163** [comment]
其实更希望负载均衡能够做到v2ray，现在只支持ss+trojan的相同配置

**Comment by kang-mk** [comment]
@dabster163 V2也可以用HAProxy来负载均衡的啊，只需要把ID和协议 加密全部设置为一样的即可
![snipaste20200212_181032](https://user-images.githubusercontent.com/20243226/74325105-0bca7300-4dc3-11ea-9fe7-1c49a58934a8.jpg)
如图，我设置的这两种都是V2的负载均衡，一种是V2自带的，一种就是采用HAProxy方式的

**Comment by kang-mk** [comment]
@dabster163 
![snipaste20200212_181032](https://user-images.githubusercontent.com/20243226/74325283-47fdd380-4dc3-11ea-909f-13481b7bb729.jpg)

**Comment by kang-mk** [comment]
V2自带的负载均衡，可以支持不同ID不同协议的多个节点，HAProxy这种必须ID和协议完全一样才行

**Comment by zlkent** [comment]
> @zlkent 哈哈，之前我用LEAN大固件的时候，SSR和负载均衡的插件完全是分开的，搞的我一头雾水，后来搜索了不少教程才弄明白，负载均衡的原理，才学会的设置，否则就是一脸懵逼

我是打算转到L大的固件的，但ssr+还是没ks的ss好用，直到发现了passwall，我决定放弃ks了

**Comment by pidou122** [comment]
> @dabster163
> ![snipaste20200212_181032](https://user-images.githubusercontent.com/20243226/74325283-47fdd380-4dc3-11ea-909f-13481b7bb729.jpg)

请教，按照你的设置，域名这里输入本地ip地址，如果有多个v2ray都这样设置的话，会自动负载均衡？

**Comment by dabster163** [comment]
@kang-mk ，收到，非常感谢。
