### ISSUE TITLE
Passwall请问可否添加前置代理功能?

### ISSUE THREAD

**Issue by yyzh** [Lienol/openwrt-package#204]
因我现在有两个节点,A节点是走的CN2线路,但是无法观看netfilx,B节点线路很差劲,但是能看netfilx,所以我就想把A节点作为B节点的前置代理,这样在确保到能看netfilx的同时速度也非常不错.

**Comment by wefuxkgfw** [comment]
我也想要…

**Comment by Lienol** [comment]
没有，没有，没有
