### ISSUE TITLE
passwall 的国外链接  判断经常不准

### ISSUE THREAD

**Issue by genics** [Lienol/openwrt-package#207]
那个谷歌的图标，点了经常是明明通的，但是显示不通。是不是可以考虑换个判断的代码？

**Comment by chnexpats** [comment]
有可能是你本地缓存没有清除导致 DNS 判断失败，或者节点资源质量本来就不够好。这个判断感觉是香港节点才会显示 非常好，其他都是一般般 或者 差 要么就是检测出问题。

**Comment by x91270** [comment]
我今天也出现这个问题，
我直接在路由器上执行

/usr/share/passwall/test.sh test_url 'www.google.com'

发现超时，然后执行 

nslookup www.google.com

发现使用的 DNS 是运营商的， SmartDNS 并没有接管
好像路由器重启之后，路由器本机访问时并没有使用 SmartDNS（猜测）

**Comment by Lienol** [comment]
@x91270 配置不当

**Comment by x91270** [comment]
配置没问题，我又手动重启一下 SmartDNS

**Comment by x91270** [comment]
SmartDNS 设置不要被视频误导 重定向设置 “无”

**Comment by Hueysun** [comment]
那应该怎么解决呢？？

**Comment by han7299** [comment]
13号版本，就是今天的版本 gfw模式下，打不开google
