### ISSUE TITLE
想咨询一下，GFW白名单模式不能用的问题

### ISSUE THREAD

**Issue by xiaoxiang8002** [Lienol/openwrt-package#209]
作者提示如果使用GFW模式无法使用，请尝试清除本机缓存。我想问一下，这个本机缓存意思是路由器的缓存吗，路由器清除缓存就是直接重启路由吗？如果是清除电脑的缓存那没意义呀，因为选了GWF模式，所有的设备都无法翻墙。麻烦知道的专家、大神指点一下！

**Comment by Lienol** [comment]
一直用GFW模式，正常
DNS劫持打钩试试

**Comment by xiaoxiang8002** [comment]
试过了，也不行，选大陆白名单没问题。我用的是Trojan服务器。

**Comment by hslzyd** [comment]
我用了GFW模式，fb、ytb那些都正常，只有谷歌上不去，这又是啥问题呢 O-O

**Comment by x91270** [comment]
我关闭了 IPV6 好像才正常

**Comment by AndyWii** [comment]
iptables -t nat -L
Chain PSW (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere             match-set laniplist dst
REDIRECT   tcp  --  anywhere             localhost            tcp dpt:7054 redir ports 1041
RETURN     all  --  anywhere             anywhere             match-set vpsiplist dst
RETURN     all  --  anywhere             anywhere             match-set whitelist dst
RETURN     tcp  --  anywhere             120.79.16.255        multiport dports 10724
RETURN     tcp  --  anywhere             139.226.186.59       multiport dports 10502
RETURN     tcp  --  anywhere             139.226.186.59       multiport dports 502
RETURN     tcp  --  anywhere             139.226.186.59       multiport dports 503
我想是这个问题 tcp到本地被拒绝了！可是我也不明白怎么处理！
我也是白名单可以上！GFW就上不了！

**Comment by tinnlux** [comment]
OpenWrt SNAPSHOT 主线一直不能用gfw白名单模式。lede源码无问题，但是我现在只用OpenWrt SNAPSHOT

**Comment by ceozero** [comment]
> 作者提示如果使用GFW模式无法使用，请尝试清除本机缓存。我想问一下，这个本机缓存意思是路由器的缓存吗，路由器清除缓存就是直接重启路由吗？如果是清除电脑的缓存那没意义呀，因为选了GWF模式，所有的设备都无法翻墙。麻烦知道的专家、大神指点一下！

今天试了一下。果然是这样的。。GFW模式失败，其他正常。

**Comment by Lienol** [comment]
> @Lienol 大佬，OpenWrt SNAPSHOT 主线passwall与ssr++一直不能用gfw白名单模式。lede源码无问题。还希望有空能修复一下。谢谢！

测试正常

**Comment by Lienol** [comment]
反正我是测试可用的，你们用不了是不是因为有IPV6的原因？

**Comment by ceozero** [comment]
> 反正我是测试可用的，你们用不了是不是因为有IPV6的原因？

在TG下载最新的估计更新以后没有问题了。

**Comment by tianiue** [comment]
我今天编译出来没有GFW名单模式选项，是怎么回事

**Comment by saphhireBlue** [comment]
> > 反正我是测试可用的，你们用不了是不是因为有IPV6的原因？
> 
> 在TG下载最新的固件更新以后没有问题了。

请问你是更新什么固件，是passwall的ipk吗

**Comment by galed-wang** [comment]
openwrt里的GFW模式不能用的问题我也困惑了很久，最后发现是CHROME浏览器打开了安全DNS模式，关闭以后就正常了。
