### ISSUE TITLE
请问一下passwall里面的shadowsocks用TCP代理，google.com访问不了

### ISSUE THREAD

**Issue by funison** [Lienol/openwrt-package#210]
反复更换V2RAY和SS代理，V2RAY能在自带的测试连接页面显示google.com能通，而SS则不能访问google.com,一度以为是SS的完全不能出国，其实只是不能访问google，浏览器显示SSL出了问题，具体是：NET::ERR_CERT_COMMON_NAME_INVALID。
![20200208204538](https://user-images.githubusercontent.com/28219978/74085456-049a2100-4ab4-11ea-8fdd-71c4d64671f1.png)

**Comment by funison** [comment]
补充一下信息：我是用的lean的源码加入了您的passwall大包，2月7日编译的。

**Comment by wefuxkgfw** [comment]
刷新电脑DNS

**Comment by funison** [comment]
刷新过了，没有用，开关openwrt功能，ipconfig/flushdns，开关物理网卡，重启路由，重启VPS，各种试，折腾了2天，就这个问题，暂时无解，不知道怎么分析。需要提交具体信息的话，我来补充。

**Comment by funison** [comment]
应该是DNS设置的问题，IT奶爸2月13日的视频补充说明了smartdns的具体设置，解决了google访问的问题，不是固件的issues。
