### ISSUE TITLE
passwall无法解析一些机场ss订阅的问题

### ISSUE THREAD

**Issue by tanbofan** [Lienol/openwrt-package#212]
我使用的机场是dler，提供ss/ssr/v2ray三种方式的订阅，在passwall中ssr和v2ray订阅一切正常。但ss订阅后节点信息中端口里面会有一些插件的参数无法正常识别，比如我的其中一个节点的端口信息的部分显示“152/?plugin=obfs-local%3Bobfs%3Dtls%3Bobfs-host%3D6bf5644409.wns.windows.com&group=RGxlciBDbG91ZA”。
希望L大能够进行适配，谢谢！

**Comment by tanbofan** [comment]
机场订阅的链接地址我发邮件给你一份方便进行相应的适配。

**Comment by aglent** [comment]
最新版的passwall 好像只是增加了不支持obfs插件的提示? 实际还是不支持这个插件 现在dlercloud大部分节点依旧不能订阅

**Comment by ShanStone** [comment]
> 最新版的passwall 好像只是增加了不支持obfs插件的提示? 实际还是不支持这个插件 现在dlercloud大部分节点依旧不能订阅

obfs插件事实上已经被ss官方弃用了,passwall也没加进来，只加了v2ray-plugin,看作者的意向加不加obfs的支持

**Comment by Lienol** [comment]
更新新版试试
