### ISSUE TITLE
可尝试本人基于大雕源码 跟着README操作即可(这个版本现在无法编译了）能否检查一下

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#214]
可尝试本人基于大雕源码 跟着README操作即可(这个版本现在无法编译了）能否检查一下
去年编译lean-lede都很顺利
今年
git pull
./scripts/feeds update -a && ./scripts/feeds install -a
rm -rf ./tmp && rm -rf .config
make menuconfig
然后编译，整个luci所有appliancation都去掉了，只保留passwall，都无法编译过去，
必须去掉passwall
请教lienol大如何解决？能否百忙之中抽空看看

**Comment by luckyyyyy** [comment]
这个问题，至少给出错误信息。

**Comment by Lienol** [comment]
git fetch --all && git reset --hard origin/dev
git pull
./scripts/feeds clean
./scripts/feeds update -a && ./scripts/feeds install -a
rm -rf ./tmp && rm -rf .config
make menuconfig

**Comment by norikohxb** [comment]
ca8c2bd2/.pkgdir/hostapd-common/. /home/vehxb/lean-lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/vehxb/lean-lede/staging_dir/target-x86_64_musl/root-x86/stamp/.hostapd-common_installed
echo "hostapd-common" >> /home/vehxb/lean-lede/staging_dir/target-x86_64_musl/pkginfo/hostapd.wpad-full-internal.install
make[3]: Leaving directory '/home/vehxb/lean-lede/package/network/services/hostapd'
time: package/network/services/hostapd/wpad-full-internal/compile#1.07#0.81#1.86
make[2]: Leaving directory '/home/vehxb/lean-lede'
package/Makefile:103: recipe for target '/home/vehxb/lean-lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/vehxb/lean-lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/vehxb/lean-lede'
Build failed - please re-run with -j1 to see the real error message
/home/vehxb/lean-lede/include/toplevel.mk:216: recipe for target 'world' failed

**Comment by norikohxb** [comment]
整个 lean-lede目录是重新git pull的
already uptodate

**Comment by norikohxb** [comment]
真神奇用了你的命令就行了，对比你的命令多了这几句？
git fetch --all && git reset --hard origin/dev
./scripts/feeds clean
我感觉是clean的问题
问题是leann-lede目录里面的所有东西都是去年编译的，而且编译成功了，也正在使用。
为什么今年git pull以后还需要多这个clean呢？

其实我在您的oepnwrt系统都没有用这两句命令过
今年也一样编译成功了
git fetch --all && git reset --hard origin/dev
./scripts/feeds clean

**Comment by luckyyyyy** [comment]
git fetch --all && git reset --hard origin/dev
如果你不是维护者 多用这个命令 不要用pull

**Comment by norikohxb** [comment]
git fetch --all && git reset --hard origin/dev 是取代 git pull还是先用git fetch --all && git reset --hard origin/dev
再git pull 能否赐教？

**Comment by kenzok8** [comment]
如果./scripts/feeds clean了，就直接update -a && install -a 了！不用再git pull

**Comment by norikohxb** [comment]
./scripts/feeds clean
./scripts/feeds update -a && ./scripts/feeds install -a
用这两个就可以了对吗？
内核的更新，靠这两个也就可以了吗？
