### ISSUE TITLE
（可尝试本人基于大雕源码）lean-lede编译，编译出来没有passwall

### ISSUE THREAD

**Issue by authon** [Lienol/openwrt-package#215]
大雕，基于lean-lede编译，为什么编译出来没有passwall和其他Lienol/openwrt-package的插件，看了下feeds.conf.default里面是有这个连接的。

然后尝试在自定义文件里面添加
git clone https://github.com/Lienol/openwrt-package package/Lienol后，编译失败，

[使用的自动编译代码](https://github.com/authon/OpenWrt-Actions-Lean/blob/master/.github/workflows/OpenWrt-x86-64-Actions.yml
)   |   [使用的插件自定义文件](https://github.com/authon/OpenWrt-Actions-Lean/blob/master/OpenWrt-x86-64.sh)

错误代码如下

package/Makefile:65: recipe for target 'package/install' failed
make[2]: Leaving directory '/home/runner/work/OpenWrt-Actions-Lean/OpenWrt-Actions-Lean/openwrt'
package/Makefile:104: recipe for target '/home/runner/work/OpenWrt-Actions-Lean/OpenWrt-Actions-Lean/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install' failed
make[1]: Leaving directory '/home/runner/work/OpenWrt-Actions-Lean/OpenWrt-Actions-Lean/openwrt'
make: *** [world] Error 2
/home/runner/work/OpenWrt-Actions-Lean/OpenWrt-Actions-Lean/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
##[error]Process completed with exit code 2.

也尝试过使用lean的源码，添加Lienol/openwrt-package，也是编译失败，按照说明   使用大雕源码务必按此操作执行    里面的连接添加也是报错

**Comment by Lienol** [comment]
- name: 克隆源代码
      env: 
        REPO_URL: https://github.com/Lienol/lean-lede
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

REPO_BRANCH 改成 dev 而不是master
