### ISSUE TITLE
当删除lienol基于大雕源码lede的kernel modules的wireless driver随便一个比如ath10k编译就会出错

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#218]
其实我在去年精简的时候，整个wireless driver都是连根拔起的，因为我的软路由不带wifi模块
也不打算让他支持wifi。所以是彻底没有wifi驱动的
今年2月份之后再编译  lienol基于lean的lede的改进版（集成passwall）
发现无法删除无线网卡驱动。
一旦删除编译就过不去。

package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/vehxb/lean-lede'
package/Makefile:104: recipe for target '/home/vehxb/lean-lede/staging_dir/target-x86_64_musl/stamp/.package_install' failed
make[1]: *** [/home/vehxb/lean-lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/vehxb/lean-lede'
Build failed - please re-run with -j1 to see the real error message
/home/vehxb/lean-lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 1

**Comment by hyird** [comment]
mac80211 wpad wifi驱动 连根拔起就不会了
