### ISSUE TITLE
提几个建议和问题

### ISSUE THREAD

**Issue by hyird** [Lienol/openwrt-package#219]
1：sock5 可以添加 “与TCP节点相同” 的选项
2：节点订阅希望可以 去除无效节点设为 可选开关  刚刚发现把我看流量剩余的节点给去掉了
3：在节点订阅时，再点击删除订阅节点，订阅进程不会停止，希望点击删除订阅节点时同时停止订阅
4：机场订阅用户 可以自己添加haproxy负载均衡节点 并且置顶，机场订阅用户节点配置完全相同，只需要检测一个tcping通的节点的配置即可，在可行性和cpu处理能力上完全不构成难度。
问题：
1：passwall 国内dns设置 “默认” 和 “运营商DNS” 有什么区别么？
2：推测节点检测无超时限制，出现超时节点会一直检测中，望修复

**Comment by Lienol** [comment]
adopted.
