### ISSUE TITLE
V2ray的负载均衡问题

### ISSUE THREAD

**Issue by billy-zheng** [Lienol/openwrt-package#22]
作者你好。
今天在两个vps上分别安装了v2ray 服务器端，并配置了cloudflare cdn。
在passwall插件里，v2ray单个用的时候没问题，一但设置成负载均衡并启用，就上不了外网了。
同样的情况下，ssr设置成负载均衡就没问题。

v2ray有两个和ssr不一样的地方，就是一长串的那个“ID”和 websocket host在两个服务器之间是不一样的，在设置负载均衡的时候只能选一个，不知道是不是因为这个原因导致负载均衡不能用？如果是的话需要怎么解决？

**Comment by Lienol** [comment]
更新试试，所有要负载均衡的V2ray服务器参数配置一定要相同。

**Comment by billy-zheng** [comment]
新版passwall挺好用，几个主题也看起来不错。 辛苦

**Comment by billy-zheng** [comment]
在V2ray+WS+TLS+套CDN的场景下，三个vps的ID、域名、websocket host都不一致，没法做到完全相同。  试着做了下负载均衡，ID、域名、websocket host用其中一个的，跑起来之后能跑通，但是从haproxy里看，数据只走其中一个vps。目前看来是不是暂时无解？

**Comment by Lienol** [comment]
你可以试试直接使用v2ray内置的负载均衡
