### ISSUE TITLE
google play 下载或者更新软件的时候要转圈将近1分钟才开始下载是什么原因？

### ISSUE THREAD

**Issue by phoenix-cn** [Lienol/openwrt-package#221]
开始下载之后速度就很快了，浏览速度也很快。梯子没问题。

**Comment by baygixu** [comment]
我也是这个问题，每次下载前都转很久，真开始下载了速度挺快，Gmail更新也是等很久，然后Facebook lite的app打不开，但Facebook app可以。节点应该没问题，用手机客户端的话，这些问题也没有，能不能请L大帮忙分析分析啊，谢谢

**Comment by Lienol** [comment]
开UDP节点了吗

**Comment by baygixu** [comment]
> 开UDP节点了吗

开了，用的和tcp同一个节点，会不会跟ipv6有啥关系啊？但小白不太懂怎么配置，试过几个组合好像都不行
