### ISSUE TITLE
关于启用pw后使用bt下载的问题

### ISSUE THREAD

**Issue by xiaozizi58** [Lienol/openwrt-package#224]
如何设置不让bt软件走代理流量  大雕原版有一键设置，这个是不是在tcp转发里设置 还是怎么样

**Comment by Lienol** [comment]
高级设置 TCP转发端口 改80,443试试

**Comment by lzlyt** [comment]
我也遇到同样的问题，默认模式是大陆白名单，PT的端口是16881，我不想让这个端口走代理，但是其他端口需要走代理，因为下载机还需要谷歌的smtp发邮件。在访问控制里设置了下载机16881不代理，这样一设置，下载机所有的端口都不走代理了。。。

**Comment by Lienol** [comment]
暂时不支持反向转发端口配置。可以把邮件端口，web端口作为TCP转发端口

**Comment by Lienol** [comment]
更新新版试试
![image](https://user-images.githubusercontent.com/23146169/74505237-93ce8b00-4f31-11ea-8e2c-143a8f075189.png)
在这里填你不想被代理的端口

**Comment by xiaozizi58** [comment]
好的 现在去编译试试

**Comment by greennyreborn** [comment]
> 更新新版试试
> ![image](https://user-images.githubusercontent.com/23146169/74505237-93ce8b00-4f31-11ea-8e2c-143a8f075189.png)
> 在这里填你不想被代理的端口

大佬，不转发的端口会管source 端口么，还是只管目的端口

**Comment by Lienol** [comment]
> > 更新新版试试
> > ![image](https://user-images.githubusercontent.com/23146169/74505237-93ce8b00-4f31-11ea-8e2c-143a8f075189.png)
> > 在这里填你不想被代理的端口
> 
> 大佬，不转发的端口会管source 端口么，还是只管目的端口

只管destination
