### ISSUE TITLE
请问可以在trojan里面可以增加一项sni吗？

### ISSUE THREAD

**Issue by dabster163** [Lienol/openwrt-package#226]
请问可以在trojan里面可以增加一项sni吗？trojan windows配置里面有"remote_addr"，"sni"，我是在config.json里remote_addr填ip,sni填域名。原因是我在vps上同时运行v2ray和trojan，域名都一样，v2ray走了cdn。passwall和shadowsocksr plus+里面的trojan都没有sni选项，在cdn情况下，无法连上vps。

**Comment by dabster163** [comment]
更正一下，今天看回shadowsocksr Plus +里面trojan节点配置是有sni的，就是tls host。就是passwall没有，希望能加上

**Comment by Lienol** [comment]
更了，配置trojan节点时，勾选验证证书 填域名即可
