### ISSUE TITLE
感谢2月12日新版passwall加入了混淆支持，但是还是有问题。

### ISSUE THREAD

**Issue by window227** [Lienol/openwrt-package#229]
先感谢一下作者。
但是支持混淆的SSR配置中，为什么没有aes-256-gcm加密方式呢？
而SS有aes-256-gcm，却还是不支持混淆。

搬瓦工官方的justmysocks ShadowSocks服务旗，现在是这样的模式"obfs=tls, aes-256-gcm, no udp"，还请大大兼容一下，十分感谢。

**Comment by wefuxkgfw** [comment]
@ShanStone

**Comment by ShanStone** [comment]
SSR不支持gcm等加密方式，具体详情看这里https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/34
simple-obfs是可选项，需要在编译时手动选择，或者手动安装ipk包，才会在luci中显示

**Comment by window227** [comment]
ss在编译时也可加入simple-obfs功能吗？我是自己编译的ipk，装上去后ssr里面是有这个功能，但是ss模式里面没有。

**Comment by ShanStone** [comment]
> ss在编译时也可加入simple-obfs功能吗？我是自己编译的ipk，装上去后ssr里面是有这个功能，但是ss模式里面没有。

passwall的可选项里加了obfs插件的选项，源码里也有simple-obfs的源码包，需要就自己编译

**Comment by window227** [comment]
谢谢，已经搞定了。我修改了一下node_config.lua文件，在ss模式里面也加入了obfs插件选项。
