### ISSUE TITLE
openwrt-packages 里的go1.18版本有点高了

### ISSUE THREAD

**Issue by bwb0101** [Lienol/openwrt-package#23]
官方把go升级到1.18，syncthing并没有进行升级，引用的0.24版的quic还没有对go1.18进行适配，会报：syncthing cannot use "quic-go doesn't build on Go 1.18 yet.

syncthing从1.19开始支持go1.18，这是官方插件的问题，这里提下是希望能把go的版本还是还原到1.17

**Comment by bwb0101** [comment]
go1.18刚推出不久，应该有不少插件都还没进行适配

**Comment by Lienol** [comment]
与其动它不如用稳定分支而不是master，master本来就是各种新特征新适配。建议用22.03或21.02分支
