### ISSUE TITLE
关于最新版谷歌检测问题

### ISSUE THREAD

**Issue by Hueysun** [Lienol/openwrt-package#230]
今天更新了最新版3.5.5  谷歌检测只要检测就会提示连接失败  但是已经可以扶墙了   怎么测试都是显示连接失败！

**Comment by x91270** [comment]
https://github.com/Lienol/openwrt-package/issues/207

**Comment by Hueysun** [comment]
@x91270 怎么解决啊？

**Comment by x91270** [comment]
你有没有用 SmartDNS

**Comment by Hueysun** [comment]
我不用那个东西

**Comment by Hueysun** [comment]
@x91270 我没有用那个东西 怎么解决？

**Comment by x91270** [comment]
> @x91270 我没有用那个东西 怎么解决？

IPV6 也关了 哪就不太清楚了

**Comment by Hueysun** [comment]
@x91270 关了  好像好多人 都有这个问题 昨天的版本没这问题

**Comment by bingrenyg** [comment]
今天的版本是有这个问题，同样的设置，没动

**Comment by Lienol** [comment]
本机代理模式改成 GFW试试

**Comment by bingrenyg** [comment]
> 本机代理模式改成 GFW试试

已尝试，还是不行。白名单、全局也试了，不行。

**Comment by Hueysun** [comment]
@Lienol 昨天的版本没问题  今天编译的都这样

**Comment by viagram** [comment]
请叫我雷峰！
`rm -f /etc/resolv.conf
echo 'nameserver 127.0.0.1'>/etc/resolv.conf

`
