### ISSUE TITLE
最新passwall导入vmess链接后，不能运行！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#231]
![TK`OC}{533TL6MFHTQ38$Z6](https://user-images.githubusercontent.com/45259624/74428705-80b9ad80-4e94-11ea-9a59-f6eda0fa8ebb.png)
![image](https://user-images.githubusercontent.com/45259624/74428754-95964100-4e94-11ea-981a-644332c7f488.png)
![image](https://user-images.githubusercontent.com/45259624/74428805-ae065b80-4e94-11ea-8ce3-c7004591d4d8.png)

**Comment by Lienol** [comment]
链接发我测试下？发我邮箱

**Comment by zxlhhyccc** [comment]
> 链接发我测试下？发我邮箱

你邮箱是给我。。。

**Comment by zxlhhyccc** [comment]
> 链接发我测试下？发我邮箱

![image](https://user-images.githubusercontent.com/45259624/74429558-2cafc880-4e96-11ea-9493-0e03349777a3.png)

**Comment by zxlhhyccc** [comment]
> 链接发我测试下？发我邮箱

请问大佬：这个问题不能运行的bug解决了吗？

**Comment by Lienol** [comment]
Fix.
