### ISSUE TITLE
回国模式下域名黑白名单无效

### ISSUE THREAD

**Issue by zhucaidan** [Lienol/openwrt-package#233]
只开启了一个节点，为回国模式
使用的是SSR节点，只开启了TCP开关
在黑白名单选项卡内的域名白名单和域名黑名单填写后也是无效的
DNS改为路由器的IP，开启关闭DNS劫持，清除电脑DNS缓存均无效
但是IP的黑白名单是可以生效的，求修复

**Comment by viagram** [comment]
SSR代理出国，不管是GFW还是大陆白名单，发现同楼上。强烈求修复，谢谢！

**Comment by Lienol** [comment]
更新源碼試下

**Comment by zhucaidan** [comment]
刚刚测试清空DNS后可以了，还有个问题想问下就是域名名单填写一级域名是不是二级域名也会自动算入在内呢？
例如域名白名单添加baidu.com，那是不是在访问pan.baidu.com的时候也是生效的呢？

**Comment by Lienol** [comment]
> 刚刚测试清空DNS后可以了，还有个问题想问下就是域名名单填写一级域名是不是二级域名也会自动算入在内呢？
> 例如域名白名单添加baidu.com，那是不是在访问pan.baidu.com的时候也是生效的呢？

是的
