### ISSUE TITLE
报告passwall解析含ws-tls的vmess链接/订阅的bug

### ISSUE THREAD

**Issue by lymatthew** [Lienol/openwrt-package#234]
passwall在解析含TLS加密、Websocket传输的vmess链接时有bug。目前的解析方式将域名只输入了WebSocket Host一栏，TLS域名被留空，导致TLS链接失败。

多次尝试后，发现只需要手动将域名输入传输层加密下的域名一栏后，即可正确解析使用。请Li大修复，谢谢！

**Comment by jiatianxa** [comment]
是的包括ssr p+也存在这个问题，希望能修复

**Comment by wefuxkgfw** [comment]
楼上有病病？ssrplus+来这里说有用？

**Comment by jiatianxa** [comment]
杠精 ，请学好语文在来杠。懂（包括）和（也)的意思吗？拿个管理员，懂点鸟东西就在得瑟！

**Comment by Lienol** [comment]
> passwall在解析含TLS加密、Websocket传输的vmess链接时有bug。目前的解析方式将域名只输入了WebSocket Host一栏，TLS域名被留空，导致TLS链接失败。
> 
> 多次尝试后，发现只需要手动将域名输入传输层加密下的域名一栏后，即可正确解析使用。请Li大修复，谢谢！

发个链接到我邮箱 让我测试测试

**Comment by jiatianxa** [comment]
![20200214233012](https://user-images.githubusercontent.com/12829666/74544586-59410e80-4f82-11ea-832f-f8c0403882c9.png)
![20200214233101](https://user-images.githubusercontent.com/12829666/74544596-5c3bff00-4f82-11ea-8193-74f3b6ee4c03.png)
![120200214233147](https://user-images.githubusercontent.com/12829666/74544602-5cd49580-4f82-11ea-8547-a0176af53d2a.png)
你好 情况就像图片一样，要手动填！我是不懂，也不知道是那里出的问题。只是反馈而已！请见谅！

**Comment by jiatianxa** [comment]
vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ3dWxhYmluZ193d3cuamlhdGlhbnhhLnh5eiIsCiAgImFkZCI6ICJ3d3cuamlhdGlhbnhhLnh5eiIsCiAgInBvcnQiOiAiNDQzIiwKICAiaWQiOiAiNGNhNGU5ZWMtYzJkYy00ZWM3LTk4NmYtZGU2YzFlYmEzMjM2IiwKICAiYWlkIjogIjY4IiwKICAibmV0IjogIndzIiwKICAidHlwZSI6ICJub25lIiwKICAiaG9zdCI6ICJ3d3cuamlhdGlhbnhhLnh5eiIsCiAgInBhdGgiOiAiL2E4ZWYyN2I3LyIsCiAgInRscyI6ICJ0bHMiCn0K

**Comment by Lienol** [comment]
Fix.
