### ISSUE TITLE
lienol今天用了您给的命令更新 openwrt

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#235]
git fetch --all && git reset --hard origin/dev
git pull
./scripts/feeds clean
./scripts/feeds update -a && ./scripts/feeds install -a
rm -rf ./tmp && rm -rf .config
make menuconfig
=======================
上面命令运行到第二步 git pull
显示如下错误。

Your configuration specifies to merge with the ref 'refs/heads/my-19.07-full'
from the remote, but no such ref was fetched.
vehxb@lean:~/openwrt$ git fetch --all && git reset --hard origin/dev
Fetching origin
fatal: ambiguous argument 'origin/dev': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
vehxb@lean:~/openwrt$ git pull
Your configuration specifies to merge with the ref 'refs/heads/my-19.07-full'
from the remote, but no such ref was fetched.

**Comment by Lienol** [comment]
git fetch --all && git reset --hard origin/dev-19.07

**Comment by norikohxb** [comment]
这个命令是每天起床要编译新的op，都要不断变化吗？
如果不知道这些命令，请问如何保证我三不五时登陆自己的ubuntu可以更新一下源代码然后进行编译？有没有一个固定的万能命令？

**Comment by Lienol** [comment]
没，前几天整理了一下源码。
以后直接
git pull
./scripts/feeds update -a && ./scripts/feeds install -a
就好

**Comment by norikohxb** [comment]
咱们这个passwall集成了trojan的负载均衡了吗，我怎么编译不出来？

**Comment by norikohxb** [comment]
lienol请问你可以赐教如何集成trojan+负载均衡功能吗？

**Comment by Lienol** [comment]
编译时选上haproxy，然后编译后配置

**Comment by norikohxb** [comment]
但是追问一下，为何lean-lede不需要在编译的时候勾luci-app-haproxy-tcp. luci for haproxy and shadowsocks 一样可以负载均衡？

**Comment by norikohxb** [comment]
按照lienol大大的说法，勾选了haproxy编译的时候出错了（nano pi H5）

satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-rtc-sunxi:
kernel (= 4.14.156-1-b92e0de5f7beebcc20b30671b1de70c4)
opkg_install_cmd: Cannot install package kmod-rtc-sunxi.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt'
package/Makefile:108: recipe for target '/home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_install' failed
make[1]: *** [/home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt'
Build failed - please re-run with -j1 to see the real error message
/home/vehxb/friendlywrt-h5/friendlywrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 1
Command exited with non-zero status 2
you take 1:29.92 to build friendlywrt
