### ISSUE TITLE
Lienol大，您好，建议在不转发端口加入常用p2p和bt端口，有些机场会触发审计

### ISSUE THREAD

**Issue by lzx2009vb** [Lienol/openwrt-package#236]
Lienol大，您好，建议在不转发端口加入常用p2p和bt端口，有些机场会触发审计

**Comment by funison** [comment]
我倒是建议把常用端口稍微列一下具体有哪些。

**Comment by fgprodigal** [comment]
我是自己编译了iptable ipp2p模块， 然后在iptable里把p2p流量不走代理

**Comment by ksong008** [comment]
> 我是自己编译了iptable ipp2p模块， 然后在iptable里把p2p流量不走代理

请教，有参考资料吗

**Comment by fgprodigal** [comment]
> > 我是自己编译了iptable ipp2p模块， 然后在iptable里把p2p流量不走代理
> 
> 请教，有参考资料吗

https://github.com/fgprodigal/OpenWrtx86_64-firmware
我的编译的git

**Comment by ksong008** [comment]
> > > 我是自己编译了iptable ipp2p模块， 然后在iptable里把p2p流量不走代理
> > 
> > 
> > 请教，有参考资料吗
> 
> https://github.com/fgprodigal/OpenWrtx86_64-firmware
> 我的编译的git

谢谢，我去看看

**Comment by fgprodigal** [comment]
> > > > 我是自己编译了iptable ipp2p模块， 然后在iptable里把p2p流量不走代理
> > > 
> > > 
> > > 请教，有参考资料吗
> > 
> > 
> > https://github.com/fgprodigal/OpenWrtx86_64-firmware
> > 我的编译的git
> 
> 谢谢，我去看看，流控后，能杜绝pt不会偷跑流量吗

我自己是不用bt的，所以也没测试过
