### ISSUE TITLE
lienol大的openwrt现在gitpull的这个提示正确吗？

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#237]
git pull
Your configuration specifies to merge with the ref 'refs/heads/my-19.07-full'
from the remote, but no such ref was fetched.

**Comment by Lienol** [comment]
重新关联一下远程分支
git fetch --all
git reset --hard origin/dev-19.07
git branch --set-upstream-to=origin/dev-19.07
git pull
再试试

**Comment by lymatthew** [comment]
借宝地问一下，原来用lean-lede的怎么重新关联远程分支呢？

**Comment by norikohxb** [comment]
现在git pull可以了，以后就不用操作上面的命令了对吧，
建议你以后看能否稳定一点，只要让我们小的运行这2个命令就行了
git pull				
./scripts/feeds update -a && ./scripts/feeds install -a
然后就可以
rm -rf ./tmp && rm -rf .config
然后就可以编译了。毕竟这么多命令不是很好懂得。哈哈

**Comment by Lienol** [comment]
> 借宝地问一下，原来用lean-lede的怎么重新关联远程分支呢？

git branch -M dev-lean-lede
git remote remove origin
git remote add -t dev-lean-lede origin https://github.com/Lienol/openwrt
git fetch --all
git reset --hard origin/dev-lean-lede
