### ISSUE TITLE
lienol希望能在百忙中帮我看看，因为喜欢用您的passwall已经把它编译到nano PI h5 里面

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#241]
但是之前编译的都没有带passwall的负载均衡，这次想要编译进去，就会显示如下错误。麻烦你帮我看看

make[3]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt/feeds/luci/collections/luci'
time: package/feeds/luci/luci/compile#0.58#0.31#0.72
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Download failed.
No more mirrors to try - giving up.
Makefile:69: recipe for target '/home/vehxb/friendlywrt-h5/friendlywrt/dl/v2ray-plugin-linux-aarch64-v1.2.0.tar.gz' failed
make[3]: *** [/home/vehxb/friendlywrt-h5/friendlywrt/dl/v2ray-plugin-linux-aarch64-v1.2.0.tar.gz] Error 2
make[3]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt/package/feeds/package/v2ray-plugin'
time: package/feeds/package/v2ray-plugin/compile#0.25#0.19#29.16
package/Makefile:111: recipe for target 'package/feeds/package/v2ray-plugin/compile' failed
make[2]: *** [package/feeds/package/v2ray-plugin/compile] Error 2
make[2]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt'
package/Makefile:107: recipe for target '/home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile' failed
make[1]: *** [/home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt'
Build failed - please re-run with -j1 to see the real error message
/home/vehxb/friendlywrt-h5/friendlywrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 1
Command exited with non-zero status 2
you take 1:43.09 to build friendlywrt

**Comment by hyird** [comment]
明显的 下载dl失败  。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by Lienol** [comment]
更新feeds，我的packages里的v2ray-plugin已经修复并更新到1.3.0了

**Comment by norikohxb** [comment]
因为是在friendlywrt-h5上编译并不是x86平台我是这样做的你看看对不对。
先把你的lean-lede的目录git pull，然后./scripts/feeds update -a && ./scripts/feeds install -a
更新到最新，编译lean-lede可以轻松成功。
然后删除之前的
rm -rf /home/vehxb/friendlywrt-h5/friendlywrt/package/lean
rm -rf /home/vehxb/friendlywrt-h5/friendlywrt/package/feeds/lienol
rm -rf /home/vehxb/friendlywrt-h5/friendlywrt/feeds/lienol
然后将lean-lede的最新的文件都复制到friendlywrt里面
用了如下命令
cp -r  /home/vehxb/lean-lede/package/lean /home/vehxb/friendlywrt-h5/friendlywrt/package/
cp -r /home/vehxb/lean-lede/feeds/lienol /home/vehxb/friendlywrt-h5/friendlywrt/feeds/
复制完毕还不忘记再运行一次
./scripts/feeds update -a && ./scripts/feeds install -a
其实我感觉这句是多余的了，因为复制之前的lean-lede已经给我更新到最新了
，编译的时候平台因为是nano pi H5，所以选了其他平台。

**Comment by norikohxb** [comment]
因为没有那个文件，我又自己复制了一个
cp -r /home/vehxb/lean-lede/dl/v2ray-plugin-linux-amd64-v1.3.0.tar.gz  /home/vehxb/friendlywrt-h5/friendlywrt/dl/
然后再次编译。还是出错。

**Comment by norikohxb** [comment]
WARNING: kmod-rtc-sunxi is not available in the kernel config - generating empty package
mkdir -p /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/stamp

SHELL= flock /home/vehxb/friendlywrt-h5/friendlywrt/tmp/.root-copy.flock -c 'cp -fpR /home/vehxb/friendlywrt-h5/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/packages/.pkgdir/kmod-rtc-sunxi/. /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/'
touch /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/stamp/.kmod-rtc-sunxi_installed
echo "kmod-rtc-sunxi" >> /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/linux.default.install
make[3]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt/package/kernel/linux'
time: package/kernel/linux/compile#4.90#1.01#6.12
make[2]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt'
package/Makefile:107: recipe for target '/home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile' failed
make[1]: *** [/home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt'
Build failed - please re-run with -j1 to see the real error message
/home/vehxb/friendlywrt-h5/friendlywrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 1
Command exited with non-zero status 2
you take 1:12.55 to build friendlywrt
vehxb@lean:~/friendlywrt-h5$

**Comment by norikohxb** [comment]
在这个之前，我如果是编译的时候，只选择passwall，不加负载均衡是可以编译成功并且正常使用，因为这次要追加这个passwall独有的负载均衡，勾选了编译就出错了

**Comment by lonee6** [comment]
> 因为没有那个文件，我又自己复制了一个
> cp -r /home/vehxb/lean-lede/dl/v2ray-plugin-linux-amd64-v1.3.0.tar.gz /home/vehxb/friendlywrt-h5/friendlywrt/dl/
> 然后再次编译。还是出错。

我就想问问你一个ARM的CPU你复制个X64干啥？

**Comment by norikohxb** [comment]
我不想要复制啊，但是刚编译的时候提示出错，我也觉得纳闷我这个是arm的cpu，我不勾选那个passwall的负载均衡是可以编译通过，但是勾选了就编译不通过。这个问题出在哪里呢？请教一下

**Comment by norikohxb** [comment]
> > 因为没有那个文件，我又自己复制了一个
> > cp -r /home/vehxb/lean-lede/dl/v2ray-plugin-linux-amd64-v1.3.0.tar.gz /home/vehxb/friendlywrt-h5/friendlywrt/dl/
> > 然后再次编译。还是出错。
> 
> 我就想问问你一个ARM的CPU你复制个X64干啥？

我删除掉复制的那个文件了，再次编译还是通过不了。
错误依旧，这个错误主要是什么问题？
在x86平台， 在lean-lede， 或者在 openwrt，都可以轻松编译成功
就是在friendlywrt-h5不行

**Comment by norikohxb** [comment]
如果我不勾选 Include simple-obfs (Shadowsocks plugin 进行编译就可以成功编译

copy from: ./friendlywrt_4.14_arm64 to /dev/loop2
 [RAW. 0]:       32 KB | ./friendlywrt_4.14_arm64/sunxi-spl.bin > 100% : done.
 [RAW. 1]:      511 KB | ./friendlywrt_4.14_arm64/u-boot.itb    > 100% : done.
 [MBR. 0]:   102400 KB | ./friendlywrt_4.14_arm64/boot.img      > 100% : done.
 [MBR. 1]:   100764 KB | ./friendlywrt_4.14_arm64/rootfs.img    > 100% : done.
 [MBR. 2]:     5752 KB | ./friendlywrt_4.14_arm64/userdata.img  > 100% : done.
----------------------------------------------------------------
/dev/loop2: msdos partitions 1 2 3
### try to resize2fs: /dev/loop2p3
resize2fs 1.44.1 (24-Mar-2018)
Resizing the filesystem on /dev/loop2p3 to 72282 (4k) blocks.
The filesystem on /dev/loop2p3 is now 72282 (4k) blocks long.

---------------------------------
Friendlywrt_4.14_arm64 is fused successfully.
All done.
---------------------------------
RAW image successfully created (17:38:11).
-rw-r--r-- 1 root root 640000000 Feb 15 17:38 out/FriendlyWrt_20200215_NanoPi-R1S_aarch64_sd.img
Tip: You can compress it to save disk space.
-----------------------------------------
Run the following command for sdcard install:
    sudo dd if=out/FriendlyWrt_20200215_NanoPi-R1S_aarch64_sd.img bs=1M of=/dev/sdX

**Comment by norikohxb** [comment]
Include v2ray-plugin (Shadowsocks plugin) 
Include simple-obfs (Shadowsocks plugin)    
这两个选项在nano pi的编译中（frliendlywrt）就只能选其中一个，两个都选无法通过编译。错误就是上面我罗列出来的

**Comment by norikohxb** [comment]
Include v2ray-plugin (Shadowsocks plugin)这个选项不可以加上去
加上去就无法编译通过

=========================
SHELL= flock /home/vehxb/friendlywrt-h5/friendlywrt/tmp/.root-copy.flock -c 'cp -fpR /home/vehxb/friendlywrt-h5/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/packages/.pkgdir/kmod-nls-base/. /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/'
touch /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/stamp/.kmod-nls-base_installed
echo "kmod-nls-base" >> /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/linux.default.install
mkdir -p /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/stamp

SHELL= flock /home/vehxb/friendlywrt-h5/friendlywrt/tmp/.root-copy.flock -c 'cp -fpR /home/vehxb/friendlywrt-h5/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/packages/.pkgdir/kmod-mmc/. /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/'
touch /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/stamp/.kmod-mmc_installed
echo "kmod-mmc" >> /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/linux.default.install
mkdir -p /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/stamp

SHELL= flock /home/vehxb/friendlywrt-h5/friendlywrt/tmp/.root-copy.flock -c 'cp -fpR /home/vehxb/friendlywrt-h5/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/packages/.pkgdir/kmod-usb-core/. /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/'
touch /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/stamp/.kmod-usb-core_installed
echo "kmod-usb-core" >> /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/linux.default.install
WARNING: kmod-rtc-sunxi is not available in the kernel config - generating empty package
mkdir -p /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/stamp

SHELL= flock /home/vehxb/friendlywrt-h5/friendlywrt/tmp/.root-copy.flock -c 'cp -fpR /home/vehxb/friendlywrt-h5/friendlywrt/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/packages/.pkgdir/kmod-rtc-sunxi/. /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/'
touch /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/root-sunxi/stamp/.kmod-rtc-sunxi_installed
echo "kmod-rtc-sunxi" >> /home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/linux.default.install
make[3]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt/package/kernel/linux'
time: package/kernel/linux/compile#4.90#0.99#6.12
make[2]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt'
package/Makefile:107: recipe for target '/home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile' failed
make[1]: *** [/home/vehxb/friendlywrt-h5/friendlywrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/vehxb/friendlywrt-h5/friendlywrt'
Build failed - please re-run with -j1 to see the real error message
/home/vehxb/friendlywrt-h5/friendlywrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 1
Command exited with non-zero status 2
you take 1:07.18 to build friendlywrt
