### ISSUE TITLE
PW3.57-3.58订阅ssr有问题

### ISSUE THREAD

**Issue by bihcou2** [Lienol/openwrt-package#244]
所有节点都被当无用节点丢弃了，换了下3.56版本仍然正常订阅

**Comment by hyird** [comment]
我真的是不建议 废弃节点

**Comment by zlkent** [comment]
我也遇到了，然后用重置方式恢复正常了
http://192.168.1.1/cgi-bin/luci/admin/vpn/passwall/reset_config

**Comment by Hueysun** [comment]
今天的3.58订阅 有问题  而且订阅过的节点用不了

**Comment by Hueysun** [comment]
@zlkent 重置没有作用

**Comment by Hueysun** [comment]
#246

**Comment by Lienol** [comment]
更新最新源码

**Comment by fanxueke** [comment]
找到/usr/share/passwall/subscribe.lua
第526行开始	
if result.remarks:find("过期时间") or
                                                result.remarks:find("剩余流量") or
						result.remarks:find("QQ群") or
						result.remarks:find("官网") or

根据需要修改或直接删除，因为只要节点含这些词汇就会被丢弃。
实在是因为我的SSR提供商订阅下的列表每一项都含这些词，不得不关掉这个功能，这只是一个暂时的权益之计。
希望lienal能够在luci上添加筛选功能的开关和自定义过滤词汇功能，而不是硬编码在代码中，这样不但没有困扰，还更有用。

**Comment by wefuxkgfw** [comment]
> 
> 
> 找到/usr/share/passwall/subscribe.lua
> 第526行开始
> if result.remarks:find("过期时间") or
> result.remarks:find("剩余流量") or
> result.remarks:find("QQ群") or
> result.remarks:find("官网") or
> 
> 根据需要修改或直接删除，因为只要节点含这些词汇就会被丢弃。
> 实在是因为我的SSR提供商订阅下的列表每一项都含这些词，不得不关掉这个功能，这只是一个暂时的权益之计。
> 希望lienal能够在luci上添加筛选功能的开关和自定义过滤词汇功能，而不是硬编码在代码中，这样不但没有困扰，还更有用。

你的机场真的过分。。每一条都带关键字。。。这种垃圾厂还是退款吧
