### ISSUE TITLE
自从改用ssr++的订阅代码后出现诸多问题(附带临时解决方法）

### ISSUE THREAD

**Issue by tinnlux** [Lienol/openwrt-package#246]
第一个问题是所有v2ray节点在代码里缺少result.tls_allowInsecure = 1，大多数v2ray节点都是要允许不安全连接才可以正常使用的。
第二个问题是直接通过vmess://形式添加v2ray节点是无法直接使用的，因为这样添加进的节点缺少：	 
        option v2ray_protocol 'vmess'
需要手动点击编辑节点后再保存，已添加上这几项，然后才能正常使用。
第三个问题，手动通过vmess：//添加节点，现在不会新增节点，而是覆盖原来添加的节点。
第四个问题，通过订阅添加的节点显示的却是手动添加。
第五个问题，在openwrt主线源码里使用passwall代理模式无法启用gfw名单模式，不是缓存什么的问题，换成lede的源码就可以使用，能否适配下openwrt主线？
望尽快修复。自从改用ssr++的代码后问题越来越严重。当初就是因为ssr++的第一个问题我才弃用转投passwall的，没想到现在又直接用了ssr++的订阅代码。

**Comment by tinnlux** [comment]
我测试把订阅代码改成如下可以解决前两个问题，但是第三个问题因为我不懂编程解决不了，希望大佬能看到，把代码改下：
	elseif szType == 'vmess' then
		local info = jsonParse(content)
		result.type = 'V2ray'
		result.v2ray_protocol = "vmess"
		result.address = info.add
		result.port = info.port
		result.v2ray_transport = info.net
		result.v2ray_VMess_alterId = info.aid
		result.v2ray_VMess_id = info.id
		result.remarks = info.ps
		result.v2ray_mux = 1
		result.v2ray_mux_concurrency = 8
		if info.net == 'ws' then
			result.v2ray_ws_host = info.host
			result.v2ray_ws_path = info.path
		end
		if info.net == 'h2' then
			result.v2ray_h2_host = info.host
			result.v2ray_h2_path = info.path
		end
		if info.net == 'tcp' then
			result.v2ray_tcp_guise = info.type
			result.v2ray_tcp_guise_http_host = info.host
			result.v2ray_tcp_guise_http_path = info.path
		end
		if info.net == 'kcp' then
			result.v2ray_mkcp_guise = info.type
			result.v2ray_mkcp_mtu = 1350
			result.v2ray_mkcp_tti = 50
			result.v2ray_mkcp_uplinkCapacity = 5
			result.v2ray_mkcp_downlinkCapacity = 20
			result.v2ray_mkcp_readBufferSize = 2
			result.v2ray_mkcp_writeBufferSize = 2
		end
		if info.net == 'quic' then
			result.v2ray_quic_guise = info.type
			result.v2ray_quic_key = info.key
			result.v2ray_quic_security = info.securty
		end
		if not info.security then
			result.v2ray_security = "auto"
		end
		if info.tls == "tls" or info.tls == "1" then
			result.v2ray_stream_security = "tls"
			result.tls_serverName = info.host
			result.tls_allowInsecure = 1

**Comment by Hueysun** [comment]
@tinnlux 第二个和第三个问题我都遇到了  我换成了昨天的3.5.7版本 目前正常

**Comment by tinnlux** [comment]
@Hueysun 问题是要修复的，要不然就是源码主线回滚代码，不然这样总不是个办法。

**Comment by tinnlux** [comment]
@Lienol 求大佬有时间的时候看看这几个问题。谢谢！

**Comment by Lienol** [comment]
Fix.

**Comment by tinnlux** [comment]
@Lienol 十分感谢
