### ISSUE TITLE
请问哪个DNS转发优先级高？

### ISSUE THREAD

**Issue by billy-zheng** [Lienol/openwrt-package#25]
作者你好，我在Openwrt上安装了AdGuardHome，端口设成了5335；然后在接口DHCP/DNS里，把DNS转发设置成了127.0.0.1#5335；然而，在passwall插件中的高级设置-DNS配置-DNS转发地址里，我设置成了192.168.2.1：5335，这样是否DNS解析都走AdGuardHome了？

但是在passwall的基本设置里面，还存在一个DNS转发模式的选项。

请问如果要实现AdGuardHome独家代理DNS服务，需要怎么设置才正确？他们之间的优先级如何？谢谢！

**Comment by Lienol** [comment]
将AdGuardHome监听端口设置7913，然后passwall dns转发模式使用本机7913端口即可

**Comment by billy-zheng** [comment]
好的 谢谢


发自我的iPhone

在 2019年11月19日，下午6:11，Lienol <notifications@github.com> 写道：

﻿

将AdGuardHome监听端口设置7913，然后passwall dns转发模式使用本机7913端口即可

**Comment by yunjie-li** [comment]
我是用虚拟机搭建的一个pi-hole, 这个有办法使用自定义的非本机地址吗？
