### ISSUE TITLE
网易云端口转发能回家访问内网，唯独旁路OP不能进

### ISSUE THREAD

**Issue by johnita-biubiu** [Lienol/openwrt-package#253]
手机APN设置顺利回家+出国，唯独打开旁路OP地址后，输入密码后进不去，谢谢！

**Comment by Lienol** [comment]
最好问问原作者

**Comment by johnita-biubiu** [comment]
原作者在哪里可以联系到？谢谢



---原始邮件---
发件人: "Lienol"<notifications@github.com&gt;
发送时间: 2020年2月24日(周一) 晚上9:14
收件人: "Lienol/openwrt-package"<openwrt-package@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"johnita"<187176802@qq.com&gt;;
主题: Re: [Lienol/openwrt-package] 网易云端口转发能回家访问内网，唯独旁路OP不能进 (#253)



最好问问原作者
