### ISSUE TITLE
安装昨天的 X64-1907 passwall 设置不启用了

### ISSUE THREAD

**Issue by hello--world** [Lienol/openwrt-package#258]
重启，在刷都不行，更改了后无法保存。

日志有显示 `Tue Feb 18 12:27:51 2020 daemon.err uhttpd[2364]: sh: write error: Broken pipe
Tue Feb 18 12:27:51 2020 daemon.err uhttpd[2364]: sh: write error: Broken pipe`
不知道是否相关。

固件版本：OpenWrt 19.07-SNAPSHOT / LuCI 18-Lienol (git-20.044.63297-f21c9fa)

![image](https://user-images.githubusercontent.com/9261185/74704600-ed91c680-524b-11ea-9e4c-0bab205af513.png)
![image](https://user-images.githubusercontent.com/9261185/74704612-f8e4f200-524b-11ea-92cf-30745c533a24.png)

**Comment by Lienol** [comment]
恢复出厂设置

**Comment by hello--world** [comment]
根据你提供的`x64-1907`自己编译一下正常了。
