### ISSUE TITLE
回国模式无法观看爱奇艺

### ISSUE THREAD

**Issue by superstaraug** [Lienol/openwrt-package#264]
在2月1日Lean版固件中的Passwall，回国模式无法观看爱奇艺，其他优酷腾讯等都可以。

已自行在IP黑名单中加入一下IP段，依然无法观看。

#爱奇艺自有IP组AS133865
101.227.200.0/24
101.227.200.11/32
101.227.200.28/32
101.227.97.240/32
104.99.206.172
124.192.153.42/32
111.206.13.61
111.206.13.0/24
111.206.0.0/16 
111.206.0.0/18
103.44.56.0/22 
103.44.56.0/23 
103.44.56.0/24 
103.44.57.0/24 
103.44.58.0/23 
103.44.58.0/24 
103.44.59.0/24 
103.98.125.0/24 
103.98.127.0/24 
103.98.248.0/23 
103.98.248.0/24 
103.98.249.0/24 
103.98.250.0/24 
103.98.251.0/24 
103.98.252.0/22 
103.98.252.0/23 
103.98.252.0/24 
103.98.253.0/24 
103.98.254.0/23 
103.98.254.0/24 
103.98.255.0/24 
118.26.32.0/23 
118.26.34.0/23 
118.26.96.0/21 
129.227.142.0/24 
193.118.33.0/24 
43.225.84.0/23 
43.225.87.0/24

**Comment by superstaraug** [comment]
相同节点，在IOS上使用Quantumult开启分流模式加入geo ip cn走proxy可以观看。
在安卓上使用clash的洞主规则Asian TV走节点，也可以正常观看。

**Comment by zhucaidan** [comment]
我是回国模式域名黑白名单那里失效，IP黑白名单倒是可以

**Comment by superstaraug** [comment]
> 
> 
> 我是回国模式域名黑白名单那里失效，IP黑白名单倒是可以

我同时也加了域名黑名单，但是也依然无法观看

# Iqiyi
(^|\.)71\.am$
(^|\.)71edge\.com$
(^|\.)iqiyi\.com$
(^|\.)iqiyipic\.com$
(^|\.)ppsimg\.com$
(^|\.)qiyi\.com$
(^|\.)qiyipic\.com$
(^|\.)qy\.net$
iqiweb.akadns.net
akadns.net
edgekey.net
iqiyi.com.edgekey.net
akamaiedge.net
e4358.a.akamaiedge.net
71.am
71edge.com
www.iqiyi.com
iqiyi.com
iqiyipic.com
ppsimg.com
qiyi.com
qiyipic.com
qy.net
data.video.qiyi.com
cache.m.iqiyi.com
iface2.iqiyi.com
iface.iqiyi.com
iplocation.geo.iqiyi.com
cache.video.iqiyi.com
cache.video.qiyi.com
cache.vip.iqiyi.com
cache.video.qiyi.com
cache.vip.qiyi.com
data.video.iqiyi.com
qiyipic.com 
qiyi.cn
qy.com
jiangbing.cn
iface.iqiyi.com/api/searchIface?*
iface.iqiyi.com/api/ip2area?*
iface2.iqiyi.com/php/xyz/iface/*
iface2.iqiyi.com/php/xyz/entry/galaxy.php?*
iface2.iqiyi.com/php/xyz/entry/nebula.php?*
cache.m.iqiyi.com/jp/tmts/*

**Comment by Lienol** [comment]
全局可以看吗

**Comment by superstaraug** [comment]
> 
> 
> 全局可以看吗

刚才测试后确认了，全局模式可以顺利观看爱奇艺。

**Comment by Lienol** [comment]
尝试DNS地址使用国内DNS，然后确保这个DNS不存在白名单里，并且加入到黑名单里
然后清除DNS缓存试试

**Comment by superstaraug** [comment]
> 
> 
> 尝试DNS地址使用国内DNS，然后确保这个DNS不存在白名单里，并且加入到黑名单里
> 然后清除DNS缓存试试

已经尝试过，但不知方法是否正确。回国模式时，哪一条DNS用于解析回国线路？国内DNS服务器(UDP) 还是 DNS模式 里的？

**Comment by Lienol** [comment]
> > 尝试DNS地址使用国内DNS，然后确保这个DNS不存在白名单里，并且加入到黑名单里
> > 然后清除DNS缓存试试
> 
> 已经尝试过，但不知方法是否正确。回国模式时，哪一条DNS用于解析回国线路？国内DNS服务器(UDP) 还是 DNS模式 里的？

既然是回国，思维逻辑就要倒过来
而且建议你先升级到最新版本再测试

**Comment by superstaraug** [comment]
> 
> 
> > > 尝试DNS地址使用国内DNS，然后确保这个DNS不存在白名单里，并且加入到黑名单里
> > > 然后清除DNS缓存试试
> > 
> > 
> > 已经尝试过，但不知方法是否正确。回国模式时，哪一条DNS用于解析回国线路？国内DNS服务器(UDP) 还是 DNS模式 里的？
> 
> 既然是回国，思维逻辑就要倒过来
> 而且建议你先升级到最新版本再测试

那我的操作是正确的，并且昨天晚上也尝试了将passwall中的两组DNS都改为114，并将其加入黑名单，确认白名单里无114.

现在准备周末将passwall升级至最新版后再做尝试。

**Comment by superstaraug** [comment]
> 
> 
> > > 尝试DNS地址使用国内DNS，然后确保这个DNS不存在白名单里，并且加入到黑名单里
> > > 然后清除DNS缓存试试
> > 
> > 
> > 已经尝试过，但不知方法是否正确。回国模式时，哪一条DNS用于解析回国线路？国内DNS服务器(UDP) 还是 DNS模式 里的？
> 
> 既然是回国，思维逻辑就要倒过来
> 而且建议你先升级到最新版本再测试

已经尝试重新编译固件，加入最新版本PASSWALL，回国模式下，问题依旧
