### ISSUE TITLE
dns2socks包编译错误not match (file: ec82de936ad004cc940502cd2a1bff5b, requested: 6a6d5462113929cb8ba3511a884211cf)

### ISSUE THREAD

**Issue by ChenYuJie1987** [Lienol/openwrt-package#265]
SHELL= flock /home/runner/work/OpenWrt-Rpi/OpenWrt-Rpi/openwrt/tmp/.SourceCode.zip.flock -c '  	/home/runner/work/OpenWrt-Rpi/OpenWrt-Rpi/openwrt/scripts/download.pl "/home/runner/work/OpenWrt-Rpi/OpenWrt-Rpi/openwrt/dl" "SourceCode.zip" "6a6d5462113929cb8ba3511a884211cf" "" "@SF/dns2socks"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.sourceforge.net/dns2socks/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   331  100   331    0     0   1161      0 --:--:-- --:--:-- --:--:--  1157

100 25279  100 25279    0     0  37561      0 --:--:-- --:--:-- --:--:-- 37561
Hash of the downloaded file does not match (file: ec82de936ad004cc940502cd2a1bff5b, requested: 6a6d5462113929cb8ba3511a884211cf) - deleting download.
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://downloads.sourceforge.net/dns2socks/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

**Comment by Lienol** [comment]
更新源码
