### ISSUE TITLE
刚才更新源码重新编译  但是节点延迟全部超时

### ISSUE THREAD

**Issue by Hueysun** [Lienol/openwrt-package#271]
刚才更新源码重新编译  但是节点延迟全部超时
![QQ截图20200220103710](https://user-images.githubusercontent.com/58328962/74895621-1ab9b280-53cd-11ea-86f7-062d14674204.png)

**Comment by Hueysun** [comment]
关了tcp检测延迟正常

**Comment by Lienol** [comment]
更新最新源码
