### ISSUE TITLE
更新 tcping 后， 报错了

### ISSUE THREAD

**Issue by zerofo** [Lienol/openwrt-package#272]
make[3]: Entering directory '/home/runner/work/lede/lede/feeds/packages/libs/libnet-1.2.x'
make[3]: Leaving directory '/home/runner/work/lede/lede/feeds/packages/libs/libnet-1.2.x'
time: package/feeds/packages/libnet-1.2.x/compile#0.10#0.03#0.14
make[3]: Entering directory '/home/runner/work/lede/lede/feeds/lienol/package/tcping'
mkdir -p /home/runner/work/lede/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/runner/work/lede/lede/tmp/.root-copy.flock -c 'cp -fpR /home/runner/work/lede/lede/build_dir/target-x86_64_musl/tcping-0.2/.pkgdir/tcping/. /home/runner/work/lede/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/runner/work/lede/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.tcping_installed
mkdir -p /home/runner/work/lede/lede/bin/targets/x86/64/packages /home/runner/work/lede/lede/build_dir/target-x86_64_musl/tcping-0.2/ipkg-x86_64/tcping/CONTROL /home/runner/work/lede/lede/staging_dir/target-x86_64_musl/pkginfo
install -d -m0755 /home/runner/work/lede/lede/build_dir/target-x86_64_musl/tcping-0.2/ipkg-x86_64/tcping/usr/bin
install -m0755 /home/runner/work/lede/lede/build_dir/target-x86_64_musl/tcping-0.2/tcpping /home/runner/work/lede/lede/build_dir/target-x86_64_musl/tcping-0.2/ipkg-x86_64/tcping/usr/bin/tcping
find /home/runner/work/lede/lede/build_dir/target-x86_64_musl/tcping-0.2/ipkg-x86_64/tcping -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package tcping is missing dependencies for the following libraries:
libnet.so.9
libpcap.so.1
Makefile:39: recipe for target '/home/runner/work/lede/lede/bin/packages/x86_64/lienol/tcping_0.2-1_x86_64.ipk' failed
make[3]: Leaving directory '/home/runner/work/lede/lede/feeds/lienol/package/tcping'
make[3]: *** [/home/runner/work/lede/lede/bin/packages/x86_64/lienol/tcping_0.2-1_x86_64.ipk] Error 1
package/Makefile:107: recipe for target 'package/feeds/lienol/tcping/compile' failed
make[2]: Leaving directory '/home/runner/work/lede/lede'
package/Makefile:103: recipe for target '/home/runner/work/lede/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
time: package/feeds/lienol/tcping/compile#0.16#0.04#0.19
make[1]: Leaving directory '/home/runner/work/lede/lede'
make[2]: *** [package/feeds/lienol/tcping/compile] Error 2
/home/runner/work/lede/lede/include/toplevel.mk:216: recipe for target 'world' failed
make[1]: *** [/home/runner/work/lede/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make: *** [world] Error 2
##[error]Process completed with exit code 2.

**Comment by zerofo** [comment]
@coolsnowwolf

**Comment by Lienol** [comment]
更新最新源码
make defconfig
再编译
