### ISSUE TITLE
建议添加firewall script

### ISSUE THREAD

**Issue by fgprodigal** [Lienol/openwrt-package#276]
防火墙单独重启后passwall的iptables规则会被清空

**Comment by fgprodigal** [comment]
https://github.com/coolsnowwolf/lede/blob/master/package/lean/luci-app-ssr-plus/root/etc/uci-defaults/luci-ssr-plus

像这样的

**Comment by Lienol** [comment]
的确

**Comment by Lienol** [comment]
Thank.

**Comment by fgprodigal** [comment]
> Thank.

这两天在研究Openwrt的软件包开发，像这种luci-app有啥好一点的教程么
