### ISSUE TITLE
昨天新升级后，在最新的LEAN固件里面，启用科学上网就系统崩溃

### ISSUE THREAD

**Issue by czxinshui** [Lienol/openwrt-package#28]
昨天新升级后，在最新的LEAN固件里面，启用【科学上网】系统崩溃，无法进入LEDE后台，无法上网，全崩溃状态

**Comment by Lienol** [comment]
更新最新源码后，不继承passwall配置文件再试试

**Comment by czxinshui** [comment]
> 更新最新原始码后，不继承passwall配置文件再试试

刚才更新的这个修复好这些问题了吗？
