### ISSUE TITLE
2月22日passwall软件包编译错误

### ISSUE THREAD

**Issue by ccrx110** [Lienol/openwrt-package#281]
2月22日passwall软件包编译的时候出现错误

Configuring luci-app-passwall.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for alsa-utils:
 *      libncursesw6.1
 * opkg_install_cmd: Cannot install package alsa-utils.
make[2]: *** [package/install] Error 255
make[2]: Leaving directory `/home/ccrx/lede'
make[1]: *** [/home/ccrx/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory `/home/ccrx/lede'

**Comment by Lienol** [comment]
这个与passwall无关，看你应该是大雕源码编译的吧？
进去build_dir把alsa-utils包删掉再编译应该就好了
不然就make clean

**Comment by ccrx110** [comment]
嗯，好的，make clean 解决了
