### ISSUE TITLE
能否添加brook websocks模式的支持？

### ISSUE THREAD

**Issue by maskedeken** [Lienol/openwrt-package#284]
能否添加brook websocks模式的支持？

**Comment by Lienol** [comment]
brook的ws貌似不支持透明代理，只支持socks，貌似还不支持udp

**Comment by maskedeken** [comment]
> brook的ws貌似不支持透明代理，只支持socks，貌似还不支持udp

不是有ipt2socks嘛

**Comment by Lienol** [comment]
再看看吧
ipt2socks竟然会突然去世

**Comment by Lienol** [comment]
可以的话，提供一下brook websocks服务器给我邮箱

**Comment by maskedeken** [comment]
> 
> 
> 可以的话，提供一下brook websocks服务器给我邮箱

请查收

**Comment by Lienol** [comment]
已更新支持，请测试，如无问题，请close.
