### ISSUE TITLE
Socks5的节点udp能连接，tcp却始终不能

### ISSUE THREAD

**Issue by martin0607** [Lienol/openwrt-package#285]
我是单口软路由openwrt开v2ray并开启socks5共享，端口是2080的。
主路由K2P设置软路由ip和端口为tcp socks5节点并不能运行，udp节点倒是能运行。是我少勾了依赖嘛?普通的V2ray节点是正常的，但是K2P性能不行跑不动。
另外我还在软路由docker部署Adguardhome，主路由的dns指向Adguardhome的，防火墙也注释掉了。
![批注 2020-02-23 215828](https://user-images.githubusercontent.com/32560181/75113302-a3fc0e00-5687-11ea-8d20-0c68e561ca24.jpg)

![批注 2020-02-23 175617](https://user-images.githubusercontent.com/32560181/75113259-2d5f1080-5687-11ea-892c-91a0efe7157e.jpg)

**Comment by Lienol** [comment]
下个版本修复

**Comment by martin0607** [comment]
> 下个版本修复

感谢大佬的贡献！！！

**Comment by Lienol** [comment]
已修复

**Comment by martin0607** [comment]
感谢，正在编译中！
