### ISSUE TITLE
lienol很喜欢用你的openwrt，为何到现在仍然是OpenWrt R20.1.24什么时候可以更新

### ISSUE THREAD

**Issue by norikohxb** [Lienol/openwrt-package#287]
lienol很喜欢用你的openwrt，为何到现在仍然是OpenWrt R20.1.24什么时候可以更新到OpenWrt R20.2.15期待啊

**Comment by Lienol** [comment]
你没更新源码

**Comment by norikohxb** [comment]
大大，难道不是用git pull更新吗

**Comment by norikohxb** [comment]
vehxb@lean:~$ cd openwrt
vehxb@lean:~/openwrt$ git pull
Already up to date.
vehxb@lean:~/openwrt$ 

然后运行./scripts/feeds update -a && ./scripts/feeds install -a
更新feeds，然后编译，
我的git pull显示的是 already up to date
难道还需要重新git clone一次？
你又做了更改？
lean-lede我是重新做了一次git clone，难道这个openwrt也重新再做一次git clone？

**Comment by Lienol** [comment]
那就是最新的了

**Comment by norikohxb** [comment]
能不能更新到openwrt  R20.2.15的版本呢？
