### ISSUE TITLE
最新源代码编译的passwall没有Chinadns-ng

### ISSUE THREAD

**Issue by Kotori-0912** [Lienol/openwrt-package#289]
在24号更新了源代码之后编译出来的Passwall都没有Chinadns-ng选项，chinadns-ng已经显示安装
![123](https://user-images.githubusercontent.com/25550007/75212943-803de280-57c3-11ea-8f35-ac7f4a638947.png)

**Comment by openwrtsan** [comment]
好几天以前的版本就没有这个东西了，软件包里显示是已经安装了的。

**Comment by lonee6** [comment]
wangejibadns

**Comment by Kotori-0912** [comment]
> 好几天以前的版本就没有这个东西了，软件包里显示是已经安装了的。

就是Lienol大佬已经取消掉了？现在只能用pdnsd解析？

**Comment by openwrtsan** [comment]
应该是这样

**Comment by PaulPaulYang** [comment]
你可以试一下下面的方法:
ssh到openwrt中
编辑 /etc/config/passwall
在
config global_other下加上:
        option wangejibadns '1'

**Comment by Kotori-0912** [comment]
> 你可以试一下下面的方法:
> ssh到openwrt中
> 编辑 /etc/config/passwall
> 在
> config global_other下加上:
> option wangejibadns '1'

我在/etc/config/passwall里面加上了option wangejibadns '1'之后看到了Chinadns-ng得选项，感谢大佬
