### ISSUE TITLE
科学上网-服务器列表 排列问题-黑名单问题

### ISSUE THREAD

**Issue by czxinshui** [Lienol/openwrt-package#29]
你好，每天持续关注您的更新，服务器列表的排列问题还是有点乱，订阅地址内的VIP0-VIP2-VIP1 乱排，没有按从小到大排列。当然这个问题有可能是机场的问题！能否在列表规则里面多写一条代码判断等级，然后按等级排列的！
黑名单问题：
请问【域名黑名单】和【路由器本机黑名单】的区别，是不是直接从路由器连接到电脑的就执行【路由器本机黑名单】的功能，用二级路由连接路由器再连接电脑的就没有这个功能？否则他的存在意义是什么？
还有【路由器本机黑名单】是否不能删除，因为我把【路由器本机黑名单】全部复制到【域名黑名单】，再保存，【路由器本机黑】名单里面的内容自动又存在！

**Comment by Lienol** [comment]
路由器本机黑名单只给路由器自己使用，一般用来检测状态，更新软件等。路由器下的设备并不会走该黑名单列表
