### ISSUE TITLE
passwall中的脚本iptables.sh应避免写死br-lan

### ISSUE THREAD

**Issue by maskedeken** [Lienol/openwrt-package#290]
脚本iptables.sh在获取内网ip时直接引用br-lan，但有很多单臂路由只有一个网口，没做成桥接，这里会引起脚本出错。可以通过以下方法获取内网接口：

lan_if=$(uci -p /var/state get network.lan.ifname)

**Comment by Lienol** [comment]
来个PR不美滋滋？

**Comment by wefuxkgfw** [comment]
骚

**Comment by Lienol** [comment]
Fix.
