### ISSUE TITLE
luci-app-passwall所有依赖比如brook和v2ray能不能不要设置为必需组件，占空间又无法完全取消。

### ISSUE THREAD

**Issue by FoxDring** [Lienol/openwrt-package#292]
luci-app-passwall编译时取消brook和v2ray（这两个东西不需要，太占空间，将近10M啊，k2p空间太小），然后删除编译界面Network下的brook和v2ray-plugin，最后编译提示luci-app-passwall缺少这两个依赖。希望大大优化这个问题，这样能节省不少空间啊。

**Comment by Lienol** [comment]
本来编译的时候就可选编译。。。
