### ISSUE TITLE
 can't open '/usr/share/passwall/gfwlist.conf': No such file or directory

### ISSUE THREAD

**Issue by bigbighill** [Lienol/openwrt-package#296]
luci-app-passwall.3.6-2.ipk
ssh:
root@OpenWrt:~# /etc/init.d/passwall restart
cat: can't open '/usr/share/passwall/gfwlist.conf': No such file or directory

bug？
![image](https://user-images.githubusercontent.com/26495337/75452926-0e75bc80-59ae-11ea-8e01-c323c09a824e.png)

**Comment by bigbighill** [comment]
实际在 /usr/share/passwall/rules/gfwlist.conf

**Comment by Lienol** [comment]
The latest version is 3.6.5, you need to update...

**Comment by bigbighill** [comment]
> The latest version is 3.6.5, you need to update...

是我写错了，我用的就是 3.6-5出现的bug

**Comment by Lienol** [comment]
Fix.
