### ISSUE TITLE
passwall 游戏模式消失

### ISSUE THREAD

**Issue by maozheng92** [Lienol/openwrt-package#297]
编译passwall最新版后，发现没有游戏模式了，是取消了吗，还是编译时要选择什么？
![截屏2020-02-27下午11 32 18](https://user-images.githubusercontent.com/13172714/75458814-6e259500-59b9-11ea-8c92-e74275b6c7aa.png)

**Comment by Lienol** [comment]
开UDP节点，用大陆白名单，高级设置 - UDP转发端口 选 所有 即可
