### ISSUE TITLE
TCP_1 状态显示未运行

### ISSUE THREAD

**Issue by billy-zheng** [Lienol/openwrt-package#30]
更新最新的版本后，设置trojan服务器，运行服务器后 基本设置页面 显示**TCP_1状态未运行**，实际上已经能访问外网，且点检查 百度 和 谷歌的两个按钮都显示连接正常。

**Comment by Lienol** [comment]
确定进程已运行？请输入命令
ps -w 查找是否已运行

**Comment by billy-zheng** [comment]
最新的一版 “TCP_1 状态”的显示正常了，但是出现了新的bug， 底下“谷歌连接”的按钮点击了之后，实际外网连接的情况下仍是显示“连接失败”。

**Comment by billy-zheng** [comment]
最新的一版还是存在 外网连接情况按钮 点击后显示 “连接失败”的bug

**Comment by Lienol** [comment]
建议检查是不是和其他插件冲突
