### ISSUE TITLE
这样是不是直白一点

### ISSUE THREAD

**Issue by lloyd18** [Lienol/openwrt-package#300]
下面也免得放一段文字说明了，我觉得可以移动到访问控制分类下
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/75514927-a669b980-5a33-11ea-8dfd-3cb36d6c14b6.jpg)

**Comment by hyird** [comment]
我也是这么觉得 
黑白名单，按理说也可以归类在访问控制里面

**Comment by Lienol** [comment]
已经整在一起了
