### ISSUE TITLE
访问控制如何只允许一台设备使用节点

### ISSUE THREAD

**Issue by zhucaidan** [Lienol/openwrt-package#301]
请问如何只让局域网内的一台电脑使用TCP节点，其他维持本地营运商网络？

也就是默认连接路由器的设备不可以直接使用passwall，
要在访问控制内添加他的mac地址才可以让他使用TCP或者UDP节点。

**Comment by lloyd18** [comment]
![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/75525180-577b4e80-5a4a-11ea-8410-752fea970d90.jpg)

**Comment by zhucaidan** [comment]
666这藏的
