### ISSUE TITLE
请问大陆白名单会自动更新吗？没有看到手动更新的选项。

### ISSUE THREAD

**Issue by BlackTouma** [Lienol/openwrt-package#302]
请问大陆白名单会自动更新吗？没有看到手动更新的选项。今天刚从SSR+转战passwall，发现不能手动更新，所以想请教一下，passwall的规则都是自动更新的吗？

**Comment by 819-dev** [comment]
按钮是没有了，但是lua还有
手动吧

**Comment by BlackTouma** [comment]
> 按钮是没有了，但是lua还有
> 手动吧

请问一下怎么手动更新的指令是什么呢？谢谢

**Comment by lonee6** [comment]
等版本更新吧，源头没更新，你把按钮按烂了也没用。

**Comment by jelly0925** [comment]
新版passwall 没有gfw和国内IP更新了？
