### ISSUE TITLE
新版passwall 没有了GFW和大陆白名单选项了

### ISSUE THREAD

**Issue by jelly0925** [Lienol/openwrt-package#305]
大神，新版passwall 在更新里面没有GFW和大陆白名单选项了，请问后期后恢复这个选项？请问一下这两个参数的更新地址可以让用户输入？谢谢

**Comment by Myoko** [comment]
据说要换接口 先撤了

**Comment by kang-mk** [comment]
不知道什么时候会好，lean大现在用的哪里的列表可以借鉴下
