### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by ntgeralt** [Lienol/openwrt-package#307]
您好，感谢您制作的passwall.
使用了您3月新版本后。感觉挺好。交互上有几点建议稍微提下：

1：打钩启用，变成'运行中'时，点运行状态的谷歌连接，第一次总提示'连接失败'。点多一次又变成'非常快。
2：建议订阅功能放出来更明显位置，减少操作步骤。

2.5：有一定几率更新订阅无法刷出节点（无勾选透过代理）。

3：第一页底部本机代理模式这个，其实非常少见，解释有点谜。

**Comment by Lienol** [comment]
本机代理模式是路由器自己
