### ISSUE TITLE
单网口做旁路由时，在此网口上设置dns，会导致passwall的google测速永远失败

### ISSUE THREAD

**Issue by JeremyPeng** [Lienol/openwrt-package#308]
周日在电报群报过这个issue，现在我已经找到100%重现的方法：
设备只有1个网口，作为旁路由（多功能网关）接入网络。
在此网口设置自定义dns为主路由IP，必然会导致passwall的Google测速失败，但科学上网正常。
<img width="558" alt="image" src="https://user-images.githubusercontent.com/4402112/75782065-4c515700-5d99-11ea-9783-3e602a04a0c4.png">

测速时，系统日志会显示dns被污染，也就是本机的dns解析被污染了...：
<img width="905" alt="image" src="https://user-images.githubusercontent.com/4402112/75782173-76a31480-5d99-11ea-84a0-d2f40567111f.png">

只要在网口配置上删除任何IP，留空，就可以避免这个问题。
但这似乎不符合正常配置规则，留空的话，当passwall不启动，这个网关进无法做任何dns解析，无法正常上网了，Lean版在这里用主路由IP，打开ssr+后是不会影响线路检测。希望Li大能修一下。

**Comment by Lienol** [comment]
应该不会才对的，我也这样用。

**Comment by Lienol** [comment]
![image](https://user-images.githubusercontent.com/23146169/75785625-00a1ac00-5d9f-11ea-905d-fe8148cc7aa5.png)
![image](https://user-images.githubusercontent.com/23146169/75785690-1c0cb700-5d9f-11ea-81e1-b23ae9fec5be.png)
![image](https://user-images.githubusercontent.com/23146169/75785725-262eb580-5d9f-11ea-9457-f576d510a48b.png)

**Comment by JeremyPeng** [comment]
> 应该不会才对的，我也这样用。

好奇怪...我这里确实有这个问题。Li大开了turboacc的dns加速吗？我没有开。
如果我第二天去测，不知是污染的解析失效还是计划任务处理了什么，即使不去掉主路由的IP也是正常的。

重启路由器就会再现。

**Comment by Lienol** [comment]
> > 应该不会才对的，我也这样用。
> 
> 好奇怪...我这里确实有这个问题。Li大开了turboacc的dns加速吗？我没有开。
> 如果我第二天去测，不知是污染的解析失效还是计划任务处理了什么，即使不去掉主路由的IP也是正常的。
> 
> 重启路由器就会再现。

没有开，都是关的

**Comment by JeremyPeng** [comment]
> > > 应该不会才对的，我也这样用。
> > 
> > 
> > 好奇怪...我这里确实有这个问题。Li大开了turboacc的dns加速吗？我没有开。
> > 如果我第二天去测，不知是污染的解析失效还是计划任务处理了什么，即使不去掉主路由的IP也是正常的。
> > 重启路由器就会再现。
> 
> 没有开，都是关的

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/4402112/75786481-59257900-5da0-11ea-81ee-011c49663a6b.png">
我的Wan口规则是默认的，没有删除

**Comment by Lienol** [comment]
![image](https://user-images.githubusercontent.com/23146169/75786633-8d009e80-5da0-11ea-909a-3700f40cf30c.png)
按我这样试试

**Comment by JeremyPeng** [comment]
> ![image](https://user-images.githubusercontent.com/23146169/75786633-8d009e80-5da0-11ea-909a-3700f40cf30c.png)
> 按我这样试试

<img width="889" alt="image" src="https://user-images.githubusercontent.com/4402112/75792590-26cc4980-5da9-11ea-90f4-a3529727ee27.png">


还是一样，应该不是这个问题。
如果我去掉主路由IP做网口dns，或者把本机代理模式设成白名单，才好能正常，好奇怪

**Comment by Lienol** [comment]
更新最新的源码 不保留配置升级 或 恢复出厂设置 试试

**Comment by JeremyPeng** [comment]
用了今天的官方编译版本，还是有这个问题，这个问题只在gwflist下有。
个人猜测：还是污染的问题，在现在命令是应用后重启dnsmasq，这个过程如果加载gwflist还没完成，客户端浏览器还在持续访问，是会被污染的，会被缓存。那些说切换应用设置后，不flushdns就访问不了google，如果一直没有开twitter，去试twitter就应该是可以访问的。如果是白名单，即使没有加载完前也是全走科学线路，所以不会有这个问题。其他服务要在dnsmasq完成加载后启动就应该可以避免了。。。。

**Comment by Lienol** [comment]
我大概知道原因了，更新最新源码试试。
但是奇怪的是我，在我电脑上不会复现

**Comment by JeremyPeng** [comment]
> 我大概知道原因了，更新最新源码试试。
> 但是奇怪的是我，在我电脑上不会复现

已修复，非常感谢。
估计Li大的硬件比较好，加载速度快，哈哈。
Ps，建议开机自动启动延迟设置为3秒～
