### ISSUE TITLE
SS订阅出来的分析师无法自动加载插件obfs

### ISSUE THREAD

**Issue by woni928** [Lienol/openwrt-package#309]
如题
每次订阅出来的节点必须手动修改，才可以正常使用。希望L大能修复自动加载。
<img width="609" alt="1" src="https://user-images.githubusercontent.com/28220733/75844783-12706700-5e12-11ea-85d6-acf03a278015.png">

**Comment by Lienol** [comment]
发个订阅到我邮箱测试下？
