### ISSUE TITLE
科学上网插件，IP黑名单设置无效

### ISSUE THREAD

**Issue by hr1217** [Lienol/openwrt-package#31]
代理模式为GFW模式，IP黑名单添加Telegram IP段， Telegram无法连接网络

**Comment by Lienol** [comment]
默认黑名单已加入TG IP段，本人亲测没问题。

**Comment by hr1217** [comment]
> 默认黑名单已加入TG IP段，本人亲测没问题。

使用的是默认设置，只添加了V2ray服务器！谷歌、油管网站都能正常打开，就是电报不行！很喜欢passwall，是我哪里设置的出问题了吗

**Comment by hr1217** [comment]
> 默认黑名单已加入TG IP段，本人亲测没问题。

![QQ截图20191116235651](https://user-images.githubusercontent.com/57555223/68995817-dfd74880-08cc-11ea-8bc6-3e18e376c22c.png)
![QQ截图20191116235714](https://user-images.githubusercontent.com/57555223/68995818-e06fdf00-08cc-11ea-9e6c-da016856e75a.png)

这是IP黑名单列表
91.108.4.0/22
91.108.8.0/22
91.108.12.0/22
91.108.20.0/22
91.108.36.0/23
91.108.38.0/23
91.108.56.0/22
149.154.160.0/20
149.154.164.0/22
149.154.172.0/22
67.198.55.0/24
74.125.0.0/16
109.239.140.0/24
172.217.0.0/16
173.194.0.0/16
216.58.200.0/24
216.58.220.0/24

**Comment by Lienol** [comment]
高级设置 - 接管局域网DNS解析，勾上再试试

**Comment by Lienol** [comment]
修复了，是自己疏忽漏了一句代码
