### ISSUE TITLE
PASSWALL里访问控制的建议

### ISSUE THREAD

**Issue by 7ordy** [Lienol/openwrt-package#312]
感谢L大的固件。
PASSWALL的访问控制能否添加一个“默认主机使用的代理模式”？我家里包括IOT设备在内差不多有40多个设备，但我只需要PC、PS4、手机等设备FQ，其他设备不需要FQ。而通过访问控制里我需要把所有的不需要FQ设备添加进去，感觉工作量有点大。如果有默认主机不通过FQ的模式，我只需要把要FQ的添加进去就行了。
再次感谢

**Comment by Lienol** [comment]
默认代理模式 在首页

**Comment by 7ordy** [comment]
> 默认代理模式 在首页

哦对，感谢，脑子秀逗了
