### ISSUE TITLE
passwall突然速度仅有0.几M，用其他SSR工具正常100+

### ISSUE THREAD

**Issue by istevenyang** [Lienol/openwrt-package#313]
使用访问控制，尝试恢复passwall配置，重启路由器，无果。版本3.6-12

**Comment by Lienol** [comment]
配置？
节点类型？
多进程？
UDP不转发端口 80,443？
TCP转发端口？
UDP转发端口？

**Comment by istevenyang** [comment]
ssr节点，其他默认。
添加了tcp1，tcp2，使用访问控制分流。没有udp设置

**Comment by Lienol** [comment]
注意一下 TCP UDP转发端口，如果不在意可能会走PT流量，建议设置所有

**Comment by istevenyang** [comment]
这个在哪里设置呢？我都是默认设置，代理模式选择不代理，在访问控制里面对不同Mac地址做了代理
