### ISSUE TITLE
Li大能否考虑加入udp2raw？

### ISSUE THREAD

**Issue by trumen8510** [Lienol/openwrt-package#314]
Li大能否考虑加入udp2raw？结合固件原有的kcptun，起码能救一些线路差的，比如pr。

**Comment by SoPudge** [comment]
这个必须顶

**Comment by Lienol** [comment]
加入不是問題，我缺的是 udp2raw節點 and Time

**Comment by trumen8510** [comment]
我的pr小鸡可以贡献出来，kcptun+udp2raw已经搭好了，现在其实是自己编译的也能用，就是感觉能整合到passwall里面的话，就更完美了

**Comment by Lienol** [comment]
暫時沒空做，你可以先把節點發我郵箱，週末我再找時間做做看
