### ISSUE TITLE
向L大提个建议  关于V2ray分流节点

### ISSUE THREAD

**Issue by JustOnePei** [Lienol/openwrt-package#315]
目前v2ray可设定的分流功能非常的好
如果分流节点里能选择均衡负载的节点就非常好了

比如 youtube  我用 TCP1
         netflix   我用  TC22
        默认       我能选用均衡负载节点

感谢L大，给大家提供这么好的插件及固件！

**Comment by Lienol** [comment]
意思是说想 
无限套娃？
还真的是可以无限套

**Comment by Lienol** [comment]
![image](https://user-images.githubusercontent.com/23146169/76010063-38e6ed00-5f4d-11ea-8c04-a930319114a6.png)
最新源码已经可以使用任何协议分流了，不过建议编译勾选项全选才可以
