### ISSUE TITLE
L大佬，经测试最新版本的passwall隔段时间虽然显示科学正常运行，但是ping谷歌失败，网络不通！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#316]

**Comment by wefuxkgfw** [comment]
看日志，等启动完成。你太急了。

**Comment by zxlhhyccc** [comment]
> 看日志，等启动完成。你太急了。

不是启动的问题，是启动后能正常科学，过段时间就掉，然后需要关闭再重新开启才正常！！！

**Comment by Lienol** [comment]
不能ping的，icmp是不会代理的

**Comment by Kisoul** [comment]
我也发现了同样的问题，版本号3.6.9

**Comment by cnclg** [comment]
用tcping ,ping 肯定不行的

**Comment by Kisoul** [comment]
> 用tcping ,ping 肯定不行的

关键如果是单单的ping不通没问题，主要是直接无法访问google了。一定要从新保存并应用一次

**Comment by kuailxxh** [comment]
实际上我用的SSR+也是这样，时不时谷歌就上不了，然后过一会儿就好了。不知道时不时线路问题

**Comment by cnclg** [comment]
> > 用tcping ,ping 肯定不行的
> 
> 关键如果是单单的ping不通没问题，主要是直接无法访问google了。一定要从新保存并应用一次。之前的确遇到过你说的这种问题，我用的trojan，现在基本上没遇到过你说的问题了。

**Comment by BarneyTTGumble** [comment]
遇到相同问题，版本 OpenWrt SNAPSHOT / LuCI Master-Lienol git-20.064.57175-8859fac

**Comment by BarneyTTGumble** [comment]
隔段时间谷歌就连不上，youtube没问题

**Comment by luckyyyyy** [comment]
在节点不稳定的时候我遇到过很多次 
关于google不能访问 YouTube可以访问多半是缓存问题

还有用v2的注意 如果机场设置了人数限制 会被强行定向到404错误 SSL错误之类的问题
