### ISSUE TITLE
新主题白屏

### ISSUE THREAD

**Issue by Kalansas** [Lienol/openwrt-package#318]
如题，我编译过从github上找到的主题，也从路由软件包界面下载过主题，但无论主题文件从哪儿来，只要应用了新主题，页面就白屏了，啥都没有，刷新也不管用，但网络和已开启的服务均正常，最后只能按reset键恢复出厂，我编译过你基于大雕的源码和基于官方19.07的源码，这个问题均有出现，初步推断应当是新主题里的某些代码不兼容导致luci界面崩溃，但不知有什么解决办法，大神可以帮帮我吗，出问题的主题有luci-theme-rosy   luci-theme-argon（新版-github上的） luci-theme-material（新版-软件包界面下载的） luci-theme-bootstrap（新版-软件包界面下载的）

**Comment by Lienol** [comment]
相互肯定是不兼容的
luci版本都不一样
