### ISSUE TITLE
passwall升级规则覆盖问题。

### ISSUE THREAD

**Issue by hyird** [Lienol/openwrt-package#319]
刚刚才得知，passwall支持在线升级了 利用获取在github release的ipk来实现，在升级中会出现这个
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/passwall is different from the conffile in the new package. The new conffile will be placed at /etc/config/passwall-opkg.

 * resolve_conffiles: Existing conffile /usr/share/passwall/rules/blacklist_host is different from the conffile in the new package. The new conffile will be placed at /usr/share/passwall/rules/blacklist_host-opkg.

在第一个   resolve_conffiles为了避免旧的配置被覆盖掉将新的重命名很正常，没问题
但是第二个 resolve_conffiles  规则更新了 blacklist_host 也依旧是旧的这点不可取，我觉得应该直接新的覆盖旧的

**Comment by Lienol** [comment]
因为之前有人希望 更新可以保留自定义的黑白名单。。。

**Comment by hyird** [comment]
................
passwall luci的ipk可以参考 https://github.com/pymumu/smartdns/tree/master/package/luci-compat
整个luci可以直接用sh打包，出来贼快 
可以用action生成 只需要几分钟吧
