### ISSUE TITLE
移植编译报错!

### ISSUE THREAD

**Issue by waynesg** [Lienol/openwrt-package#32]
错误信息如下:
collect2: error: ld returned 1 exit status
Makefile:23: recipe for target 'ipt2socks' failed
make[4]: *** [ipt2socks] Error 1
make[4]: Leaving directory '/home/waynesg/lede/build_dir/target-x86_64_musl/ipt2socks/ipt2socks-1.0.1-b9bd7d888f2f95a6d7306030c8a5e252732dc451'
Makefile:48: recipe for target '/home/waynesg/lede/build_dir/target-x86_64_musl/ipt2socks/ipt2socks-1.0.1-b9bd7d888f2f95a6d7306030c8a5e252732dc451/.built' failed
make[3]: *** [/home/waynesg/lede/build_dir/target-x86_64_musl/ipt2socks/ipt2socks-1.0.1-b9bd7d888f2f95a6d7306030c8a5e252732dc451/.built] Error 2
make[3]: Leaving directory '/home/waynesg/lede/package/lean/ipt2socks'
time: package/lean/ipt2socks/compile#0.10#0.02#0.14
package/Makefile:107: recipe for target 'package/lean/ipt2socks/compile' failed
make[2]: *** [package/lean/ipt2socks/compile] Error 2
make[2]: Leaving directory '/home/waynesg/lede'
package/Makefile:103: recipe for target '/home/waynesg/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/waynesg/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/waynesg/lede'
/home/waynesg/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

请教下应该如何解决.

**Comment by Lienol** [comment]
更新最新libuv包

**Comment by waynesg** [comment]
> 更新最新libuv包

感谢回复,不过又出现了新的错误,再次请教

make[5]: Entering directory '/home/waynesg/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.82'
  CALL    scripts/checksyscalls.sh
  DESCEND  objtool
make[9]: *** No rule to make target '/usr/include/x86_64-linux-gnu/bits/sigset.h', needed by '/home/waynesg/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.82/tools/objtool/fixdep.o'.  Stop.
Makefile:43: recipe for target '/home/waynesg/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.82/tools/objtool/fixdep-in.o' failed
make[8]: *** [/home/waynesg/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.82/tools/objtool/fixdep-in.o] Error 2
/home/waynesg/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.82/tools/build/Makefile.include:4: recipe for target 'fixdep' failed
make[7]: *** [fixdep] Error 2
Makefile:63: recipe for target 'objtool' failed
make[6]: *** [objtool] Error 2
Makefile:1643: recipe for target 'tools/objtool' failed
make[5]: *** [tools/objtool] Error 2
make[5]: Leaving directory '/home/waynesg/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.82'
Makefile:29: recipe for target '/home/waynesg/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.82/.modules' failed
make[4]: *** [/home/waynesg/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-4.19.82/.modules] Error 2
make[4]: Leaving directory '/home/waynesg/lede/target/linux/x86'
Makefile:13: recipe for target 'compile' failed
make[3]: *** [compile] Error 2
make[3]: Leaving directory '/home/waynesg/lede/target/linux'
time: target/linux/compile#1.00#0.40#1.42
target/Makefile:23: recipe for target 'target/linux/compile' failed
make[2]: *** [target/linux/compile] Error 2
make[2]: Leaving directory '/home/waynesg/lede'
target/Makefile:18: recipe for target '/home/waynesg/lede/staging_dir/target-x86_64_musl/stamp/.target_compile' failed
make[1]: *** [/home/waynesg/lede/staging_dir/target-x86_64_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/waynesg/lede'
/home/waynesg/lede/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by Lienol** [comment]
make clean再试试

**Comment by dengchan0416** [comment]
请问解决了吗？我的错误也是一样

**Comment by Lienol** [comment]
#54

**Comment by 1272568459** [comment]
更新libuv包命令是啥？
