### ISSUE TITLE
在处理v2ray分流时，如果SS节点中设有ota=true值时将会失败

### ISSUE THREAD

**Issue by hcwang** [Lienol/openwrt-package#320]
在openwrt-package/lienol/luci-app-passwall/luasrc/model/cbi/passwall/api/gen_v2ray_shunt.lua的文件第123行，直接将ota设为了nil，此时会导致如果在分流规则时选择了设有ota=true的ss节点时，将会无法使用。

**Comment by Lienol** [comment]
目前其实并没有直接使用V2ray内置SS，而是非V2ray节点转socks再进行分流

**Comment by Lienol** [comment]
V2ray这个功能可以实现 无限套娃 ..

**Comment by hcwang** [comment]
收到，谢谢。
