### ISSUE TITLE
3.6-13新加的手动更新功能不能使用

### ISSUE THREAD

**Issue by Gzxhwq** [Lienol/openwrt-package#321]
如题，这个功能点击没有反应，不知道如何排错。

**Comment by Lienol** [comment]
需要路由器自己能上github
還有 圖片都沒一個 很難分析

**Comment by Gzxhwq** [comment]
下面3个是能用的，新加那个不能用，本机已经设定成全局了
![passwall](https://user-images.githubusercontent.com/8738520/76078695-24066a00-5fde-11ea-8b4c-4c96bb3b9ab8.png)

**Comment by Lienol** [comment]
用的哪个分支编译的？
rm -rf /tmp/luci-* 了没

**Comment by Gzxhwq** [comment]
rm -rf /tmp/luci-* 就可以了，
只 rm /tmp/luci-indexcache 不行，
谢谢了！
