### ISSUE TITLE
建议 规则更新如果没有新版本就结束，不重启插件

### ISSUE THREAD

**Issue by JeremyPeng** [Lienol/openwrt-package#324]
建议 规则更新如果没有下载新版本更新就结束，不重启插件。
现在是只要使用了检查，不论有没有更新规则，都会完全重起一次插件

**Comment by Lienol** [comment]
![image](https://user-images.githubusercontent.com/23146169/76098767-0bf61100-6005-11ea-9701-3d986ff082f7.png)
不会啊

**Comment by JeremyPeng** [comment]
> ![image](https://user-images.githubusercontent.com/23146169/76098767-0bf61100-6005-11ea-9701-3d986ff082f7.png)
> 不会啊

<img width="532" alt="image" src="https://user-images.githubusercontent.com/4402112/76099654-6643a180-6006-11ea-90e2-b924be881e43.png">
今天actions的编译版本...

**Comment by viagram** [comment]
刚拉最新源码编译的斐讯k3固件，也会重启。如下图：
![IMG_20200307_204003](https://user-images.githubusercontent.com/18513535/76143634-060b3900-60b4-11ea-9908-f8b90148e358.jpg)

**Comment by ShanStone** [comment]
不止更新规则，订阅更新也会多一次重启，看起来像是在lua脚本执行完后又重启了一次
![image](https://user-images.githubusercontent.com/31815718/76158613-7cf70f00-6152-11ea-8fa1-fb1b89fdd71a.png)

**Comment by Lienol** [comment]
更新源码试试
@ShanStone 帮忙测试下

**Comment by ShanStone** [comment]
> 更新源码试试
> @ShanStone 帮忙测试下

OK，这边测试暂时没问题了

**Comment by JeremyPeng** [comment]
> 更新源码试试
> @ShanStone 帮忙测试下

我这里也没有问题了
