### ISSUE TITLE
passwall 代理开启udp后无法游戏

### ISSUE THREAD

**Issue by frankniubi** [Lienol/openwrt-package#325]
![IMG_20200308_011411](https://user-images.githubusercontent.com/42706849/76147847-5cd83900-60db-11ea-874c-ee25379361a2.jpg)
如图，单击sstap测试可连接游戏，放入openwrt便不可进入。

**Comment by maogoudaxia** [comment]
额，我还以为只是我的插件有问题，在我用ssr plus的 ssr节点可以正常使用UDP，passwall的UDP好像都出了问题。另外，你使用的是什么类型的节点，如果是r2way或者trojan，我经过几天的测试都是不可用于游戏加速的（刚开始的十多分钟可以正常游戏，但十多分钟后就UDP断流，不管是ssrplus插件还是passwall插件），这不属于插件的问题，我另外有一个issue，是想看看作者能不能解决这个问题。。。

**Comment by frankniubi** [comment]
> 额，我还以为只是我的插件有问题，在我用ssr plus的 ssr节点可以正常使用UDP，passwall的UDP好像都出了问题。另外，你使用的是什么类型的节点，如果是r2way或者trojan，我经过几天的测试都是不可用于游戏加速的（刚开始的十多分钟可以正常游戏，但十多分钟后就UDP断流，不管是ssrplus插件还是passwall插件），这不属于插件的问题，我另外有一个issue，是想看看作者能不能解决这个问题。。。

我用SSR但是也是无法链接到任意服务器。我现在只好用Netch了。

**Comment by wzd1016** [comment]
3.3的版本没这个问题，3.6号的大更新有这个问题

**Comment by frankniubi** [comment]
> 3.3的版本没这个问题，3.6号的大更新有这个问题

请问3.3大概是在什么时候发布的呢

**Comment by wzd1016** [comment]
> > 3.3的版本没这个问题，3.6号的大更新有这个问题
> 
> 请问3.3大概是在什么时候发布的呢

我倒是有，好像那个Openwrt群里昨天有人发了，你找下，好像dns国内国外一分开就出事，过去没这事，我试了最新的还是这样，连激进版都刷了，Li也回复我的帖子说我装了啥插件，我真的啥也没装，3.3号的版本一下子就nat开放，这个nat一直是限制

**Comment by Lienol** [comment]
固件版本，固件分支

**Comment by frankniubi** [comment]
> 固件版本，固件分支

0308版 你那里编译的

**Comment by wzd1016** [comment]
> 固件版本，固件分支

我测试了3.6 3.7 3.8 就是大更后的64位稳定版 以及昨晚又试了下3.8号的激进版 3.9我还没刷没测 一会没准还测试下，我只有xbox没有ps4 听说ps4行 我之前用的3.3的64位稳定版 那个版本dns很简单 国内都没办法改 那个版本xbox用大陆白名单 udp tcp所有nat能开放 dns模式用的pdnsd 或者dnssocks5 其实过去版本也有点问题就是一开始打开游戏机nat偶尔开放 但是只要一换dns模式 就开放了 连节点都不用换 但起码能用 3.6-3.8号的固件 索性nat很难开放了

**Comment by wzd1016** [comment]
> > 固件版本，固件分支
> 
> 0308版 你那里编译的

我是小白我不会编译，都是捡现成的，群里的固件直接虚拟机pve走起

**Comment by frankniubi** [comment]
![image](https://user-images.githubusercontent.com/42706849/76205533-62e22d00-6235-11ea-8d64-d8e2ed8e1943.png)
三月三日版固件一切正常

**Comment by Lienol** [comment]
玄学BUG无法解决
我自己测试倒是正常的
