### ISSUE TITLE
ipv6节点无法显示

### ISSUE THREAD

**Issue by djp518** [Lienol/openwrt-package#330]
在【节点列表】中添加了ipv6地址的节点后（无论是ss/ssr/trojan）均无法在【基本设置】-【TCP节点】中显示，只有ipv4地址的节点可以显示

openwrt版本 ccacbb4
passwall版本 3.6-20

**Comment by Lienol** [comment]
没有ipv6环境，所以暂时不会完美兼容ipv6

**Comment by djp518** [comment]
但是其实是可以用的，在【节点列表】直接【使用】就可以，只是在【基本设置】中无法显示，就是开关很不方便
