### ISSUE TITLE
基于最新官方源码编译后发现两个问题

### ISSUE THREAD

**Issue by parorisim** [Lienol/openwrt-package#333]
- 点击“通过链接添加节点后”，复制链接点击“添加”，PASSWALL没有反应，只能手动添加
- 点击“手动订阅”后跳转到了日志页面但没有输出任何日志，节点也没有更新

这两个功能在 19.07 分支下可以正常使用，所以我在想会不会是我少添加了什么依赖？

**Comment by ShanStone** [comment]
如果你使用的是Luci19，请编译时选上"luci","luci-compat","luci-lib-ipkg"后编译

**Comment by parorisim** [comment]
@ShanStone 我是勾选上的呢

**Comment by lidyu2019** [comment]
19.07.2和18.06.8都无法订阅

**Comment by parorisim** [comment]
@lidyu2019 可以讲解下是什么原因导致的吗？这样我自己修改的话会有些思路～

**Comment by ShanStone** [comment]
测试过了，官方默认没有勾选libuci-lua，你勾选上编译就可以正常使用了，待会加上依赖
