### ISSUE TITLE
add shadowsocks-libev in luci-app-passwall

### ISSUE THREAD

**Issue by serverlinuxit** [Lienol/openwrt-package#334]
can you add the example of shadowsocks-libev in the luci-app-passwall makefile, I see that there is no shadowsocks-libev makefile

**Comment by ShanStone** [comment]
It's already provided by the Openwrt source code,you can find the makefile after update the feeds.
https://github.com/openwrt/packages/tree/master/net/shadowsocks-libev

**Comment by serverlinuxit** [comment]
Thanks
