### ISSUE TITLE
我的N1是arm64 aarch64框架的，无法编译tro和openssl，请问有办法解决吗

### ISSUE THREAD

**Issue by feifan1113** [Lienol/openwrt-package#34]

**Comment by Lienol** [comment]
请编译使用-j 1，然后提供编译错误信息

**Comment by feifan1113** [comment]
> 请编译使用-j 1 V=s，然后提供编译错误信息

可能要晚上了，我删了虚拟机重新编译中，多次重复编译，虚拟机占用空间太大所以重新编

**Comment by feifan1113** [comment]
> 请编译使用-j 1 V=s，然后提供编译错误信息

![快照2](https://user-images.githubusercontent.com/57245399/69016542-29fa2000-09da-11ea-917c-76fe8be6f0bf.png)
大佬你看看 就是这个错误信息

**Comment by Lienol** [comment]
> > 请编译使用-j 1 V=s，然后提供编译错误信息
> 
> ![快照2](https://user-images.githubusercontent.com/57245399/69016542-29fa2000-09da-11ea-917c-76fe8be6f0bf.png)
> 大佬你看看 就是这个错误信息

OpenSSL 1.1.1d编译不过去吧，本人暂时无解
