### ISSUE TITLE
passwall的谷歌连接检测绝大多数是失败

### ISSUE THREAD

**Issue by GimmGoo** [Lienol/openwrt-package#341]
passwall就放了3个节点，全是trojan的，测试过ping值都很低的，百分百能使用，点击passwall谷歌连接那里检测，却总是提示失败（90%概率都是显示连接失败），但是却能够上网。无论什么时段，无论点击多少次都是这样。

**Comment by GimmGoo** [comment]
节点那里无论勾不勾选tcp ping方式，以及无论是大陆白名单还是GFW都有这情况。都是能上谷歌，但是谷歌连接检测绝大多数是失败，并非节点不能ping，多个站长ping工具都是一篇绿色的低延迟。
望开发者修复下。passwall版本【3.6-20】

**Comment by Lienol** [comment]
更新最新源码，若再复现再反馈问题

**Comment by kang-mk** [comment]
我这边倒是没有检测失败，但是检测出来显示都是一般般或者很慢，但实际节点直接是很好的，延迟只有50+  可以跑满百兆带宽无压力，自建台湾谷歌云v2协议，原来的版本都是显示很快或者非常快，后来这十几天的不知道是不是修改了判断逻辑，昨晚最新编译的也是这样
