### ISSUE TITLE
app.sh中RESOLVFILE有误

### ISSUE THREAD

**Issue by iberryful** [Lienol/openwrt-package#342]
在某些系统中，RESOLVFILE应为/tmp/resolv.conf.auto

影响： 读不到系统默认dns，导致白名单域名无法解析

**Comment by iberryful** [comment]
建议不指定白名单dns_server,只添加ipset即可，留给默认dns去解析

**Comment by ShanStone** [comment]
有做过兼容的啊，你看200行

**Comment by iberryful** [comment]
找到原因了，我没有给LAN设置DNS，在dnsmasq里配置了转发127.0.0.1#5300，所以/tmp/resolv.conf.auto里只有127.0.0.1,而这个ip在获取CHINA_DNS_1的时候被过滤掉了
这种情况下，白名单里是这样的：
server=/.apple.com/
server=/.apple.com/114.114.114.114
ipset=/.apple.com/whitelist

**Comment by ShanStone** [comment]
passwall里不是有国内DNS服务器设置吗

**Comment by Lienol** [comment]
Fix.
