### ISSUE TITLE
希望处理一下passwall与IPv6的问题

### ISSUE THREAD

**Issue by viagram** [Lienol/openwrt-package#347]
如题，现在的宽带"几乎"没有公网IPv4，同时也需要访问一些v6的网站，希望大佬抽时间处理一下。
不要直接禁止v6的dns解析，谢谢。

**Comment by Lienol** [comment]
没有测试环境

**Comment by iberryful** [comment]
> 如题，现在的宽带"几乎"没有公网IPv4，同时也需要访问一些v6的网站，希望大佬抽时间处理一下。
> 不要直接禁止v6的dns解析，谢谢。

建议你直接关掉IPV6，对于双栈网站，系统会优先走IPv6，有时会带来一些问题，比如访问速度慢，代理没有应用上等等

**Comment by wefuxkgfw** [comment]
> 
> 
> 如题，现在的宽带"几乎"没有公网IPv4，同时也需要访问一些v6的网站，希望大佬抽时间处理一下。
> 不要直接禁止v6的dns解析，谢谢。

你手动关一下禁止解析不会累死。。lean写这个默认过滤就是为了解决大多数人需要手动关ipv6各种接口麻烦的问题（你是少数，不会为了你这样的少数默认开启的，大多数是要关闭的，请理解，这是少数的代价）

**Comment by hhht110** [comment]
大佬啊 我第一次来这个 开源社区 我是 斐讯K3 的Opwrt固件  他作者的固件没有集成 passwall  我想用这个软件 请教一下怎么安装呀 疯了要

**Comment by youwei5683** [comment]
> 大佬啊 我第一次来这个 开源社区 我是 斐讯K3 的Opwrt固件 他作者的固件没有集成 passwall 我想用这个软件 请教一下怎么安装呀 疯了要

去学一下 如何编译openwrt固件吧。

**Comment by hhht110** [comment]
好吧 谢谢大佬&nbsp; 回复





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DingYongbin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月26日(星期四) 中午11:03
收件人:&nbsp;"Lienol/openwrt-package"<openwrt-package@noreply.github.com&gt;;
抄送:&nbsp;"小常"<454125259@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Lienol/openwrt-package] 希望处理一下passwall与IPv6的问题 (#347)





  
大佬啊 我第一次来这个 开源社区 我是 斐讯K3 的Opwrt固件 他作者的固件没有集成 passwall 我想用这个软件 请教一下怎么安装呀 疯了要
  
去学一下 如何编译openwrt固件吧。
