### ISSUE TITLE
编译的时候报错，说缺少ipt2socks

### ISSUE THREAD

**Issue by billy-zheng** [Lienol/openwrt-package#35]
如题

**Comment by feifan1113** [comment]
> 如题

我也是 即使把ipt2socks放在lean文件夹 也会报错

**Comment by billy-zheng** [comment]
https://github.com/zfl9/ipt2socks

**Comment by feifan1113** [comment]
> https://github.com/zfl9/ipt2socks
不是在 lean那勾选libuv这个依赖吗
