### ISSUE TITLE
passwall中chinadns-ng遇到的问题

### ISSUE THREAD

**Issue by wstxwd007** [Lienol/openwrt-package#351]
dns模式选择chinadns-ng后无论下方的选项选什么，手机的play商店app无法链接到google；dns模式换用pdnsd或者7913端口后app可以正常访问，但会无法访问某些网址，如www.inty3000.com （在chinadns-ng模式下该网址可以访问）

**Comment by ShanStone** [comment]
被墙了，把域名加入黑名单或者使用大陆白名单模式

**Comment by wstxwd007** [comment]
使用的是大陆白名单模式

**Comment by ShanStone** [comment]
> 使用的是大陆白名单模式

我这里无法复现，等其他人测试看看

**Comment by wstxwd007** [comment]
> > 使用的是大陆白名单模式
> 
> 我这里无法复现，等其他人测试看看

使用最原始的方法把play商城卸载重装后暂时解决了
