### ISSUE TITLE
不想抛弃lienol的固件，建议增加kpr去广告固件

### ISSUE THREAD

**Issue by e141313** [Lienol/openwrt-package#353]
如上，满足去广告+科学上网基本需求，增加kpr plus+去广告插件。免得用跳转用其他的固件了。

**Comment by ClayMoreBoy** [comment]
不是有人出个帖子说sarmtdns+adguardhome+passwall?

**Comment by andrewhe1234** [comment]
> 不是有人出个帖子说sarmtdns+adguardhome+passwall?

adguardhome不能过滤app， https广告， 
去广告大师也不行
但kpr可以，
请附加kpr， 感谢

**Comment by wefuxkgfw** [comment]
你是指猛禽编译好的x86_64固件，以后都加上Kpr吧。。。

**Comment by andrewhe1234** [comment]
> 你是指猛禽编译好的x86_64固件，以后都加上Kpr吧。。。

是的，感谢
