### ISSUE TITLE
SSR使用GWF模式下黑白名单失效

### ISSUE THREAD

**Issue by JeremyPeng** [Lienol/openwrt-package#355]
3月21日官方编译版本

SSR下，使用GWF模式，YouTube中页面可以打开页面，但是无法打开视频，googlevideo.com已经手动放入黑名单，google测试一直失败。

同样的设置下，切换至V2Ray下，不论是youtube和Google测速均无问题。

估计是SSR下黑白名单失效了....

**Comment by Lienol** [comment]
玄学bug

**Comment by JeremyPeng** [comment]
> 玄学bug

会不会是开了tls混淆，流量伪装成域名被挡了？我回去试试把伪装的url加到黑名单试试。。。

**Comment by JeremyPeng** [comment]
用Trojan了，不管了
