### ISSUE TITLE
更新v2ray源码到4.23.0后V2ray 服务器失效，恢复4.22.1后故障消失

### ISSUE THREAD

**Issue by tinnlux** [Lienol/openwrt-package#358]
更新v2ray源码到4.23.0后V2ray 服务器（luci-app-v2ray-server）失效，恢复4.22.1后故障消失，望修复

**Comment by Lienol** [comment]
No logs, how to solve?
Run v2ray command and you'll see why

**Comment by tinnlux** [comment]
> No logs, how to solve?
> Run v2ray command and you'll see why

sorry

**Comment by Lienol** [comment]
X64 Test No problem.
