### ISSUE TITLE
请问大佬passwall可不可以加一个HTTP代理选项！

### ISSUE THREAD

**Issue by youwei5683** [Lienol/openwrt-package#359]
请问大佬passwall可不可以加一个HTTP代理选项！
虽然 Privoxy 可以实现类似需求，但是如果一个插件能搞定的话更好啦！！

**Comment by Lienol** [comment]
最新源码可以利用V2ray的HTTP协议实现

**Comment by youwei5683** [comment]
> 最新源码可以利用V2ray的HTTP协议实现

还请大佬明示  passwall 里面没找到这个选项。 是要 用v2ray服务端 搭建一个 http服务器吗？

**Comment by Lienol** [comment]
你是想HTTP代理转透明代理还是 HTTP服务端？

**Comment by youwei5683** [comment]
> 你是想HTTP代理转透明代理还是 HTTP服务端？

应该是您理解的HTTP服务端。v2ray 不是可以这样配置么
		{
			"tag": "http-in",
			"protocol": "http",
			"domainOverride": [
				"http","tls"
			],
			"port": 5000,
			"settings": {}
		}
这样就可以成为一个 HTTP服务端了。 就像socks代理一样。 我想让大佬也加一个开关 
像开启socks 代理一样 打开一个 HTTP 服务端！

**Comment by LsnmxNB** [comment]
@Lienol  大佬加个HTTP代理服务端吧，现仅有Socks代理
