### ISSUE TITLE
编译时候ipt2socks出错

### ISSUE THREAD

**Issue by dengchan0416** [Lienol/openwrt-package#36]
![image](https://user-images.githubusercontent.com/41529838/69004881-d7c2eb80-0954-11ea-980d-40557b8b0d45.png)
我试过取消和选上include ipt2socks，就会出现图片出错

**Comment by dengchan0416** [comment]
请问是什么原因，我试过取消include ipt2socks，就会出现图片出错，选了上去也是会一样报错

> ![image](https://user-images.githubusercontent.com/41529838/69004881-d7c2eb80-0954-11ea-980d-40557b8b0d45.png)
> 每次编译到ipt2socks这里都会报错

**Comment by dengchan0416** [comment]
最新libuv包用什么命令，在线等

**Comment by Lienol** [comment]
lean的package好久没有更新，libuv包版本太久，所以报错。
为了方便大家编译，恢复用redsocks2

**Comment by feifan1113** [comment]
- 
![快照1](https://user-images.githubusercontent.com/57245399/69007411-6c8b1080-0978-11ea-8080-e998e9744af1.png)


- 我也报错了  而且是全新的重新编译

**Comment by dengchan0416** [comment]
> lean的package好久没有更新，libuv包版本太久，所以报错。
> 为了方便大家编译，恢复用redsocks2

那怎样做
