### ISSUE TITLE
Trojan切换到v2ray无法正常启动

### ISSUE THREAD

**Issue by jasonkarl** [Lienol/openwrt-package#360]
亲爱的L大，我同时订阅同一个机场的trojan和v2ray，我先启动trojan，然后更换v2ray节点，结果v2ray节点无法启动，切换回trojan正常。
编译的纯粹固件，或者安装IPK
均有此问题
虽然不能启动，但是passwall日志一切正常。
昨天请朋友试了一下，同样如此！

**Comment by jasonkarl** [comment]
最新版本依旧如此。

**Comment by Lienol** [comment]
It's no use just saying, where is the log???
Run v2ray command and you'll see why

**Comment by jasonkarl** [comment]
> It's no use just saying, where is the log???
> Run v2ray command and you'll see why
奇怪就在这里，我手动启动并没有发现错误，而且配置文件也很正常，现在就想问一下，能把订阅链接通过邮箱发给你吗？请L大测试一下，如果可以，请留下邮箱。

**Comment by Lienol** [comment]
点开我的信息里面有

**Comment by jasonkarl** [comment]
> 点开我的信息里面有

已发送，非常感谢！

**Comment by Lienol** [comment]
已修复
