### ISSUE TITLE
关于插件的引用请教

### ISSUE THREAD

**Issue by yfdoor** [Lienol/openwrt-package#363]
关于引用插件的请教:
我编译固件的时候引用了大佬的 package ，编译的时候 config 文件 定义了:
CONFIG_LUCI_LANG_zh_Hans=y
然后比如我也定义了下面的插件:
CONFIG_PACKAGE_luci-app-control-mia=y
CONFIG_PACKAGE_luci-app-ssr-plus=y
编译后的固件luci界面的菜单栏显示的是 "control",而不是本土化的 "管控"。而ssr 在菜单里显示的名称也是英文的。但是每个插件内的设置界面确都是中文。
请教下如下问题:
1、luci中，哪里定义菜单栏每个分类在菜单中的顺序？
2、为啥会出现这种菜单内的名称无法汉化的现象？汉化不完整？
我直接下载大佬编译好的固件，里面的菜单确都是正常的，请指导下还需要修改哪里。多谢了。

**Comment by Lienol** [comment]
用官源就自己排坑，自己解决。
