### ISSUE TITLE
在线升级后产生额一点小问题

### ISSUE THREAD

**Issue by Kisoul** [Lienol/openwrt-package#365]
![image](https://user-images.githubusercontent.com/32985553/77394578-b37f8b80-6dda-11ea-8893-d19b3a11e939.png)
主要问题是如果负载均衡单口上一个节点没填，那么会出现miss的字样，是不是可以相办法有优化一下，这个问题好像在必填空没填的地方都会出现，比如订阅地址。
能否在屏幕上方提示一句话，这样会清晰一点。谢谢。
![image](https://user-images.githubusercontent.com/32985553/77398508-9f3f8c80-6de2-11ea-9ba7-5385c9252fd9.png)
补充一下，我无意多点了几下新增节点，结果卡了，但是路由还有上网功能，我估计是tcp在空ping？导致路由假死？

**Comment by Lienol** [comment]
必填项
