### ISSUE TITLE
开启负载均衡后udp选择与tcp同一节点无法科学上网的bug

### ISSUE THREAD

**Issue by Kisoul** [Lienol/openwrt-package#366]
![image](https://user-images.githubusercontent.com/32985553/77436507-8a80ea00-6e1e-11ea-9e6e-ae843bfdc6d4.png)
如图
关闭udp后，负载均衡依然无法运行，只能单节点用了

**Comment by Lienol** [comment]
1. 估计是你负载均衡配置有问题
2. 说过好多次了，haproxy负载均衡不支持udp

**Comment by Kisoul** [comment]
> 1. 估计是你负载均衡配置有问题
> 2. 说过好多次了，haproxy负载均衡不支持udp

现在没法恢复了。哭死了

**Comment by Kisoul** [comment]
![image](https://user-images.githubusercontent.com/32985553/77440092-d6ce2900-6e22-11ea-93dc-052eb9d7fadd.png)
现在通了。可是局域网的设备没法出去了

**Comment by Kisoul** [comment]
> 1. 估计是你负载均衡配置有问题
> 2. 说过好多次了，haproxy负载均衡不支持udp

补充一下，我从新刷机了，然后负载均衡是好的，但在passwall中提交了一个访问白名单后保存应用后，haproxy再次无法启动，唯一解决办法就是重启路由器。
我的负载设置如下，除了节点域名不一样剩下的ssr设置参数完全一样。
![image](https://user-images.githubusercontent.com/32985553/77452142-91b0f380-6e30-11ea-8db3-e11d167a8510.png)
