### ISSUE TITLE
新版编译后socks5节点无法运行tcp代理

### ISSUE THREAD

**Issue by Tony-1998** [Lienol/openwrt-package#368]
和 #285 完全一样的情况

**Comment by Lienol** [comment]
Fix.
如果不穩定可以試試最新源碼的v2ray socks

**Comment by Tony-1998** [comment]
> Fix.
> 如果不穩定可以試試最新源碼的v2ray socks

谢谢大佬更新，现在已经可以使用TCP代理了，我是在n1上跑的v2ray，和前面的老哥一样套路，k2p性能太差了
