### ISSUE TITLE
移植passwall,基本设置页面异常

### ISSUE THREAD

**Issue by waynesg** [Lienol/openwrt-package#37]
<a href="https://sm.ms/image/PqWGARrZjI63bJu" target="_blank"><img src="https://i.loli.net/2019/11/18/PqWGARrZjI63bJu.png" ></a>

如图,是否冲突所致?

**Comment by Lienol** [comment]
进入高级设置，保存应用后再试试

**Comment by waynesg** [comment]
> 进入高级设置，保存应用后再试试

已解决，感谢！
