### ISSUE TITLE
 3.6-30更新订阅和通过连接添加节点有问题

### ISSUE THREAD

**Issue by whspider** [Lienol/openwrt-package#373]
3.6-30更新订阅和通过连接添加节点有问题
之前的版本是由更早的版本在自动更新--更新主程序--PassWall 版本那里点手动更新，自动升级上来的3.6-28(具体不记得了或是更早的版本)是OK的
今天看到有3.6-30的更新，同样在自动更新--更新主程序--PassWall 版本那里点手动更新更新以后连接什么的都没问题。
但是下面几点有问题
1负载均衡的配置会掉。
2通过连接添加节点没有反应。没有日志文件。试了SSR和trojan都一样不行。
3通过节点订阅-手动订阅。订阅不上报错日志如下。订阅地址删了。
路由恢复了之前的配置备份还是一样的情况

2020-03-25 20:25:39: 开始订阅...
2020-03-25 20:25:39: 正在订阅: 这里地址是正确的别的地方订阅没问题。
2020-03-25 20:25:40: /usr/share/passwall/subscribe.lua:88: bad argument #1 to 'ipairs' (table expected, got nil)
2020-03-25 20:25:40: stack traceback:
	/usr/share/passwall/subscribe.lua:589: in function </usr/share/passwall/subscribe.lua:587>
	[C]: in function 'foreach'
	/usr/share/passwall/subscribe.lua:567: in function </usr/share/passwall/subscribe.lua:564>
	[C]: in function 'xpcall'
	/usr/share/passwall/subscribe.lua:587: in main chunk
	[C]: ?
2020-03-25 20:25:40: 发生错误, 正在恢复服务
2020-03-25 20:25:40: 订阅完毕...

SSR和trojan报同样的错

主机名 | OpenWrt
-- | --
主机型号 | Phicomm N1
架构 | ARMv8 Processor rev 4 (v8l) x 4
固件版本 | OpenWrt  R20.3.11 /			LuCI Master (git-20.062.50551-a6189c5)
内核版本 | 5.4.25-amlogic-flippy-30+

**Comment by Kisoul** [comment]
我是29负载均衡也会掉，唯有重启才能用。366里我做了很久测试。

**Comment by whspider** [comment]
> 我是29负载均衡也会掉（配置还在，就是不能点passwall的保存与应用，点了负载均衡就再也起不来了），唯有重启才能用。366里我做了很久测试。



> 我是29负载均衡也会掉（配置还在，就是不能点passwall的保存与应用，点了负载均衡就再也起不来了），唯有重启才能用。366里我做了很久测试。

能订阅节点吗

**Comment by Kisoul** [comment]
> > 我是29负载均衡也会掉（配置还在，就是不能点passwall的保存与应用，点了负载均衡就再也起不来了），唯有重启才能用。366里我做了很久测试。
> 
> > 我是29负载均衡也会掉（配置还在，就是不能点passwall的保存与应用，点了负载均衡就再也起不来了），唯有重启才能用。366里我做了很久测试。
> 
> 能订阅节点吗

可以

**Comment by Lienol** [comment]
恢复passwall配置重新配置 不要保留旧的配置文件

**Comment by Kisoul** [comment]
> 恢复passwall配置重新配置 不要保留旧的配置文件

我是完全从新编译的

> 恢复passwall配置重新配置 不要保留旧的配置文件

升级到32了，http://192.168.1.1/cgi-bin/luci/admin/vpn/passwall/reset_config恢复初始配置结果负载均衡依然起不来，虽然重启路由器可以让负载均衡恢复，但是由于开启了自动订阅和更新，到了那个时间，负载均很就掉了，估计passwall到时间自动更新后做了类似保存应用的相同动作，导致负载均衡又挂了。
