### ISSUE TITLE
关于高可以用的一个实现方案预想

### ISSUE THREAD

**Issue by luomoxu** [Lienol/openwrt-package#376]
因为自己有好几个服务器节点可用
为了实现高可用和负载均衡所以预想了一个实现方案，目标是保证大部分情况下服务是可用的
和大神讨论下可行性的问题
下面是示例图，说下我个人认为的优势

1. 支持跨协议的负载均衡
1. 支持快速的横向扩展

![流程图](https://user-images.githubusercontent.com/1317574/77630505-237e4500-6f86-11ea-8f1e-d14e44f7b6a9.png)

**Comment by Lienol** [comment]
方案是可行的

**Comment by Lienol** [comment]
不过luci这结构，要改造有点麻烦。
不过可以尝试使用我提供的方案（实际上我没试过，不过理论上是可行的）：
passwall内同时开多个socks节点，然后HA负载均衡里添加这127.0.0.1:socks端口，设置好比重。然后TCP节点使用负载均衡的节点。
你可以尝试试试。

**Comment by luomoxu** [comment]
我尝试下 不过这里有个问题是ha对socks做默认健康检测的可用性结果可能是不准确的

**Comment by luomoxu** [comment]
还有一个就是貌似现在最大打开3个socks节点
