### ISSUE TITLE
卸载和安装IPK出错

### ISSUE THREAD

**Issue by liliass** [Lienol/openwrt-package#377]
固件 eSir v3.1 

> root@OpenWrt:/tmp/upload# ls
luci-app-passwall_3.6-28_all.ipk  luci-app-ssr-plus_173-6_all.ipk
luci-app-passwall_3.6-32_all.ipk
root@OpenWrt:/tmp/upload# opkg remove luci-app-passwall
Removing package luci-app-passwall from root...
root@OpenWrt:/tmp/upload# opkg install luci-app-passwall_3.6-32_all.ipk
Installing luci-app-passwall (3.6-32) to root...
Configuring luci-app-passwall.
cat: can't open '/var/run/haproxy.pid': No such file or directory
sh: you need to specify whom to kill
uci: Entry not found
uci: Entry not found
root@OpenWrt:/tmp/upload# 

>/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/vpn/passwall/balancing'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:38: Model 'passwall/balancing' not found!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by Lienol** [comment]
删除luci缓存
或者直接重启路由
