### ISSUE TITLE
增加v2ray fast open选项

### ISSUE THREAD

**Issue by ioioioion** [Lienol/openwrt-package#378]
https://www.v2ray.com/chapter_02/05_transport.html
e.g
```json
  "sockopt": {
    "tcpFastOpen": true
  }
```

**Comment by youwei5683** [comment]
V2RAY官方文档说的很清楚，Linux 3.16: 系统已默认开启，无需要配置。
如果楼主有强迫症可以修改openwrt 
/usr/lib/lua/luci/model/cbi/passwall/api 下的 gen_v2ray.lua 文件
在第26行的位置 插入
 sockopt = {tcpFastOpen = true},
注意逗号不可以少，亲测有效。

**Comment by ioioioion** [comment]
![TFO_no](https://user-images.githubusercontent.com/7686842/77662000-47f21580-6fb6-11ea-95a7-41883e1b71a8.PNG)
![TFO_yes](https://user-images.githubusercontent.com/7686842/77662010-49bbd900-6fb6-11ea-98c5-b9feab763995.PNG)
@youwei5683  服务端我抓包没有找到带cookie的包 对比验证在手机端quanX环境下是可以找到TFO的生效的包的 我先试试手动编辑吧

**Comment by ioioioion** [comment]
确认没有TFO的包和配置无关 应该是网络环境的问题
