### ISSUE TITLE
关于多播情况下的负载均衡掉线的bug反馈。

### ISSUE THREAD

**Issue by Kisoul** [Lienol/openwrt-package#379]
![image](https://user-images.githubusercontent.com/32985553/77653400-95688580-6faa-11ea-8b3e-d65c4662423f.png)
我自己的验证发现如果"多WAN指定出口"选择自动一定会在保存运用后导致负载均衡无法启动，但是如果指定了蓝框以外的（pppoe接口）就不会有这个问题，我研究了koolshare的负载均衡，推测图中蓝色的选项是造成负载均衡失败的原因。因为这些接口并不是WAN口（koolshare的负载均衡中没有这些接口）。真正有效的是蓝框以外的。
所以推测取消无用的接口，然后在自动应该就不会有问题了。

**Comment by Lienol** [comment]
代码上如果选自动是不会生成静态路由的
