### ISSUE TITLE
V2ray订阅不完整，还有GFW列表不能正常使用

### ISSUE THREAD

**Issue by yoyi412** [Lienol/openwrt-package#38]
订阅不完整，原本的V2ray订阅节点有38个的，但是只能订阅阅读到18个
GFW列表已经是最新的更新日期了，但是选择代理模式为GFW还是不能正常使用的

望作者或者其他开发者修复一下以上问题，跪谢

**Comment by Lienol** [comment]
能提供订阅链接发我邮箱吗？

**Comment by yoyi412** [comment]
> 能提供订阅链接发我邮箱吗？

已经发你的谷歌邮箱了，望大佬查看

**Comment by Lienol** [comment]
已修复

**Comment by yoyi412** [comment]
> 已修复

谢谢大佬
