### ISSUE TITLE
突发奇想给大佬的passwall里面的v2ray添加 http代理 和 shadowsocks回家！

### ISSUE THREAD

**Issue by youwei5683** [Lienol/openwrt-package#382]
---本人也是小白，大神不要喷！
注意此方法只使用于服务器为v2ray的用户。修改前请自行备份 gen_v2ray.lua 文件
需要修改openwrt   /usr/lib/lua/luci/model/cbi/passwall/api目录下的 gen_v2ray.lua 文件。
推荐用 notepad++ 编辑器。
打开 gen_v2ray.lua 文件 大概在 94 行的位置。找到 if socks5_proxy_port ~= "nil" then
删掉  if socks5_proxy_port ~= "nil" then 到  end 之间的所有内容
并添加

    table.insert(inbounds, {
        listen = "0.0.0.0",
        port = socks5_proxy_port,
        protocol = "socks",
        settings = {auth = "noauth", udp = true, ip = "127.0.0.1"}
    })
    network = "tcp,udp", --这里需要先添加一个英文逗号。
	
	-- 修改之前请先执行备份该文件。。。
	-- 添加HTTP代理	 port是想要开放的端口 可自行修改。http代理一般作为内网使用所以不加认证。
	table.insert(inbounds, {
			listen = "0.0.0.0",
			port = "8118",
			protocol = "http",
			destOverride = {"http", "tls"}
		}
	)
	
	-- 添加shadowsocks
	table.insert(inbounds, {
			listen = "0.0.0.0",
			port = "8388",
			protocol = "shadowsocks",
			destOverride = {"http", "tls"},
			--method 为加密方式可自行修改
			--password 为密码可按需修改
			settings = {method = "aes-256-cfb", udp = true, password = "password"}
		}
	)

然后到passwall网页打开socks代理，保存！
路由器做端口映射就可以通过shadowsocks回家啦。并且也可以愉快的使用http代理

**Comment by Lienol** [comment]
有单独的v2ray服务端

**Comment by dominicx** [comment]
> ---本人也是小白，大神不要喷！
> 注意此方法只使用于服务器为v2ray的用户。修改前请自行备份 gen_v2ray.lua 文件
> 需要修改openwrt /usr/lib/lua/luci/model/cbi/passwall/api目录下的 gen_v2ray.lua 文件。
> 推荐用 notepad++ 编辑器。
> 打开 gen_v2ray.lua 文件 大概在 94 行的位置。找到 if socks5_proxy_port ~= "nil" then
> 删掉 if socks5_proxy_port ~= "nil" then 到 end 之间的所有内容
> 并添加
> 
> ```
> table.insert(inbounds, {
>     listen = "0.0.0.0",
>     port = socks5_proxy_port,
>     protocol = "socks",
>     settings = {auth = "noauth", udp = true, ip = "127.0.0.1"}
> })
> network = "tcp,udp", --这里需要先添加一个英文逗号。
> 
> -- 修改之前请先执行备份该文件。。。
> -- 添加HTTP代理	 port是想要开放的端口 可自行修改。http代理一般作为内网使用所以不加认证。
> table.insert(inbounds, {
> 		listen = "0.0.0.0",
> 		port = "8118",
> 		protocol = "http",
> 		destOverride = {"http", "tls"}
> 	}
> )
> 
> -- 添加shadowsocks
> table.insert(inbounds, {
> 		listen = "0.0.0.0",
> 		port = "8388",
> 		protocol = "shadowsocks",
> 		destOverride = {"http", "tls"},
> 		--method 为加密方式可自行修改
> 		--password 为密码可按需修改
> 		settings = {method = "aes-256-cfb", udp = true, password = "password"}
> 	}
> )
> ```
> 
> 然后到passwall网页打开socks代理，保存！
> 路由器做端口映射就可以通过shadowsocks回家啦。并且也可以愉快的使用http代理

我单独安装了个v2ray，通过v2ray回家，然后就可以从公司到家了再出去。
