### ISSUE TITLE
luci-app-pptp-vpnserver-manyusers有一个BUG

### ISSUE THREAD

**Issue by chiyu521** [Lienol/openwrt-package#383]
luci-app-pptp-vpnserver-manyusers 当开启VPN后 FULLCONENAT就失效了 关闭就正常 不知道是哪里的问题

**Comment by Lienol** [comment]
在用版本是什么？哪个分支？我测试下

**Comment by Lienol** [comment]
![image](https://user-images.githubusercontent.com/23146169/77865736-785ddc00-7262-11ea-87cf-93d8dd6ed12d.png)
![image](https://user-images.githubusercontent.com/23146169/77865740-7e53bd00-7262-11ea-9baf-576b04bc5682.png)
测试正常，注意pptp不应和lan网段相同

**Comment by chiyu521** [comment]
我路由器IP是192.168.0.1 PPTP服务器IP也设置相同的192.168.0.1~  别的没动过

**Comment by chiyu521** [comment]
如果我要是在PPTP里设置服务器IP 192.168.2.1 当连接PPTP后无法上网 只有和路由IP一致才可以

**Comment by Lienol** [comment]
nat1失败 估计是pptp网段和lan网段相同导致的

**Comment by chiyu521** [comment]
那我现在重新编译个 然后测试 回来报告

**Comment by chiyu521** [comment]
报告: PPTP 服务器改成2.1后 恢复正常 NAT1了!
