### ISSUE TITLE
建议优化：Passwall可以不设置gfwlist和blacklist给dnsmasq

### ISSUE THREAD

**Issue by ppdragon16** [Lienol/openwrt-package#388]
当用ChinaDNS-NG模式时，Passwall依然给gfwlist配置了gfwlist和blacklist，把请求转发给127.0.0.1#7913。由于已经配置了server=127.0.0.1#7913，没有必要再配置gfwlist和blacklist。
大量的gfwlist条目可能会影响dnsmasq的转发性能。

**Comment by Lienol** [comment]
server=那条的确是不需要了，但是ipset需要的，不然无法ipset分流

**Comment by ppdragon16** [comment]
哦，是的。ipset不能删。

**Comment by ppdragon16** [comment]
我目前删除了gfwlist，用“大陆白名单”模式上网没有收到影响。
请问有好的方法测试一下ipset分流吗？
