### ISSUE TITLE
dns解析死循环？

### ISSUE THREAD

**Issue by bigbighill** [Lienol/openwrt-package#391]
1、配置情况：
国内dns  默认
china-ng  可信dns  127.0.0.1#6053(smartdns 上游dns为 8.8.8.8等)
大陆白名单模式
节点：自建的trojan、v2ray等，服务器：域名(不是vps ip)
2、bug描述：
采用国大陆白名单模式时，客户端访问google时,passwall会走可信dns交smartdns解析，
由于上游DNS均在黑名单中，必然走代理,但由于节点配置是vps域名，也要交smartdns后走代理解析。
这就形成了死循环bug了。无法翻墙。
这时只有手动在passwall中测试下节点后，客户端才能正常访问google。

**Comment by Lienol** [comment]
vps域名交给国内dns解析

**Comment by bigbighill** [comment]
> vps域名交给国内dns解析

这个流量也算是路由器自身流量？
可设置路由器自身流量模式？ 选gfw模式？
