### ISSUE TITLE
Domain name whitelist is not working with v2ray shunt

### ISSUE THREAD

**Issue by buxiaomo** [Lienol/openwrt-package#395]
when I add the 'checkip.dyndns.com' to whitelist, I get the ip is proxy server ip or network operator's ip, like this

1、cn ip
2、proxy ip
3、cn ip
4、proxy ip
...

**Comment by Lienol** [comment]
Clear DNS cache

**Comment by buxiaomo** [comment]
restart dns service?

**Comment by Lienol** [comment]
Do you use router self-detection or other device detection? Try to ipconfig/flushdns

**Comment by buxiaomo** [comment]
thanks
