### ISSUE TITLE
passwall V2RAY分流节点使用机场节点偶尔丢失问题

### ISSUE THREAD

**Issue by co1q84** [Lienol/openwrt-package#397]
订阅更新后，节点位置变了？
然后分流节点里用到的节点就为空了

如果确实没法保留，建议为空后，随机选个带Netflix名字的节点（或自定义节点名字，模糊匹配）

**Comment by Lienol** [comment]
的确存在此问题

**Comment by Lienol** [comment]
[subscribe.lua.txt](https://github.com/Lienol/openwrt-package/files/4434224/subscribe.lua.txt)
测试一下，下载后把后缀.txt去掉，覆盖/usr/share/passwall/subscribe.lua
没问题我再提交

**Comment by Lienol** [comment]
@ShanStone 帮忙测下？

**Comment by ShanStone** [comment]
> @ShanStone 帮忙测下？

我订阅过几次，我这里v2分流节点位置不变

**Comment by co1q84** [comment]
订阅没问题了。
稳。现在只有移动节点排序保持时，会丢了。
