### ISSUE TITLE
双WAN不能指定其中一个出口

### ISSUE THREAD

**Issue by dengchan0416** [Lienol/openwrt-package#40]
我有一条电信wan和一条联通wan2,试过国内DNS指定解析出口选联通,客户端指定出口也选联通,查询IP还是检查出电信做出口.[http://chuantu.xyz/t6/703/1574342805x992245926.png](url),我也试过按图片那样调转设置还是不能,我要联通做翻墙出口,电信做国内出口,像SSR+有这样设置,可是SSR+只能设置IP很不方便,[http://chuantu.xyz/t6/703/1574343362x992245926.png](url)

**Comment by Lienol** [comment]
你可能对ssrplus+的黑白名单有点误解

**Comment by Lienol** [comment]
你双线接入的话，可在负载均衡规则里面设置服务器IP走指定的线路

**Comment by dengchan0416** [comment]
ssrplus+不是有强制走代理WAN IP
[http://chuantu.xyz/t6/703/1574562021x992245975.png](url)
