### ISSUE TITLE
passwall和QOS不兼容

### ISSUE THREAD

**Issue by jerryliang122** [Lienol/openwrt-package#401]
openwrt标准的QOS启动后，会和PASSWALL 出现冲突具体表现为无法代理，原因不明（没有日志）今天PULL的源码。

**Comment by jerryliang122** [comment]
知道的是，同样用到iptables，但是作者大大能解释一下，用iptables打标记后的包为啥没办法再代理了

**Comment by Lienol** [comment]
可能是吧，好久不用QOS了
