### ISSUE TITLE
建议增加V2RAY代理转发功能，实现使用机场中转个人节点功能

### ISSUE THREAD

**Issue by co1q84** [Lienol/openwrt-package#402]
机场还是用的有点担心。如果使用机场中转、加速个人节点，便安心多了。。
看V2RAY的操作指导，本身是支持这个功能的。建议考虑在PASSWALL新建节点的时候可以自定义加入机场节点进行代理转发。

参考：
[https://toutyrater.github.io/advanced/outboundproxy.html](url)
[https://acuario.xyz/delegate-v2ray-traffic-to-ss-or-ssr/](url)

**Comment by Lienol** [comment]
这个早已有打算，不过我觉得放到单独的v2ray比较好管理

**Comment by Lienol** [comment]
看错了，我以为你说要做服务端中转

**Comment by co1q84** [comment]
看了下ssr plus+，那边的分流服务器（前置）代理功能应该也类似。

**Comment by viagram** [comment]
只想测试新版passwall

**Comment by hzjnet** [comment]
请教：能配置同端口、密码、加密协议的SSR负载均衡吗？ 如果能应该如何设置喃？如果不能为啥windows版本的ShadowsocksR v5xx版本选取服务器--负载均衡就好了，同时在服务器链接统计就能可能看见不同节点跑的流量负载！    谢谢

**Comment by viagram** [comment]
> 请教：能配置不同端口、密码、加密协议的SSR负载均衡吗？ 如果能应该如何设置喃？如果不能为啥windows版本的ShadowsocksR v5xx版本选取服务器--负载均衡就好了，同时在服务器链接统计就能可能看见不同节点跑的流量负载！ 谢谢

其实很多问题都能在网路上打到答案，建议先谷歌，后提问。

**Comment by cabbyjing** [comment]
> 看错了，我以为你说要做服务端中转

这个功能确实很好，可否考虑下
