### ISSUE TITLE
passwall建议增加定时自动切换节点功能

### ISSUE THREAD

**Issue by FoxDring** [Lienol/openwrt-package#406]
比如节点1白天快一点，但流量费率高。而节点2因为费率低导致用的人多，白天速度非常慢，但深夜速度极佳，所以每次到深夜只能手动切换到节点2以节省流量。所以建议增加一个定时自动切换主节点的功能，比如可以设置0:30自动切换为节点2，到8:00自动切换为节点1。望采纳。

**Comment by Lienol** [comment]
插件不能满足100%的人，需求不一样。
你可以自己写个脚本。
