### ISSUE TITLE
passwall3.6-29貌似有一个bug，启用访问控制，关闭TCP默认代理模式后，谷歌连接显示失败，其实可以用。

### ISSUE THREAD

**Issue by benzh1213** [Lienol/openwrt-package#409]
L大你好，目前升级PASSWALL至最新版本，关闭TCP默认代理模式，然后启用访问控制，设置有需要的设备访问谷歌，功能没问题，但是在主页上额谷歌连接一直显示失败，前一个版本是正常的，请教一下是不是哪里设置的不对，或的确有此bug，谢谢。
![Snipaste_2020-04-07_13-20-00](https://user-images.githubusercontent.com/62641767/78632819-96ff4b00-78d2-11ea-9aa5-78cd412c7058.jpg)
![2020-04-07 13 20 16](https://user-images.githubusercontent.com/62641767/78632824-9961a500-78d2-11ea-9f8a-706fcd5ac618.jpg)

**Comment by Lienol** [comment]
最新不是3.6-29
且你路由器本机代理模式设置了默认，然后默认代理模式选不代理，所以 路由器本机代理模式=不代理=Google失败
你应本机代理模式选gfw或大陆

**Comment by benzh1213** [comment]
按照您的方法，ok了，谢谢老大。
我看了最新的版本是3.6-35，前面那张图截得是另外一个路由，不好意思。
![Snipaste_2020-04-08_00-43-12](https://user-images.githubusercontent.com/62641767/78696469-0bb5a200-7932-11ea-8f61-736c57add8c8.jpg)
