### ISSUE TITLE
负载均衡配置请教

### ISSUE THREAD

**Issue by hzjnet** [Lienol/openwrt-package#410]
请教：能配置不同端口、密码、加密协议的SSR负载均衡吗？ 如果能应该如何设置喃？如果不能为啥windows版本的ShadowsocksR v5xx版本选取服务器--负载均衡就好了，同时在服务器链接统计就能可能看见不同节点跑的流量负载！ 谢谢

**Comment by Lienol** [comment]
不一样的

**Comment by kang-mk** [comment]
做是可以做到的，只要你愿意每个节点都开一个线程，开它几十个线程，不考虑资源占用就行，但是在软路由上几乎没人这么干，自然也没有开发者来这么写，所以你只能花钱定制一个插件了
