### ISSUE TITLE
passwall最新版启用chinadns-dns无法科学！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#411]
![0}Y~G2HTT K1(BA8RA2H9_6](https://user-images.githubusercontent.com/45259624/78731679-f44ad900-7972-11ea-9469-41d00dada3c7.png)
![6(OLOU RSUI{4BC}ZJYP99N](https://user-images.githubusercontent.com/45259624/78731688-fad95080-7972-11ea-8edb-9633617bd322.png)

**Comment by Lienol** [comment]
@ShanStone

**Comment by Lienol** [comment]
可信dns试试用pdnsd解析

**Comment by ShanStone** [comment]
无法复现，有可能是你运营商劫持了dns解析结果，可信dns使用pdnsd或者dns2socks试试

**Comment by zxlhhyccc** [comment]
> 无法复现，有可能是你运营商劫持了dns解析结果，可信dns使用pdnsd或者dns2socks试试

pdnsd可以正常解析。。。passwall中好像没dns2socks。。。

**Comment by ShanStone** [comment]
> > 无法复现，有可能是你运营商劫持了dns解析结果，可信dns使用pdnsd或者dns2socks试试
> 
> pdnsd可以正常解析。。。passwall中好像没dns2socks。。。

可能是你没有把dns2socks编译进去，那就用pdnsd好了

**Comment by zxlhhyccc** [comment]
> 无法复现，有可能是你运营商劫持了dns解析结果，可信dns使用pdnsd或者dns2socks试试

经测试，v2ray、ssr能正常解析，但是ss+kcptun时，只有pdnsd可以正常解析。。。。

**Comment by ShanStone** [comment]
> > 无法复现，有可能是你运营商劫持了dns解析结果，可信dns使用pdnsd或者dns2socks试试
> 
> 经测试，v2ray、ssr、trojan能正常解析，但是ss+kcptun时，只有pdnsd可以正常解析。。。。
> kcptun参数配置如下：
> ![image](https://user-images.githubusercontent.com/45259624/78744565-7ef00000-7994-11ea-8801-3a6c1dead0f6.png)

kcptun似乎不支持转发udp，pdnsd是使用TCP查询的

**Comment by zxlhhyccc** [comment]
> > > 无法复现，有可能是你运营商劫持了dns解析结果，可信dns使用pdnsd或者dns2socks试试
> > 
> > 
> > 经测试，v2ray、ssr、trojan能正常解析，但是ss+kcptun时，只有pdnsd可以正常解析。。。。
> > kcptun参数配置如下：
> > ![image](https://user-images.githubusercontent.com/45259624/78744565-7ef00000-7994-11ea-8801-3a6c1dead0f6.png)
> 
> kcptun似乎不支持转发udp，pdnsd是使用TCP查询的

但是使用pdnsd时候能正常解析使得ss+kcptun科学。。。难道其他的都不能正常解析吗？经测试ssrplus+可以在使用kcptun时候dns2socks正常解析。。。

**Comment by pizidehao** [comment]
我也碰到了同样的情况 求大佬修复原来的版本没这问题

**Comment by pizidehao** [comment]
经测试，使用 ChinaDns-NG 模式 trojan 无法出国SSR正常

**Comment by Lienol** [comment]
直接用ChinaDNS-NG，可信直接填公网DNS是直接使用UDP节点解析的
而如果选Pdnsd则会使用TCP节点去解析
dns2socks则是使用socks节点去解析

**Comment by zxlhhyccc** [comment]
> 直接用ChinaDNS-NG，可信直接填公网DNS是直接使用UDP节点解析的
> 而如果选Pdnsd则会使用TCP节点去解析
> dns2socks则是使用socks节点去解析

ChinaDNS-NG时候选择默认、公网dns，ss+kcptun下均不行。。。

**Comment by Lienol** [comment]
kcptun不支持udp

**Comment by Lienol** [comment]
你这种情况，直接用pdnsd tcp查询就行了

**Comment by zxlhhyccc** [comment]
> kcptun不支持udp

但vps服务器里我设置的是udp转发，tcp没开启。。。
其次，ssrplus+使用dns2socks、pdnsd能解析。。。

**Comment by Lienol** [comment]
> > kcptun不支持udp
> 
> 但vps服务器里我设置的是udp转发，tcp没开启。。。
> 其次，ssrplus+使用dns2socks、pdnsd能解析。。。

应该是ss+kcptun时作为socks节点并没有使用kcptun导致

**Comment by zxlhhyccc** [comment]
> > > kcptun不支持udp
> > 
> > 
> > 但vps服务器里我设置的是udp转发，tcp没开启。。。
> > 其次，ssrplus+使用dns2socks、pdnsd能解析。。。
> 
> 应该是ss+kcptun时作为socks节点并没有使用kcptun导致

如果是作为socks节点没使用kcptun的话，为啥v2ray、trojan却正常解析？

**Comment by Lienol** [comment]
可以说是也可以说不是，因为写的时候，只有TCP是使用Kcptun，而Socks没有判断

**Comment by lemon1203** [comment]
chinadns-ng模式，可信dns选择pdnsd，trojan无法使用，使用adguardhome做Dnsmasq上游查询日志看到外网地址被定向到国内dns而不是走vps隧道，3.6-32之后版本都是如此。

**Comment by cheneyxx** [comment]
> 国内Dns使用Adguardhome做Dnsmasq上游自定义端口，Dns模式使用dnschinadns-ng，可信dns选择pdnsd，trojan无法使用，Adguardhome查询日志看到外网地址Dns被定向到国内dns而不是走vps隧道，3.6-32之后版本都是如此。

我和你一样

**Comment by Lienol** [comment]
> 国内Dns使用Adguardhome做Dnsmasq上游自定义端口，Dns模式使用dnschinadns-ng，可信dns选择pdnsd，trojan无法使用，Adguardhome查询日志看到外网地址Dns被定向到国内dns而不是走vps隧道，3.6-32之后版本都是如此。

为什么要这样用？最好不要改变默认dnsmasq
adg直接跑非53端口，adg上游设置127.0.0.1，也就是上游是dnsmasq，然后passwall里面的dns不要设置adg。删掉默认的dns劫持iptables规则，adg设置重定向53端口。

**Comment by lemon1203** [comment]
谢谢大神回复，我试试看你说的这样设置，OP固件主要还是lede，觉得passwall更好用所以增加了passwall，刚开始不确定是OP问题还是passwall的问题，看到有人反馈才确定，现在ipk版的Adguardhome设置是自定义1053端口作为Dnsmasq上游，passwall的dns为dnschinadns-ng，主要是加了anti-AD规则去电视广告，还有拦截IOS更新，虽然adbyby-plus和防火墙添加域名也可以，但是一直这样用习惯了，也方便管理，而且使用passwall所有功能正常，直到3.6-32之后的版本就有问题，而且确定dnschinadns-ng有问题以后用docker再弄了一个Adguardhome也就是双Adguardhome。国内dns端口1053，国外dns定向到7913端口，发现域名黑名单不起作用，添加域名后还是走国内dns了，不知道是不是我的问题。

**Comment by lemon1203** [comment]
> > 国内Dns使用Adguardhome做Dnsmasq上游自定义端口，Dns模式使用dnschinadns-ng，可信dns选择pdnsd，特洛伊木马无法使用，Adguardhome查询日志看到外网地址Dns被定向到国内dns而不是走vps隧道，3.6- 32之后版本都是如此。
> 
> 为什么要这样用？最好不要改变dnsmasq
> adg直接跑非53端口，adg上游设置127.0.0.1，也就是上游是dnsmasq，然后passwall里面的dns不要设置adg。减少掉的dns劫持iptables规则，adg设置重置53端口。

谢谢大神回复，我试试看你说的这样设置，OP固件主要还是lede，觉得passwall更好用所以增加了passwall，刚开始不确定是OP问题还是passwall的问题，看到有人反馈才确定，现在ipk版的Adguardhome设置是自定义1053端口作为Dnsmasq上游，passwall的dns为dnschinadns-ng，主要是加了anti-AD规则去电视广告，还有拦截IOS更新，虽然adbyby-plus和防火墙添加域名也可以，但是一直这样用习惯了，也方便管理，而且使用passwall所有功能正常，直到3.6-32之后的版本就有问题，而且确定dnschinadns-ng有问题以后用docker再弄了一个Adguardhome也就是双Adguardhome。国内dns端口1053，国外dns定向到7913端口，发现域名黑名单不起作用，添加域名后还是走国内dns了，不知道是不是我的问题。图中的设置3.6-32一直使用正常。
![QQ图片20200409213007](https://user-images.githubusercontent.com/57431145/78900545-8ead3880-7aa9-11ea-94cb-674e3f08150a.png)
![QQ图片20200409213024](https://user-images.githubusercontent.com/57431145/78900565-979e0a00-7aa9-11ea-976f-fbee66f6907c.png)
![QQ图片20200409213048](https://user-images.githubusercontent.com/57431145/78900572-9a98fa80-7aa9-11ea-9a8e-e7b97d0110e2.png)
