### ISSUE TITLE
建议更改延迟启动行为

### ISSUE THREAD

**Issue by LitingLin** [Lienol/openwrt-package#414]
拨号比较慢的地方会导致1秒延迟启动仍然不能正常解析域名，使得ss会立即退出。
Options:
1. 在系统启动后的一段时间内重复测试网络连通性，正常解析域名后再执行启动函数；
2. 把启动脚本放在 /etc/hotplug.d/iface/ 里（不过需要用户选择监控哪个interface，比如可能是eth1，也可能是pppoe-wan）。

**Comment by hyird** [comment]
响应hotplug 不需要指定interface吧 只要接口状态变了 就会执行
