### ISSUE TITLE
游戏模式显示内核不支持

### ISSUE THREAD

**Issue by yoyi412** [Lienol/openwrt-package#42]
大佬，就是最新的图标这里，那个是有点问题哦，显示内核不支持，那应该哪个版本才支持呢
![image](https://user-images.githubusercontent.com/43584510/69540947-ed728980-0fc2-11ea-91c5-6e40f5a37fe6.png)

![image](https://user-images.githubusercontent.com/43584510/69541010-14c95680-0fc3-11ea-922b-90b267f74add.png)

**Comment by Lienol** [comment]
N1？Docker？

**Comment by yoyi412** [comment]
> N1？Docker？
是的...我试了很多armbian版本都一样

**Comment by Lienol** [comment]
docker容器开特权模式了没？更新源码再试下。

**Comment by yoyi412** [comment]
> docker容器开特权模式了没？更新源码再试下。

是特权模式创建容器的

**Comment by Lienol** [comment]
> > docker容器开特权模式了没？更新源码再试下。
> 
> 是特权模式创建容器的

更新再试试，不要保留passwall配置升级
