### ISSUE TITLE
luci-app-passwall运行状态报错 请教一下是怎么处理

### ISSUE THREAD

**Issue by hubbylei** [Lienol/openwrt-package#421]
最新源码编译
Sat Apr 11 01:19:51 2020 daemon.err uhttpd[1955]: /usr/lib/lua/luci/dispatcher.lua:381: Failed to execute call dispatcher target for entry '/admin/vpn/passwall/status'.
Sat Apr 11 01:19:51 2020 daemon.err uhttpd[1955]: The called action terminated with an exception:
Sat Apr 11 01:19:51 2020 daemon.err uhttpd[1955]: /usr/lib/lua/luci/controller/passwall.lua:155: 'for' limit must be a number
Sat Apr 11 01:19:51 2020 daemon.err uhttpd[1955]: stack traceback:
Sat Apr 11 01:19:51 2020 daemon.err uhttpd[1955]: 	[C]: in function 'assert'
Sat Apr 11 01:19:51 2020 daemon.err uhttpd[1955]: 	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
Sat Apr 11 01:19:51 2020 daemon.err uhttpd[1955]: 	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>
Sat Apr 11 01:19:56 2020 daemon.err uhttpd[1955]: /usr/lib/lua/luci/dispatcher.lua:381: Failed to execute call dispatcher target for entry '/admin/vpn/passwall/status'.
Sat Apr 11 01:19:56 2020 daemon.err uhttpd[1955]: The called action terminated with an exception:
Sat Apr 11 01:19:56 2020 daemon.err uhttpd[1955]: /usr/lib/lua/luci/controller/passwall.lua:155: 'for' limit must be a number
Sat Apr 11 01:19:56 2020 daemon.err uhttpd[1955]: stack traceback:
Sat Apr 11 01:19:56 2020 daemon.err uhttpd[1955]: 	[C]: in function 'assert'
Sat Apr 11 01:19:56 2020 daemon.err uhttpd[1955]: 	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
Sat Apr 11 01:19:56 2020 daemon.err uhttpd[1955]: 	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by Lienol** [comment]
不要保留配置

**Comment by hubbylei** [comment]
好的 我试试

**Comment by hubbylei** [comment]
完美解决 麻烦了 谢谢
