### ISSUE TITLE
test.sh中的test_url在不支持ipv6的机器上报错

### ISSUE THREAD

**Issue by edjia** [Lienol/openwrt-package#424]
第一次用这个，不对的地方请指出。
平台：x86
故障现象：passwall主界面测试百度和google直接失败，即使网络全部都正常。
刚才看了下，应该是我编译时候没有选择ipv6支持引起的，导致wget不支持4.3更新新增的-4参数。

**Comment by Lienol** [comment]
更新源码再试试

**Comment by edjia** [comment]
试过好了，真快！
