### ISSUE TITLE
问题反馈：更新到最新之后状态显示异常

### ISSUE THREAD

**Issue by tony27786** [Lienol/openwrt-package#427]
之前没有出现过问题，更新了3.6-40之后出现的
开启插件后不显示运行状态
![image](https://user-images.githubusercontent.com/47511820/79060561-19b04d80-7cb9-11ea-82c7-a87dcd5647a8.png)
但是网络访问正常的，希望大佬处理一下！

**Comment by Lienol** [comment]
进入 高级设置保存一下
还不行就直接用passwall内置的恢复出厂设置功能重新配置

**Comment by tony27786** [comment]
高级设置保存解决了，谢谢大佬！
