### ISSUE TITLE
运行状态不显示？

### ISSUE THREAD

**Issue by bigbighill** [Lienol/openwrt-package#428]
passwall 3.6-40 配合大雕源码，运行状态不显示。
![IMG_20200412_232443](https://user-images.githubusercontent.com/26495337/79072876-0384aa80-7d16-11ea-8232-a52eb5d691d1.jpg)
![IMG_20200412_233148](https://user-images.githubusercontent.com/26495337/79072883-097a8b80-7d16-11ea-83db-f4cae65dcf6d.jpg)

**Comment by Lienol** [comment]
提问题前能否看看 其他已解决issue？

**Comment by Lienol** [comment]
https://github.com/Lienol/openwrt-package/issues/427

**Comment by ChiHoc** [comment]
一样的问题。只用了trojan结点，发现会不停启动trojan进程，时间长了大量启动进程。
经调查是我自己安装了完整版ps的原因。
修改app.sh，monitor.sh和passwall.lua文件，把ps -w改为ps -fea解决问题。
