### ISSUE TITLE
请问怎样单独编译luci-app-passwall

### ISSUE THREAD

**Issue by dengchan0416** [Lienol/openwrt-package#43]
不想整个固件升级,想只升级passwall,每次编译都出错
[http://chuantu.xyz/t6/703/1574782535x992245926.png](url)

**Comment by dengchan0416** [comment]
> 不想整个固件升级,想只升级passwall,每次编译都出错
> 
> den@ubuntu:~/lede$ make feeds/lienol/lienol/luci-app-passwall/compile V=s time: target/linux/prereq#0.04#0.01#0.12 make[1]: Entering directory `/home/den/lede' make[1]: *** No rule to make target `feeds/lienol/lienol/luci-app-passwall/compile'. Stop. make[1]: Leaving directory `/home/den/lede' make: *** [feeds/lienol/lienol/luci-app-passwall/compile] 错误 2 den@ubuntu:~/lede$ ^C den@ubuntu:~/lede$ make package/lean/luci-app-passwall/compile V=s Collecting package info: done make[1]: Entering directory `/home/den/lede' make[1]: *** No rule to make target `package/lean/luci-app-passwall/compile'. Stop. make[1]: Leaving directory `/home/den/lede' make: *** [package/lean/luci-app-passwall/compile] 错误 2 den@ubuntu:~/lede$

**Comment by Lienol** [comment]
make menuconfig，选好passwall要编译的东西，保存后
make package/feeds/lienol/lienol/luci-app-passwall/compile -j1 V=s

**Comment by dengchan0416** [comment]
> make menuconfig，选好passwall要编译的东西，保存后
> make package/feeds/lienol/lienol/luci-app-passwall/compile -j1 V=s

按你的方法出现以下错误
[![QewJ2t.md.png](https://s2.ax1x.com/2019/12/01/QewJ2t.md.png)](https://imgse.com/i/QewJ2t)

**Comment by aiden-5154** [comment]
你先完整编译一次吧，直接编译插件不会编译toolchain之类的

**Comment by Lienol** [comment]
@dengchan0416  @aiden-5154  正解
