### ISSUE TITLE
openwrt new version not running success

### ISSUE THREAD

**Issue by buxiaomo** [Lienol/openwrt-package#434]
![1586917321630](https://user-images.githubusercontent.com/24752547/79292147-fbd62900-7f02-11ea-9540-8509c367930e.jpg)

**Comment by Lienol** [comment]
This is use the luci latest problem. Need to add ACL file.

**Comment by buxiaomo** [comment]
do you have document, thanks.

**Comment by Lienol** [comment]
https://github.com/openwrt/luci/commit/c35cb317fe6a5d42e3c7294e02fac65c50ef3f3c

**Comment by buxiaomo** [comment]
create this file `/usr/share/rpcd/acl.d/luci-app-passwall.json`

```
{
 	"luci-app-passwall": {
 		"description": "Grant UCI access for luci-app-passwall",
 		"read": {
 			"uci": [ "passwall" ]
 		},
 		"write": {
 			"uci": [ "passwall" ]
 		}
 	}
}
```

thanks
