### ISSUE TITLE
luci-app-ssr-mudb-server的配置文件能否保存到/etc/config下方便升级保留配置

### ISSUE THREAD

**Issue by xxp2277** [Lienol/openwrt-package#452]
不是指/etc/config/ssr_mudb_server，而是指/usr/share/ssr_mudb_server/mudb.json。能否考虑将这两个配置文件合并在一起？
同时由于/usr/share/ssr_mudb_server/mudb.json文件不在默认的备份配置列表中，备份配置也无法备份这个文件。
强烈建议转移位置到/etc/config路径下。

**Comment by Lienol** [comment]
try to update the latest source code and then test it.

**Comment by xxp2277** [comment]
感谢作者辛苦弄代码。
