### ISSUE TITLE
新版可道云配置WebDAV插件提示缺少PATH_INFO模式，不知能否加上

### ISSUE THREAD

**Issue by EnnawYang** [Lienol/openwrt-package#453]
配置WebDAV插件提示不支持PATH_INFO模式，用lean版编译的，那边我也提了issue，保留一个，https://github.com/coolsnowwolf/lede/issues/4813

![Snipaste_2020-06-14_20-16-34](https://user-images.githubusercontent.com/6705663/84592975-f900a180-ae7b-11ea-9079-40e10eed2a90.png)

**Comment by Lienol** [comment]
try to update the latest source code and then test it.

**Comment by EnnawYang** [comment]
![Snipaste_2020-06-14_22-35-22](https://user-images.githubusercontent.com/6705663/84596337-ab8e2f80-ae8f-11ea-9ce9-0918bc3bbd65.png)
![Snipaste_2020-06-14_22-35-37](https://user-images.githubusercontent.com/6705663/84596339-acbf5c80-ae8f-11ea-8b83-6ea92e676793.png)
![Snipaste_2020-06-14_22-48-46](https://user-images.githubusercontent.com/6705663/84596602-4e937900-ae91-11ea-8ede-3a83a8200968.png)

OK了，谢谢dalao~ 不过测试好像有上传限制，https://doc.kodcloud.com/#/others/options ，可能是还需要一些配置？ （

**Comment by Lienol** [comment]
Fix.

**Comment by dache123** [comment]
现在好了吗？支持PATH_INFO了吗  我编译路由器的没找到选项，该在哪里打开？

**Comment by EnnawYang** [comment]
> 现在好了吗？支持PATH_INFO了吗 我编译路由器的没找到选项，该在哪里打开？

不是早就修复了？
