### ISSUE TITLE
编译MR8300失败

### ISSUE THREAD

**Issue by zow2023** [Lienol/openwrt-package#46]
大佬 你好  我用你的源码21.02和22.03 **编译MR8300的固件，都失败了。截图是今天用22.03编译过程其中一段过程的截图。还望指教。
 
![FireShot Capture 003 - Build OpenWrt · zow2023_lienol-code@1e93020 - github com](https://github.com/Lienol/openwrt-package/assets/125123077/4a6ae052-ed49-4dd9-9d4e-d0700f8cd7d7)

**Comment by lxhao61** [comment]
编译斐讯 K3 固件一样问题。不仅源码 21.02 和 22.03，还有源码 23.05 一样出错。
另外除源码 master 外都需要升级 Go 以适应 Xray（v1.8.4 ） 编译环境要求。
最后源码 master 的 shortcut-fe 插件编译出错，取消后无问题。

**Comment by zow2023** [comment]
> 编译斐讯 K3 固件一样问题。不仅源码 21.02 和 22.03，还有源码 23.05 一样出错。 另外除源码 master 外都需要升级 Go 以适应 Xray（v1.8.4 ） 编译环境要求。 最后源码 master 的 shortcut-fe 插件编译出错，取消后无问题。

昨天有又编译了一次  这次好像不是GO的缘故了  [麻烦你帮我看一下什么原因
![Screenshot 2023-10-16 at 09-24-51 Build OpenWrt · zow2023_lienol-code@e27b4a6](https://github.com/Lienol/openwrt-package/assets/125123077/824d2376-ba80-45c9-93dc-6ccb2643b14b)

**Comment by zow2023** [comment]
软件源里的版本是1.8.4的，怎么编译日志里面显示的是1.8.3的呢？

**Comment by lxhao61** [comment]
> > 编译斐讯 K3 固件一样问题。不仅源码 21.02 和 22.03，还有源码 23.05 一样出错。 另外除源码 master 外都需要升级 Go 以适应 Xray（v1.8.4 ） 编译环境要求。 最后源码 master 的 shortcut-fe 插件编译出错，取消后无问题。
> 
> 昨天有又编译了一次 这次好像不是GO的缘故了 [麻烦你帮我看一下什么原因 ![Screenshot 2023-10-16 at 09-24-51 Build OpenWrt · zow2023_lienol-code@e27b4a6](https://user-images.githubusercontent.com/125123077/275375324-824d2376-ba80-45c9-93dc-6ccb2643b14b.png)

本来就不是GO的缘故，我仅知道不知道怎么解决。

**Comment by lxhao61** [comment]
> 软件源里的版本是1.8.4的，怎么编译日志里面显示的是1.8.3的呢？

Lienol 大系统源自带 Xray 且版本 1.8.3 没有更新，需要删除自带 Xray 才能编译软件源的版本。

**Comment by zow2023** [comment]
> > 软件源里的版本是1.8.4的，怎么编译日志里面显示的是1.8.3的呢？
> 
> Lienol 大系统源自带 Xray 且版本 1.8.3 没有更新，需要删除自带 Xray 或覆盖才能编译软件源的版本。

感谢回复
