### ISSUE TITLE
新版3.0-113-20191129 SSR订阅问题

### ISSUE THREAD

**Issue by dengchan0416** [Lienol/openwrt-package#47]
用最新版SSR订阅之后节点备注出现错位现像,
[![QeNEXF.md.png](https://s2.ax1x.com/2019/12/01/QeNEXF.md.png)](https://imgse.com/i/QeNEXF)
[![QeaHYR.md.png](https://s2.ax1x.com/2019/12/01/QeaHYR.md.png)](https://imgse.com/i/QeaHYR)
[![QeU6xK.md.png](https://s2.ax1x.com/2019/12/01/QeU6xK.md.png)](https://imgse.com/i/QeU6xK)
在SSR+订阅之后能正常显示节点名称,
[![QeatJI.md.png](https://s2.ax1x.com/2019/12/01/QeatJI.md.png)](https://imgse.com/i/QeatJI)

**Comment by Lienol** [comment]
已修复
