### ISSUE TITLE
你好，我在使用PASSWALL时遇到了一些问题。

### ISSUE THREAD

**Issue by smartwood777** [Lienol/openwrt-package#470]
我目前安装了3.9-4,之前用的是3.6-40这2个版本。都遇到同样一个问题：在访问控制里添加域名白名单时无效。
我已经反复试验过了，这个问题确实不是我这边的故障，而且我在TG群里也遇到了其他群友有这个困扰。
还有一个问题，3.9-4里似乎去掉了原来，奈飞油管的分流模式，如果有问题，还希望完善后可以添加回来。
                                                                                                                                                  此致敬礼！

**Comment by lllrrr** [comment]
添加后，要重启一下

**Comment by hyird** [comment]
dns缓存清除了没有
