### ISSUE TITLE
passwall设置问题

### ISSUE THREAD

**Issue by dengchan0416** [Lienol/openwrt-package#48]
开启SmartDNS之后,passwall要怎样设置,是不是如图那样,地址转发模式那里,只能是7913
[![Qm2Rxg.md.png](https://s2.ax1x.com/2019/12/01/Qm2Rxg.md.png)](https://imgse.com/i/Qm2Rxg)
高级设置那里,地址转发填:192.168.1.1:7913
[![Qm2BqA.md.png](https://s2.ax1x.com/2019/12/01/Qm2BqA.md.png)](https://imgse.com/i/Qm2BqA)
[![Qm2bGT.md.png](https://s2.ax1x.com/2019/12/01/Qm2bGT.md.png)](https://imgse.com/i/Qm2bGT)
[![Qm2XM4.md.png](https://s2.ax1x.com/2019/12/01/Qm2XM4.md.png)](https://imgse.com/i/Qm2XM4)
请问这样设置对吗

**Comment by Lienol** [comment]
只需设置使用7913端口模式，高级设置里面的DNS转发地址不用改
