### ISSUE TITLE
非常欢迎passwall回归，但目前版本无法通过链接或订阅添加节点，手工添加正常。

### ISSUE THREAD

**Issue by gswangmd-gssi** [Lienol/openwrt-package#486]

**Comment by RUI98** [comment]
我没有问题

**Comment by gswangmd-gssi** [comment]
![批注 2020-07-11 091139](https://user-images.githubusercontent.com/59297839/87213368-1af42380-c357-11ea-9746-61c946c0bffa.png)

**Comment by peter-tank** [comment]
看来你uci库兼容性不太好，试试下面的指令看是不是能复现 string expected, got boolean
```shell
ubus call uci add '{"config": "passwall", "type": "nodes", "name": "cfg123456"}'
ubus call uci set '{"config": "passwall", "section": "cfg123456", "values": {"test": true}}'
ubus call uci set '{"config": "passwall", "section": "cfg123456", "values": {"test": "0"}}'
ubus call uci changes

**Comment by gswangmd-gssi** [comment]
刚试了一下指令，故障依旧。

**Comment by peter-tank** [comment]
看下显示结果

**Comment by gswangmd-gssi** [comment]
![批注 2020-07-11 115354](https://user-images.githubusercontent.com/59297839/87215898-5b5e9c00-c36d-11ea-99e2-53a7873a09d1.png)

**Comment by peter-tank** [comment]
我是说运行上面指令的回显是些什么

**Comment by gswangmd-gssi** [comment]
![批注 2020-07-11 120041](https://user-images.githubusercontent.com/59297839/87216020-361e5d80-c36e-11ea-8c62-06d052a8eae4.png)

**Comment by peter-tank** [comment]
不懂了，还是试着修一下吧。(#488)

**Comment by peter-tank** [comment]
试下临时的简单方案：
```shell
sed -i 's/\(result.* = allowInsecure_default\)$/\1 and "1" or "0"/' /usr/share/passwall/subscribe.lua
```

**Comment by gswangmd-gssi** [comment]
试用临时方案后，成功解析！

**Comment by peter-tank** [comment]
那还剩下 Trojan-Go 的订阅会有同样的问题。

**Comment by gswangmd-gssi** [comment]
期待修复好！

**Comment by peter-tank** [comment]
这bug可以报到你openwrt/uci上游源去
打我提交的完整补丁可以修复。
