### ISSUE TITLE
Passwall订阅节点或者更新规则都是执行两次

### ISSUE THREAD

**Issue by king1393** [Lienol/openwrt-package#491]
Passwall订阅节点或者更新规则都是执行两次,这样导致订阅的节点明明50个变100个了，日志里动作都是这么显示的
![捕获2](https://user-images.githubusercontent.com/32534889/87228500-3bae8e80-c3d4-11ea-80d5-b7365018a589.PNG)
![捕获](https://user-images.githubusercontent.com/32534889/87228243-7d3e3a00-c3d2-11ea-923e-6c6b7ba996ec.PNG)

**Comment by Lienol** [comment]
你用的应该不是我的openwrt源码

**Comment by king1393** [comment]
> 你用的应该不是我的openwrt原始码
大佬就是用的你电报群的呀

**Comment by king1393** [comment]
> 你用的应该不是我的openwrt源码

就是用的你固件频道发的，10号的固件 重新刷了好几次都这样我也不知道怎么回事了

**Comment by king1393** [comment]
> 你用的应该不是我的openwrt源码

![捕获](https://user-images.githubusercontent.com/32534889/87311670-21022400-c552-11ea-80ab-79cc8d219e73.PNG)
