### ISSUE TITLE
trojan-Go版本更新失败！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#492]
![image](https://user-images.githubusercontent.com/45259624/87237888-2ebe8900-c42e-11ea-8b4a-aeffbd58dc4a.png)

**Comment by peter-tank** [comment]
故意的，防止无脑更新，看增加的提示信息。
实际上[官方](https://github.com/p4gefau1t/trojan-go)还未开始正式发布变动有点大。官方v0.8.x(websocket)配置跟以前不兼容。v0.7.8~v0.8.0 客户端功能没有太大变化，没发现有问题则无需更新。

也可先点保存，会从[我编译的版本](https://github.com/peter-tank/trojan-go)检查更新。`vx.x.x-cli` 只包含客户端功能并用 UPX 进行了压縮。

**Comment by wangfeng35** [comment]
> `x.x.x-cli` 只是在我 `vx.x.`

感谢解答 谢谢

**Comment by zxlhhyccc** [comment]
> 故意的，防止无脑更新，看增加的提示信息。
> 实际上[官方](https://github.com/p4gefau1t/trojan-go)还未开始正式发布，变动可能还有点大。官方v0.8.x(websocket)配置跟以前不兼容。v0.7.8~v0.8.0 客户端功能没有太大变化，没发现有问题则无需更新。
> 
> 也可先点保存，会从[我编译的版本](https://github.com/peter-tank/trojan-go)检查更新。`vx.x.x-cli` 只是在我 `vx.x.x` 的基础上重新编译，只包含客户端功能并用 UPX 进行了压縮。

按照你的教程保存后再点击更新仍失败，不会下载。。。

**Comment by peter-tank** [comment]
到底是检测不到新版本还是下载失败？总该不会是提示：＂不会下载＂吧。
如果正在使用，好像需要先关闭。
你试一下检查其它软件的更新，看可不可以通过新版本检查。

**Comment by Fujiazld521** [comment]
我的0.78都没有，不知道怎么添加上
