### ISSUE TITLE
更新到最新后，github检测连接失败！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Lienol/openwrt-package#496]
![image](https://user-images.githubusercontent.com/45259624/87255836-bce34f80-c4c0-11ea-9f1b-ee2ba32d83ed.png)

**Comment by Lienol** [comment]
没有动过这一块

**Comment by zxlhhyccc** [comment]
> 没有动过这一块

软路由上github检测正常，K3上检测失败。。。。

**Comment by zxlhhyccc** [comment]
> 没有动过这一块

大佬，已找到问题的原因，是我加了额外的内核补丁导致的。。。去掉就正常了。。。。

**Comment by CORE2021** [comment]
你在群里说sfe？L大源代码编译无此问题
