### ISSUE TITLE
ipsec 问题

### ISSUE THREAD

**Issue by ksong008** [Lienol/openwrt-package#5]
ipsec server 开启，手机等设备在外网连接后，只有tg工作正常，其他油管等app无法连接以及浏览器无法打开网页，请问是不是规则上的问题

**Comment by lxhao61** [comment]
使用luci-app-ipsec-server一样问题。而lean大luci-app-ipsec-vpnd采用ipsec0虚拟接口地址解决了这个问题，希望有大神来解决。毕竟luci-app-ipsec-server支持多用户与L2TP，这个相比luci-app-ipsec-vpnd优势。

**Comment by Lienol** [comment]
为什么我可以直接用?无法复现...

**Comment by Lienol** [comment]
算了,我晚点试试加那个虚拟接口...

**Comment by Lienol** [comment]
可以的话，试试最新源码反馈一下？

**Comment by lxhao61** [comment]
> 可以的话，试试最新源码反馈一下？

好的。正在编译固件，完成后测试。

**Comment by lxhao61** [comment]
> 可以的话，试试最新源码反馈一下？

昨晚源码编译的固件经过一天测试，反馈如下：
1、需要加入依赖包 kmod-tun，否则接口总览中IPSEC_SERVER（ipsec0）接口状态无法正常，进而影响IPSec无法使用。
2、基本达到了解决问题。
1）、IPSec解决问题完美，可以不考虑网段，默认配置即可。
2）、L2TP需要修改为路由器实际网关及分配路由器网段。
另外强迫症，希望config配置文件名luci-app-ipsec-server改为ipsec_server（与其它命名规则一致）。

**Comment by Lienol** [comment]
配置文件名加上luci-app是为了和官方package区别，也不影响。
另外我发现 kernel-libipsec 会导致无法连接L2TP/IPSec，所以最新源码做了点兼容。

**Comment by ksong008** [comment]
挖个坟，感谢大佬，现在版本完美，语言是否可以加上zh_Hans，方便官方master编译使用

**Comment by ksong008** [comment]
感谢修复，不过貌似有个小问题中文翻译ipse.po有问题

**Comment by liangchaofu** [comment]
l2tp黑名单会出现这个提醒
ipsec-server/online returns SimpleForm but is dispatched via cbi,
please change admin/services/ipsec-server/online to use the form()action instead

**Comment by ghost** [comment]
单网口出现虚拟网卡会跟lan口IP一致导致上不了网，更改后重启也会复现。手动更改虚拟网口地址，才能正常工作。怎么解决这个插件的自动更改问题
