### ISSUE TITLE
socat update

### ISSUE THREAD

**Issue by LuorixDev** [Lienol/openwrt-package#50]
Please update,thanks！
![image](https://github.com/Lienol/openwrt-package/assets/157946924/4074d145-88e9-450e-b4eb-da4fe4e81f35)
![image](https://github.com/Lienol/openwrt-package/assets/157946924/e0ddcd30-eaaa-4b0f-938a-4d6295e8c6c0)

**Comment by Lienol** [comment]
https://github.com/Lienol/openwrt-packages/commit/5a06e3471ba0a4a49130b22f936c823142680fe1
