### ISSUE TITLE
chinadns-ng加pdnsd，可信dns是smartdns，google测速连接失败

### ISSUE THREAD

**Issue by CORE2021** [Lienol/openwrt-package#500]
实际却可以访问

**Comment by Lienol** [comment]
Why add a PDNSD?

**Comment by Lienol** [comment]
Do not use repeatedly in meaningless to paraphrase DNS services

**Comment by Lienol** [comment]
Or use smartDNS instead of DNSMasQ to do ipset shunt instead of constantly adding upstream dns.

**Comment by Lienol** [comment]
In fact, using the default configuration, using PDNSD directly instead of Chinadns + PDNSD is the most stable.

**Comment by CORE2021** [comment]
如果用smartdns，那么chinadns应该选udp节点是嘛 感觉china比本机7913端口快耶
