### ISSUE TITLE
老问题还在

### ISSUE THREAD

**Issue by raiders168** [Lienol/openwrt-package#501]
![image](https://user-images.githubusercontent.com/59355325/87395579-2d36c180-c5e4-11ea-8498-327b0fc16e38.png)

**Comment by Lienol** [comment]
https://github.com/Lienol/openwrt-package/issues/492#issuecomment-657242115

**Comment by raiders168** [comment]
收到，明白了

Lienol <notifications@github.com> 于2020年7月14日周二 下午3:41写道：
