### ISSUE TITLE
请问大佬的插件在openwrt官方或者Lean-lede都可以正常编译吗？

### ISSUE THREAD

**Issue by lyafancn** [Lienol/openwrt-package#51]
如果官方openwrt可以，那我就用官方的了。

**Comment by Lienol** [comment]
可以

**Comment by lyafancn** [comment]
> 可以

那Lean的可以吗？我发现官方的Op很多东西都没给默认 勾选。。我刚才编译失败了。。我想用Lean的源码加上您的Luci的PASSWALL。可行吧？
