### ISSUE TITLE
请教一下各位，用lienol的22.03的源,编译的E8450的固件，打开接口的DHCP/DNS选项报错

### ISSUE THREAD

**Issue by zow2023** [Lienol/openwrt-package#51]
接口选项下的DHCP/DNS报错（命令如下）：
ReferenceError
Associated tab not declared
  at ClassConstructor.taboption (http://10.0.0.1/luci-static/resources/form.js?v=git-536590c:74:9)
  at ClassConstructor.render (http://10.0.0.1/luci-static/resources/view/network/dhcp.js?v=git-536590c:63:1056)
有解决办法吗？

**Comment by lxhao61** [comment]
从现在开始倒数第二次同步官方源（Merge branch 'openwrt-22.03' of https://github.com/openwrt/luci into 22.03）引入的 BUG，现在大佬已经不手工维护了，一些问题也一直没有解决；我目前解决办法是回退到第三次同步官方源解决。方法如下：
#注释默认 luci
sed -i 's/^\(.*luci\)/#&/' feeds.conf.default
#添加回退 luci
sed -i '$a src-git luci https://github.com/Lienol/openwrt-luci.git^db0ddd1' feeds.conf.default

**Comment by zow2023** [comment]
感谢你的指教

**Comment by lxhao61** [comment]
> 感谢你的指教

最新更新解决这个 BUG，但产生了一个另外小问题；虽然不影响使用，多出如下条目：
删除及CFG01411C
