### ISSUE TITLE
V2ray/Trojan服务器端无法运行成功

### ISSUE THREAD

**Issue by imace3** [Lienol/openwrt-package#521]
2020.07.18的passwall，Trojan服务器一直无法运行成功，自从日更恢复后，Trojan服务器用原来的证书，都无法运行成功。

**Comment by Lienol** [comment]
Try to update the latest source code

**Comment by imace3** [comment]
问题依旧存在。无法生成配置文件运行。

二次加密，取消后，无法保存。

<img width="1003" alt="截屏2020-07-19 下午11 33 42" src="https://user-images.githubusercontent.com/20973219/87878706-72118c80-ca18-11ea-87c5-5c1a7dec8763.png">

**Comment by Lienol** [comment]
事实上，trojan-go服务端并没有实现

**Comment by imace3** [comment]
Trojan-plus服务端也无法运行。

在恢复日更前，Trojan服务器未整合至passwall里之前，配合ssl证书是能正常运行。

**Comment by lxhao61** [comment]
估计是Trojan源替换Trojan-plus源问题造成的。建议还原Trojan源，或者全部替换及修改为Trojan-plus（名称与源完全一致）！

**Comment by imace3** [comment]
07.20今天更新的版本，终于解决了trojan-plus服务端的问题，可以正常运行了。但是Trojan-go的服务端还不行。

**Comment by Lienol** [comment]
> 07.20今天更新的版本，终于解决了trojan-plus服务端的问题，可以正常运行了。但是Trojan-go的服务端还不行。

Trojan-Go没有实现呢
