### ISSUE TITLE
passwall是否可以检测节点是否有效？

### ISSUE THREAD

**Issue by tjlive** [Lienol/openwrt-package#526]
节点列表使用tcp检测延迟，不能确认这个节点是否能正常使用，只能一个一个节点尝试。

在ssr plus中就有这样的功能“连接测试”。

**Comment by Lienol** [comment]
可以做，很容易，懒得做

**Comment by viagram** [comment]
> 可以做，很容易，懒得做

两会之前内测中的新版wall呢？

**Comment by CoolCollin** [comment]
我也觉得有必要做一个真实链接测试，只是tcpping对于中转机来说，就没有用了。

**Comment by han3sui** [comment]
我觉得这个功能非常有必要

**Comment by hcym** [comment]
感觉haproxy的chk状态比较有用，我看那个计数值太大就迁移户口。最近还是比较稳定了
