### ISSUE TITLE
是否能制作一个深色的Bootstrap主题？

### ISSUE THREAD

**Issue by People-11** [Lienol/openwrt-package#529]
因为白色的背景真的亮瞎眼，所以是否能制作一个深色的Bootstrap主题？

**Comment by OPnb** [comment]
以前Li哥想做过，后来好像是中途源码丢了，就半途放弃了...

**Comment by Lienol** [comment]
没开源

**Comment by OPnb** [comment]
> 
> 
> 没开源

十分想要，不开源，能发个IPK也行 /(ㄒoㄒ)/~~

**Comment by chuansao-258** [comment]
浏览器装个darkreader不会？
