### ISSUE TITLE
DNS设置好像出问题了，只能设置为默认，其他任何选项全部联网失败

### ISSUE THREAD

**Issue by db-one** [Lienol/openwrt-package#530]
![image](https://user-images.githubusercontent.com/20243226/88002199-877bd900-cb34-11ea-9cf6-6a275ae1da8f.png)
![image](https://user-images.githubusercontent.com/20243226/88002245-a5e1d480-cb34-11ea-952c-2f0e2e41290c.png)
![image](https://user-images.githubusercontent.com/20243226/88002458-2a345780-cb35-11ea-9f28-79eb53e89291.png)

DNS设置好像出问题了，只能设置为默认或者运营商DNS，其他任何选项   阿里或者腾讯  或者自定义的DNS都会导致国内国外全不断网，只有默认DNS正常，上一个版本我是5天前编译的，还是正常的，今天编译更新系统之后就打不开，然后还把PASSWALL重置了设置了几次才发现这个问题

**Comment by Lienol** [comment]
@peter-tank

**Comment by peter-tank** [comment]
log 什么样子？

**Comment by db-one** [comment]
> log 什么样子？

2020-07-21 12:19:05: 清空并关闭相关程序和缓存完成。
2020-07-21 12:19:05: Socks节点：负载均衡，地址：127.0.0.1:1181，监听端口：1080
2020-07-21 12:19:05: TCP_1节点：负载均衡，节点：127.0.0.1:1181，监听端口：1041
2020-07-21 12:19:06: 配置 pdnsd 的上游DNS[8.8.4.4:53]
2020-07-21 12:19:06: DNS：pdnsd + 使用TCP节点解析DNS...
2020-07-21 12:19:06: dnsmasq：生成配置文件。
2020-07-21 12:19:06: 开始加载防火墙规则...
2020-07-21 12:19:07: 开始过滤所有节点到白名单
2020-07-21 12:19:07: 过滤所有节点完成
2020-07-21 12:19:08: TCP默认代理模式：GFW名单
2020-07-21 12:19:08: UDP默认代理模式：大陆白名单
2020-07-21 12:19:08: 防火墙规则加载完成！
2020-07-21 12:19:11: 配置定时任务：自动更新规则。
2020-07-21 12:19:11: 运行完成！


LOG跟正常的一样的

系统日志就只有这一段，之前的都是11点多的日志 跟设置没关系

Tue Jul 21 12:19:01 2020 daemon.err uhttpd[2858]: netstat: showing only processes with your user ID
Tue Jul 21 12:19:02 2020 cron.err crond[19354]: crond (busybox 1.31.1) started, log level 8
Tue Jul 21 12:19:02 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jul 21 12:19:02 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jul 21 12:19:05 2020 daemon.info dnsmasq[20520]: Connected to system UBus
Tue Jul 21 12:19:06 2020 daemon.info pdnsd[20894]: pdnsd-1.2.9b-par starting.
Tue Jul 21 12:19:08 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jul 21 12:19:08 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jul 21 12:19:11 2020 daemon.crit dnsmasq[21380]: bad address at line 1 of /tmp/dnsmasq.d/dnsmasq-passwall.conf
Tue Jul 21 12:19:11 2020 daemon.crit dnsmasq[21380]: FAILED to start up
Tue Jul 21 12:19:11 2020 cron.err crond[21446]: crond (busybox 1.31.1) started, log level 8
Tue Jul 21 12:19:16 2020 daemon.crit dnsmasq[21481]: bad address at line 1 of /tmp/dnsmasq.d/dnsmasq-passwall.conf
Tue Jul 21 12:19:16 2020 daemon.crit dnsmasq[21481]: FAILED to start up
Tue Jul 21 12:19:21 2020 daemon.crit dnsmasq[21501]: bad address at line 1 of /tmp/dnsmasq.d/dnsmasq-passwall.conf
Tue Jul 21 12:19:21 2020 daemon.crit dnsmasq[21501]: FAILED to start up
Tue Jul 21 12:19:26 2020 daemon.crit dnsmasq[21557]: bad address at line 1 of /tmp/dnsmasq.d/dnsmasq-passwall.conf
Tue Jul 21 12:19:26 2020 daemon.crit dnsmasq[21557]: FAILED to start up
Tue Jul 21 12:19:31 2020 daemon.crit dnsmasq[21577]: bad address at line 1 of /tmp/dnsmasq.d/dnsmasq-passwall.conf
Tue Jul 21 12:19:31 2020 daemon.crit dnsmasq[21577]: FAILED to start up
Tue Jul 21 12:19:36 2020 daemon.crit dnsmasq[21589]: bad address at line 1 of /tmp/dnsmasq.d/dnsmasq-passwall.conf
Tue Jul 21 12:19:36 2020 daemon.crit dnsmasq[21589]: FAILED to start up
Tue Jul 21 12:19:36 2020 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash
Tue Jul 21 12:21:00 2020 cron.err crond[23014]: crond (busybox 1.31.1) started, log level 8
Tue Jul 21 12:21:00 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jul 21 12:21:00 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jul 21 12:21:03 2020 daemon.info dnsmasq[23124]: Connected to system UBus
Tue Jul 21 12:21:04 2020 daemon.info pdnsd[23490]: pdnsd-1.2.9b-par starting.
Tue Jul 21 12:21:06 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Jul 21 12:21:06 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Jul 21 12:21:09 2020 daemon.info dnsmasq[23948]: Connected to system UBus
Tue Jul 21 12:21:09 2020 cron.err crond[24009]: crond (busybox 1.31.1) started, log level 8


这是我设置为阿里的DNS然后断网，之后有设置为默认DNS这段时间的日志，不知道对你有没有用

**Comment by db-one** [comment]
Tue Jul 21 12:19:31 2020 daemon.crit dnsmasq[21577]: bad address at line 1 of /tmp/dnsmasq.d/dnsmasq-passwall.conf
Tue Jul 21 12:19:31 2020 daemon.crit dnsmasq[21577]: FAILED to start up

难道是这里的问题？

**Comment by Lienol** [comment]
@peter-tank dnsmasq dns port should use # , rather than :

**Comment by jh0072110** [comment]
我也遇到这个问题啦

**Comment by peter-tank** [comment]
> Tue Jul 21 12:19:31 2020 daemon.crit dnsmasq[21577]: bad address at line 1 of /tmp/dnsmasq.d/dnsmasq-passwall.conf
> Tue Jul 21 12:19:31 2020 daemon.crit dnsmasq[21577]: FAILED to start up
> 
> 难道是这里的问题？

是，没重启所以没发现这问題
fix: https://github.com/Lienol/openwrt-package/pull/531

**Comment by peter-tank** [comment]
A quick fix for it:
```shell
app=/usr/share/passwall/app.sh
sed -i 's/"${2}:/"${2}#/g' $app
sed -i 's/\(DNS2SOCKS_FORWARD=.* 53\))$/\1 | sed '\''s\/#\/:\/g'\'')/' $app
```

**Comment by db-one** [comment]
> ```shell
> "${2}#
> ```

谢谢 搞定  不用重新编译了

**Comment by peter-tank** [comment]
又要来了，#536
```
app=/usr/share/passwall/app.sh
sed -i 's/ip = ${1};/ip = ${2};/' $app
```

**Comment by jh0072110** [comment]
好像还是有点点问题，按照原来的方式自定义dns（例如1.1.1.1,1.0.0.1）还是会出现连接失败…

**Comment by db-one** [comment]
> 好像还是有点点问题，按照原来的方式自定义dns（例如1.1.1.1,1.0.0.1）还是会出现连接失败…

我这边暂时正常了
我是直接执行@peter-tank 给的命令行
我还没重新编译

**Comment by peter-tank** [comment]
不应该吧，nslookup 查一下看，DNS是用的什么模式？passwall 本身 log应该就能看出来配置对了没有。

**Comment by jh0072110** [comment]
> 不应该吧，nslookup 查一下看，DNS是用的什么模式？passwall 本身 log应该就能看出来配置对了没有。

chinadns，以前这么设置都没问题来着，不在家，到家给大佬拉log

**Comment by jh0072110** [comment]
Wed Jul 22 19:37:25 2020 daemon.err uhttpd[3025]: netstat: showing only processes with your user ID
Wed Jul 22 19:37:25 2020 cron.err crond[32700]: crond (busybox 1.31.1) started, log level 8
Wed Jul 22 19:37:25 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Jul 22 19:37:25 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Jul 22 19:37:28 2020 daemon.info dnsmasq[346]: Connected to system UBus
Wed Jul 22 19:37:28 2020 daemon.info pdnsd[559]: pdnsd-1.2.9b-par starting.
Wed Jul 22 19:37:28 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Jul 22 19:37:28 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Jul 22 19:37:31 2020 daemon.info dnsmasq[930]: Connected to system UBus
Wed Jul 22 19:37:31 2020 cron.err crond[994]: crond (busybox 1.31.1) started, log level 8

![image](https://user-images.githubusercontent.com/50496854/88172328-62ca5300-cc53-11ea-85b6-814b9f0ccc6a.png)


> 不应该吧，nslookup 查一下看，DNS是用的什么模式？passwall 本身 log应该就能看出来配置对了没有。

**Comment by peter-tank** [comment]
我不能复现，你试下加个开启二次请求的参数：https://github.com/AlexZhuo/luci-app-pdnsd/blob/master/files/etc/pdnsd_gfw.cfg
```shell
app=/usr/share/passwall/app.sh
sed -e '/status_ctl/ {' -e 'n;i\\t\t\tparanoid = on;' -e '}' $app
grep -C3 status_ctl $app
```
重启后测试下解析：
```
nslookup twitter.com 127.0.0.1#7914
```

**Comment by jh0072110** [comment]
> 我不能复现，你试下加个开启二次请求的参数：https://github.com/AlexZhuo/luci-app-pdnsd/blob/master/files/etc/pdnsd_gfw.cfg
> 
> ```shell
> app=/usr/share/passwall/app.sh
> sed -e '/status_ctl/ {' -e 'n;i\\t\t\tparanoid = on;' -e '}' $app
> grep -C3 status_ctl $app
> ```
> 
> 重启后测试下解析：
> 
> ```
> nslookup twitter.com 127.0.0.1#7914
> ```

我用最新版本重新编译一下先试试

**Comment by jh0072110** [comment]
重新编译问题依旧，我知道问题出在哪里了，如Lienol大所说，在chinadns模式自定义dns，还是默认用":"而不是用"#"来标注port，所以会导致自定义dns失效（应该是这样……吧）大佬也许只改了国内，忘记改国外了？

**Comment by peter-tank** [comment]
你理解得不对，chinadns 那个已经修了。
你这种配置方式是由 chinadns-ng 来区分国内外域名的查询，国外固定是127.0.0.1#7914(也就是pdnsd的监听端口)
国内：dnsmasq -> chinadns(7913) -> 国内DNS(223.5.5.5)
国外：dnsmasq -> chinadns(7913) -> pdnsd(7914) -> 1.0.0.1,1.1.1.1

**Comment by jh0072110** [comment]
> 你理解得不对，chinadns 那个已经修了。
> 你这种配置方式是由 chinadns-ng 来区分国内外域名的查询，国外固定是127.0.0.1#7914(也就是pdnsd的监听端口)
> 国内：dnsmasq -> chinadns(7913) -> 国内DNS(223.5.5.5)
> 国外：dnsmasq -> chinadns(7913) -> pdnsd(7914) -> tcp_proxy(代理) -> 1.0.0.1,1.1.1.1
> 
> 也许你代理服务器那边不支持 cloudflare 的 DNS 解析了？

Sorry大佬我也许太过小白，我就是从日志的体现去分析了一下，全部设置自定义DNS的情况下是这样的一个效果……

**Comment by peter-tank** [comment]
要不换成8.8.8.8和8.8.4.4看看？

**Comment by jh0072110** [comment]
> 要不换成8.8.8.8和8.8.4.4看看？

尴尬，看来是四个一的问题，耽误大佬休息了…

**Comment by peter-tank** [comment]
是有服务器开始屏蔽cloudflare的公用DNS...

**Comment by jh0072110** [comment]
> 是有服务器开始屏蔽cloudflare的公用DNS...

感觉还是有点问题…我尝试了几个DNS，只有四个八是好用的，quad9和nextdns也阵亡了…不过不是什么大问题，大佬好好休息完事再说吧……

**Comment by peter-tank** [comment]
也许是应该开启一下2服务器的并发查询，明天发pr
可以先试试：
```shell
app=/usr/share/passwall/app.sh
sed -e 's/par_queries = .*$/par_queries = 2;/' $app
```

**Comment by peter-tank** [comment]
这下应该算是修完了 😁 

ipt=/usr/share/passwall/iptables.sh
sed -i 's/\(.*2.*\)&& return 0/\1|| return 0/g' $ipt
