### ISSUE TITLE
使用passwall出现的问题

### ISSUE THREAD

**Issue by gswangmd-gssi** [Lienol/openwrt-package#534]
截图中第一组是使用passwal后l，在openwrt下执行nslookup的结果；第二组是使用SSR后，执行nslookup的结果。

![批注 2020-07-21 193707](https://user-images.githubusercontent.com/59297839/88050801-1c5cf180-cb8a-11ea-84e9-a6c352038618.png)

**Comment by gswangmd-gssi** [comment]
说明：以前版本版本未发现该问题。

**Comment by viagram** [comment]
今天已修复，重新编译固件。
