### ISSUE TITLE
Passwall使用的2个问题。

### ISSUE THREAD

**Issue by shmily103** [Lienol/openwrt-package#535]
1.节点列表中，勾选   使用TCP检测延迟 ，检测节点全部都是超时，不勾选就正常。（已安装tcping）
![2020-07-21 23-06-32 的屏幕截图](https://user-images.githubusercontent.com/4684786/88079795-c485b100-cbb0-11ea-954d-06b06ce67213.png)
![2020-07-21 23-07-17 的屏幕截图](https://user-images.githubusercontent.com/4684786/88079802-c780a180-cbb0-11ea-9af1-93fbc0d00b93.png)

2.节点订阅中， 手动订阅节点出错，详见日志，而且全局设置里 节点设置会变成关闭。
![2020-07-21 23-08-26 的屏幕截图](https://user-images.githubusercontent.com/4684786/88079829-cf404600-cbb0-11ea-96e2-c8eb3039d88e.png)
![2020-07-21 23-08-32 的屏幕截图](https://user-images.githubusercontent.com/4684786/88079837-d1a2a000-cbb0-11ea-80df-9836fac3d509.png)

**Comment by Lienol** [comment]
if you are using other source code compilation, error please solve yourself.
