### ISSUE TITLE
请在passwall上添加v2ray的mkcp新特性“seed”头部混淆密码

### ISSUE THREAD

**Issue by ymcoming** [Lienol/openwrt-package#538]
V2ary在v4.24.2后启用了一个mkcp的新特性："seed"头部混淆密码。

seed: string  ----可选项混淆密码， v4.24 后加入。可以使用 AES-128-GCM 算法混淆流量数据，客户端和服务器端需要保持一致。此设置可能可以对抗部分封锁。本混淆机制不能用于保证通信内容的安全。在开发者测试环境下开启此设置后没有出现原版未混淆版本的封端口状况。

我现在服务器上已经启用seed了，手机v2rayng上通过自定义配置文件，也能加上seed正常运行。就是路由端用passwall在v2ray-mkcp的参数里找不到设置seed的地方。

请增添这个新功能，谢谢！

**Comment by lxhao61** [comment]
支持！配置介绍链接如下：
https://www.v2fly.org/chapter_02/transport/mkcp.html

**Comment by Lienol** [comment]
The latest source code has supported.
