### ISSUE TITLE
make menuconfig 报错

### ISSUE THREAD

**Issue by SuLingGG** [Lienol/openwrt-package#54]
使用 Lean 的源码:

<https://github.com/coolsnowwolf/lede/tree/06d7b809a35c4463cf4591bd4dc078a1009a0516>

按本项目 README 文档添加 feeds 之后 update 并 install feeds 后，执行 `make menuconfig` 出现以下错误：

```
# admin @ 1470f5534bd4 in ~/workspace/lede on git:master x [22:38:28] 
$ make menuconfig
tmp/.config-package.in:76318:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:76318:   symbol PACKAGE_shadowsocks-libev-ss-local is selected by PACKAGE_shadowsocks-libev-ss-local
tmp/.config-package.in:76358:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:76358:   symbol PACKAGE_shadowsocks-libev-ss-redir is selected by PACKAGE_shadowsocks-libev-ss-redir
tmp/.config-package.in:79442:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:79442:   symbol PACKAGE_kcptun-client is selected by PACKAGE_kcptun-client
tmp/.config-package.in:76292:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:76292:   symbol PACKAGE_shadowsocks-libev-config is selected by PACKAGE_shadowsocks-libev-config
```

报错后尝试删除 `package/feeds/lienol` 文件夹，重新执行 `make menuconfig` 之后正常，无报错：

```
# admin @ 1470f5534bd4 in ~/workspace/lede/package/feeds on git:master x [22:53:50] C:1
$ rm -rf lienol 
# admin @ 1470f5534bd4 in ~/workspace/lede/package/feeds on git:master x [22:53:59] 
$ cd ...          
# admin @ 1470f5534bd4 in ~/workspace/lede on git:master x [22:54:02] 
$ make menuconfig
Collecting package info: doneing...
Your configuration changes were NOT saved.
```
以上在删除 `.config` 文件的情况下测试，所以应该不是 `.config` 的问题。

望修复~

**Comment by Lienol** [comment]
因为包重复冲突导致
如果用大雕源码，请做如下操作：
先添加 src-git lienol https://github.com/Lienol/openwrt-package 到 feeds.conf.default 文件
./scripts/feeds clean
./scripts/feeds update -a 
rm -rf feeds/lienol/lienol/v2ray
rm -rf feeds/lienol/lienol/openssl1.1
rm -rf feeds/lienol/lienol/trojan
rm -rf feeds/lienol/lienol/shadowsocks-libev-new
rm -rf feeds/lienol/lienol/shadowsocksr-libev
rm -rf feeds/lienol/lienol/pdnsd-alt
rm -rf package/lean/kcptun
rm -rf package/lean/verysync
rm -rf package/lean/luci-app-kodexplorer
rm -rf package/lean/luci-app-pppoe-relay
rm -rf package/lean/luci-app-pptp-server
rm -rf package/lean/luci-app-v2ray-server
rm -rf package/lean/luci-app-verysync
./scripts/feeds install -a
然后make menuconfig 编译

**Comment by SuLingGG** [comment]
这样操作的目的是把重复的一份包删掉吧，懂了~
（建议把这段话写在 README 里）

**Comment by caissonfiv** [comment]
可以编译两次 - - 先把大雕的$$R编译了，第二次再选择编译Passwall

**Comment by sunlanhao** [comment]
删掉重复的包之后有一些app 找不到了？ 比如 v2ray server ?

**Comment by jikuohong** [comment]
WARNING: Makefile 'package/lean/luci-app-passwall/Makefile' has a dependency on 'kcptun-client', which does not exist
WARNING: Makefile 'package/lean/luci-app-ssr-plus/Makefile' has a dependency on 'kcptun-client', which does not exist

按你上面的操作后。。。

**Comment by WinRose-C** [comment]
> WARNING: Makefile 'package/lean/luci-app-passwall/Makefile' has a dependency on 'kcptun-client', which does not exist
> WARNING: Makefile 'package/lean/luci-app-ssr-plus/Makefile' has a dependency on 'kcptun-client', which does not exist
> 
> 按你上面的操作后。。。

同样的报错

**Comment by pudding1111** [comment]
我添加 src-git lienol https://github.com/Lienol/openwrt-package 到 feeds.conf.default 文件后执行
./scripts/feeds clean出现Unable to open feeds configuration at ./scripts/feeds line 48.

**Comment by taoqixfz** [comment]
用lean的源码，在添加feeds.conf.default后make menuconfig里面luci-app里面没有smartdns

**Comment by youngjumped** [comment]
> 里面没有

lean大佬这两天从package里剔除了smartdns了 得手动安装了

**Comment by youngjumped** [comment]
> 
> 
> 用lean的源码，在添加feeds.conf.default后make menuconfig里面luci-app里面没有smartdns
lean大佬这两天从package里剔除了smartdns了 得手动安装了

**Comment by youngjumped** [comment]
> 
> 
> 用lean的源码，在添加feeds.conf.default后make menuconfig里面luci-app里面没有smartdns

lean大佬这两天从package里剔除了smartdns了 得手动安装了

**Comment by cntink** [comment]
添加后怎么多拨(luci-app-syncdial)的包也没了。。。
