### ISSUE TITLE
插件订阅脚本问题

### ISSUE THREAD

**Issue by JoeHoy233** [Lienol/openwrt-package#55]
订阅后tls全为none，参照大雕订阅脚本将
if [ "$json_tls" == "1" ]; then
改成
if [ "$json_tls" == "tls" -o "$json_tls" == "1" ]; then
后正常
另外ss订阅和导入好像也有些问题，无法订阅到正常节点信息
脚本中348和132行中应该为ss而不是ssr
PS:插件挺好用的

**Comment by lyafancn** [comment]
> 订阅后tls全为none，参照大雕订阅脚本将
> if [ "$json_tls" == "1" ]; then
> 改成
> if [ "$json_tls" == "tls" -o "$json_tls" == "1" ]; then
> 后正常
> 另外ss订阅和导入好像也有些问题，无法订阅到正常节点信息
> 脚本中348和132行中应该为ss而不是ssr
> PS:插件挺好用的

终于来大佬了。

**Comment by Lienol** [comment]
已修复
