### ISSUE TITLE
建议：所有trojan目录（源文件）及名称等改成trojan-plus，使之实至名归。

### ISSUE THREAD

**Issue by lxhao61** [Lienol/openwrt-package#557]
trojan既然被trojan-plus掏空及替换，建议所有trojan目录（源文件）及名称改成trojan-plus，使之实至名归。

**Comment by lxhao61** [comment]
@peter-tank
https://github.com/Lienol/openwrt-package/commit/c477a755929525d553424826e16f3b0c4301a405

**Comment by Lienol** [comment]
rename.
