### ISSUE TITLE
多个订阅源问题

### ISSUE THREAD

**Issue by JoeHoy233** [Lienol/openwrt-package#56]
添加多个订阅源，轮换订阅源，目前好像只有第一个能够订阅，是不支持同时订阅多个吗，能否加上这个功能呢

**Comment by lyafancn** [comment]
> 添加多个订阅源，轮换订阅源，目前好像只有第一个能够订阅，是不支持同时订阅多个吗，能否加上这个功能呢

兄弟你竟然能订阅？我试了好几个机场的SSR订阅都订阅不出来节点。。

**Comment by Lienol** [comment]
已经可以
