### ISSUE TITLE
2020-07-30升级编译结果

### ISSUE THREAD

**Issue by gswangmd-gssi** [Lienol/openwrt-package#563]
早上下载编译，结果显示DNS未运行
![批注 2020-07-30 073434](https://user-images.githubusercontent.com/59297839/88864232-4a4fcf00-d237-11ea-9a9b-2b94f6ed8a04.png)

**Comment by Bruce-Jack** [comment]
我的情况是一直运行不了，负载均衡有问题

**Comment by Lienol** [comment]
Fix
