### ISSUE TITLE
DNS好像又出问题了=。=

### ISSUE THREAD

**Issue by jh0072110** [Lienol/openwrt-package#565]
截止现在的最新源码编译，出现了两个小问题，如图：
![image](https://user-images.githubusercontent.com/50496854/88887033-3a9fad00-d26e-11ea-9542-d790fb0cf0ce.png)
![image](https://user-images.githubusercontent.com/50496854/88887062-4a1ef600-d26e-11ea-933c-1f27b9807459.png)
不影响使用，但……好像是哪里出问题了的亚子=。=

**Comment by jh0072110** [comment]
![image](https://user-images.githubusercontent.com/50496854/88887248-9a965380-d26e-11ea-8ebe-e1a174e8e88d.png)
Sorrybu补一张我的DNS设置图，没开smartdns（我觉得没什么用），涂鸦部分是nextdns（据说是私有IP就不公开了哈哈哈），用自带默认DNS效果和上面一致。

**Comment by Lienol** [comment]
It's my fault.

**Comment by x4455** [comment]
> ![图片](https://user-images.githubusercontent.com/50496854/88887033-3a9fad00-d26e-11ea-9542-d790fb0cf0ce.png)

虽然显示为运行，但是在 系统进程 那边能看到有相关的进程在工作
> ![图片](https://user-images.githubusercontent.com/50496854/88887062-4a1ef600-d26e-11ea-933c-1f27b9807459.png)

规则更新失败是 cdn.jsdelivr.net 那边403了

**Comment by Lienol** [comment]
Fix https://github.com/Lienol/openwrt-package/commit/14386a33fc513ea53df7d839f051e31481d8d1d7
