### ISSUE TITLE
大陆白名单貌似有点问题

### ISSUE THREAD

**Issue by lyafancn** [Lienol/openwrt-package#57]
看油管时很多貌似是广告的只显示框框。。。

**Comment by lyafancn** [comment]
最新的passwall貌似还是订阅、导入均失败。。是我的机场订阅不兼容您的插件？还是说Op19的默认主题不兼容您的passwall....

**Comment by lyafancn** [comment]
算了，不能订阅就不用订阅了，手动添加一次也能用好久。。主要是大陆白名单模式下很多油管浮动广告都只有框框，这个得修复下，很重要谢谢。路由Op爬墙圈未来就看大佬你了。

**Comment by Lienol** [comment]
> 算了，不能订阅就不用订阅了，手动添加一次也能用好久。。主要是大陆白名单模式下很多油管浮动广告都只有框框，这个得修复下，很重要谢谢。路由Op爬墙圈未来就看大佬你了。

openwrt ssh输入命令：
/usr/share/passwall/subscription.sh
我看看

**Comment by lyafancn** [comment]
> > 算了，不能订阅就不用订阅了，手动添加一次也能用好久。。主要是大陆白名单模式下很多油管浮动广告都只有框框，这个得修复下，很重要谢谢。路由Op爬墙圈未来就看大佬你了。
> 
> openwrt ssh输入命令：
> /usr/share/passwall/subscription.sh
> 我看看

root@OpenWrt:~# /usr/share/passwall/subscription.sh
/usr/bin/wget: unrecognized option: t
Usage: /usr/bin/wget [options] <URL>
Options:
	-4				Use IPv4 only
	-6				Use IPv6 only
	-q				Turn off status messages
	-O <file>			Redirect output to file (use "-" for stdout)
	-P <dir>			Set directory for output files
	--user=<user>			HTTP authentication username
	--password=<password>		HTTP authentication password
	--user-agent|-U <str>		Set HTTP user agent
	--post-data=STRING		use the POST method; send STRING as the data
	--spider|-s			Spider mode - only check file existence
	--timeout=N|-T N		Set connect/request timeout to N seconds
	--proxy=on|off|-Y on|off	Enable/disable env var configured proxy

HTTPS options:
	--ca-certificate=<cert>		Load CA certificates from file <cert>
	--no-check-certificate		don't validate the server's certificate

**Comment by lyafancn** [comment]
> > 算了，不能订阅就不用订阅了，手动添加一次也能用好久。。主要是大陆白名单模式下很多油管浮动广告都只有框框，这个得修复下，很重要谢谢。路由Op爬墙圈未来就看大佬你了。
> 
> openwrt ssh输入命令：
> /usr/share/passwall/subscription.sh
> 我看看

root@OpenWrt:/# ls
bin         dev         etc         lib         lib64       lost+found  mnt         overlay     proc        rom         root        sbin        sys         tmp         usr         var         www
root@OpenWrt:/# root@OpenWrt:~# /usr/share/passwall/subscription.sh
-ash: root@OpenWrt:~#: not found
root@OpenWrt:/# /usr/bin/wget: unrecognized option: t
-ash: /usr/bin/wget:: not found
root@OpenWrt:/# Usage: /usr/bin/wget [options] <URL>
-ash: syntax error: unexpected newline
root@OpenWrt:/# Options:
-ash: Options:: not found
root@OpenWrt:/# -4Use IPv4 only
-ash: -4Use: not found
root@OpenWrt:/# -6Use IPv6 only
-ash: -6Use: not found
root@OpenWrt:/# -qTurn off status messages
-ash: -qTurn: not found
root@OpenWrt:/# -O <file>
bin/         dev/         etc/         lib/         lib64/       lost+found/  mnt/         overlay/     proc/        rom/         root/        sbin/        sys/         tmp/         usr/         var/         www/
root@OpenWrt:/# -O <file>
bin/         dev/         etc/         lib/         lib64/       lost+found/  mnt/         overlay/     proc/        rom/         root/        sbin/        sys/         tmp/         usr/         var/         www/
root@OpenWrt:/# -O <file>Redirect output to file (use "-" for stdout)
-ash: syntax error: unexpected "("
root@OpenWrt:/# -P <dir>
bin/         dev/         etc/         lib/         lib64/       lost+found/  mnt/         overlay/     proc/        rom/         root/        sbin/        sys/         tmp/         usr/         var/         www/
root@OpenWrt:/# -P <dir>
bin/         dev/         etc/         lib/         lib64/       lost+found/  mnt/         overlay/     proc/        rom/         root/        sbin/        sys/         tmp/         usr/         var/         www/
root@OpenWrt:/# -P <dir>Set directory for output files
-ash: can't open dir: no such file
-ash: -P: not found
root@OpenWrt:/# --user=<user>
bin/         dev/         etc/         lib/         lib64/       lost+found/  mnt/         overlay/     proc/        rom/         root/        sbin/        sys/         tmp/         usr/         var/         www/
root@OpenWrt:/# --user=<user>
bin/         dev/         etc/         lib/         lib64/       lost+found/  mnt/         overlay/     proc/        rom/         root/        sbin/        sys/         tmp/         usr/         var/         www/
root@OpenWrt:/# --user=<user>HTTP authentication username
-ash: can't open user: no such file
-ash: --user=: not found
root@OpenWrt:/# --password=<password>
bin/         dev/         etc/         lib/         lib64/       lost+found/  mnt/         overlay/     proc/        rom/         root/        sbin/        sys/         tmp/         usr/         var/         www/
root@OpenWrt:/# --password=<password>HTTP authentication password
-ash: can't open password: no such file
-ash: --password=: not found
root@OpenWrt:/# --user-agent|-U <str>
bin/         dev/         etc/         lib/         lib64/       lost+found/  mnt/         overlay/     proc/        rom/         root/        sbin/        sys/         tmp/         usr/         var/         www/
root@OpenWrt:/# --user-agent|-U <str>Set HTTP user agent
-ash: -ash: can't open str: no such file--user-agent: not found

-ash: -U: not found
root@OpenWrt:/# --post-data=STRINGuse the POST method; send STRING as the data
-ash: --post-data=STRINGuse: not found
-ash: send: not found
root@OpenWrt:/# --spider|-sSpider mode - only check file existence
-ash: --spider: not found
-ash: -sSpider: not found
root@OpenWrt:/# --timeout=N|-T NSet connect/request timeout to N seconds
-ash: --timeout=N: not found
-ash: -T: not found
root@OpenWrt:/# --proxy=on|off|-Y on|offEnable/disable env var configured proxy
-ash: --proxy=on: not found
-ash: off: not found
-ash: -ash: offEnable/disable: not found
-Y: not found
root@OpenWrt:/# 
root@OpenWrt:/# HTTPS options:
-ash: HTTPS: not found
root@OpenWrt:/# --ca-certificate=<cert>
bin/         dev/         etc/         lib/         lib64/       lost+found/  mnt/         overlay/     proc/        rom/         root/        sbin/        sys/         tmp/         usr/         var/         www/
root@OpenWrt:/# --ca-certificate=<cert>Load CA certificates from file <cert>
-ash: syntax error: unexpected newline
root@OpenWrt:/# --no-check-certificatedon't validate the server's certificate
-ash: --no-check-certificatedont validate the servers: not found
root@OpenWrt:/#

**Comment by lyafancn** [comment]
> /usr/share/passwall/subscription.sh

root@OpenWrt:/usr/share/passwall# cd /
root@OpenWrt:/# ls
bin         dev         etc         lib         lib64       lost+found  mnt         overlay     proc        rom         root        sbin        sys         tmp         usr         var         www
root@OpenWrt:/# /usr/share/passwall/subscription.sh
/usr/bin/wget: unrecognized option: t
Usage: /usr/bin/wget [options] <URL>
Options:
	-4				Use IPv4 only
	-6				Use IPv6 only
	-q				Turn off status messages
	-O <file>			Redirect output to file (use "-" for stdout)
	-P <dir>			Set directory for output files
	--user=<user>			HTTP authentication username
	--password=<password>		HTTP authentication password
	--user-agent|-U <str>		Set HTTP user agent
	--post-data=STRING		use the POST method; send STRING as the data
	--spider|-s			Spider mode - only check file existence
	--timeout=N|-T N		Set connect/request timeout to N seconds
	--proxy=on|off|-Y on|off	Enable/disable env var configured proxy

HTTPS options:
	--ca-certificate=<cert>		Load CA certificates from file <cert>
	--no-check-certificate		don't validate the server's certificate

root@OpenWrt:/#

**Comment by Lienol** [comment]
> > /usr/share/passwall/subscription.sh
> 
> root@OpenWrt:/usr/share/passwall# cd /
> root@OpenWrt:/# ls
> bin dev etc lib lib64 lost+found mnt overlay proc rom root sbin sys tmp usr var www
> root@OpenWrt:/# /usr/share/passwall/subscription.sh
> /usr/bin/wget: unrecognized option: t
> Usage: /usr/bin/wget [options] 
> Options:
> -4	Use IPv4 only
> -6	Use IPv6 only
> -q	Turn off status messages
> -O Redirect output to file (use "-" for stdout)
> -P
> 
> Set directory for output files
> --user=	HTTP authentication username
> --password=	HTTP authentication password
> --user-agent|-U Set HTTP user agent
> --post-data=STRING	use the POST method; send STRING as the data
> --spider|-s	Spider mode - only check file existence
> --timeout=N|-T N	Set connect/request timeout to N seconds
> --proxy=on|off|-Y on|off	Enable/disable env var configured proxy
> HTTPS options:
> --ca-certificate=	Load CA certificates from file 
> --no-check-certificate	don't validate the server's certificate
> 
> root@OpenWrt:/#

更新最新源码，编译时选上wget，再试试

**Comment by lyafancn** [comment]
> > > /usr/share/passwall/subscription.sh
> > 
> > 
> > root@OpenWrt:/usr/share/passwall# cd /
> > root@OpenWrt:/# ls
> > bin dev etc lib lib64 lost+found mnt overlay proc rom root sbin sys tmp usr var www
> > root@OpenWrt:/# /usr/share/passwall/subscription.sh
> > /usr/bin/wget: unrecognized option: t
> > Usage: /usr/bin/wget [options]
> > Options:
> > -4	Use IPv4 only
> > -6	Use IPv6 only
> > -q	Turn off status messages
> > -O Redirect output to file (use "-" for stdout)
> > -P
> > Set directory for output files
> > --user=	HTTP authentication username
> > --password=	HTTP authentication password
> > --user-agent|-U Set HTTP user agent
> > --post-data=STRING	use the POST method; send STRING as the data
> > --spider|-s	Spider mode - only check file existence
> > --timeout=N|-T N	Set connect/request timeout to N seconds
> > --proxy=on|off|-Y on|off	Enable/disable env var configured proxy
> > HTTPS options:
> > --ca-certificate=	Load CA certificates from file
> > --no-check-certificate	don't validate the server's certificate
> > root@OpenWrt:/#
> 
> 更新最新源码，编译时选上wget，再试试

解决了，果然是没有WGET。
