### ISSUE TITLE
订阅出错

### ISSUE THREAD

**Issue by headphile** [Lienol/openwrt-package#572]
8月1日编译的固件，订阅报错，退回之前的版本正常。
![7db898ceec23add4](https://user-images.githubusercontent.com/43878381/89113800-fc8dcd80-d4a7-11ea-986d-0363395f2d79.png)

**Comment by Lienol** [comment]
send your subscribe url to my email let me check.

**Comment by headphile** [comment]
多谢大佬回复。
下午发现是机场改了订阅url，没通知。跟passwall没关系。
