### ISSUE TITLE
vmess设置UDP转发的疑问

### ISSUE THREAD

**Issue by maozheng92** [Lienol/openwrt-package#59]
V2ray使用wmess协议如何开启UDP转发？看官网文档要开启UDP转发功能在客户端的socks协议中开启，请问在哪里设置？

**Comment by Lienol** [comment]
直接在UDP节点使用即可。不建议用V2ray的UDP转发，性能不太佳

**Comment by maozheng92** [comment]
但是在ps4和switch中测试nat类型分别类型3和D

**Comment by kszym2002** [comment]
v2ray udp真的不行 NAT类型肯定是3和D 要用软路由游戏还是用SS或者SSR吧
