### ISSUE TITLE
ss链接导入的问题

### ISSUE THREAD

**Issue by JoeHoy233** [Lienol/openwrt-package#60]
开了一个Pull requests，麻烦看一下代码，如有不足请指出
目前自己使用的ss链接会有部分没有base64编码，使用的的是明文，这会导致导入到节点信息不完整，而且ss也没有解析节点名称，名称部分使用的是url编码，是否能够考虑把解码部分根据不同的节点类型分别处理？
指出最新subscription.sh里的一点小问题
63行ssr_encrypt_method应为ss_encrypt_method
132行${uci_set}type="SSR"应为${uci_set}type="SS"
137行应为${uci_set}ss_encrypt_method="$ss_encrypt_method"

**Comment by Lienol** [comment]
已合并，主要我没有SS链接和订阅，没有详细测试过
