### ISSUE TITLE
大陆白名单模式下，出现如图问题

### ISSUE THREAD

**Issue by lyafancn** [Lienol/openwrt-package#61]
![image](https://user-images.githubusercontent.com/53136737/70417088-75fd2980-1a9b-11ea-90cc-a7dfaaa81cab.png)
不显示广告。强迫症受不了了。/(ㄒoㄒ)/~~

**Comment by Lienol** [comment]
检测下自己的问题？我一直用大陆白名单，没出现过这问题...看看是不是和某些插件冲突？浏览器QUIC试下关掉看看

**Comment by lyafancn** [comment]
好的，我试试

**Comment by lyafancn** [comment]
> 检测下自己的问题？我一直用大陆白名单，没出现过这问题...看看是不是和某些插件冲突？浏览器QUIC试下关掉看看

![2](https://user-images.githubusercontent.com/53136737/70426865-b7e39b00-1aae-11ea-8990-6da7d089a67f.png)
![1](https://user-images.githubusercontent.com/53136737/70426867-b7e39b00-1aae-11ea-8ed6-895346797e57.png)
关掉Chrome的QUIC了，重启路由和电脑了，还是复现。具体设置也在上图了。（我没有其他的浏览器插件只有一个switch omga插件，系统代理模式。）
