### ISSUE TITLE
passwall所有服务都无法启动,

### ISSUE THREAD

**Issue by garypang13** [Lienol/openwrt-package#67]
使用的是lean的最新源码,
按照这个方式编译的,https://github.com/Lienol/openwrt-package/issues/54#issuecomment-562859266
.config中取消了所有和SSR Plus+相关的内容,
经测试,SSR订阅更新正常,但是SS订阅无法更新,另外所有passwall相关的服务都无法启动,全部都是未运行状态,PDNSD,TCP,UDP等等都无法启动.

**Comment by JoeHoy233** [comment]
我的ss订阅正常，现在只支持Kitsunebi的ss订阅链接，其他格式的不支持

**Comment by Lienol** [comment]
passwall日志
