### ISSUE TITLE
openwrt-19.07 shadowsocksr-libev-2.5.6 编译出错麻烦帮排查下谢谢

### ISSUE THREAD

**Issue by lbbboy** [Lienol/openwrt-package#68]
`Hunk #1 FAILED at 718 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file src/local.c.rej
Patch failed!  Please fix ./patches/999-Fix-Werror-sizeof-pointer-memaccess.patch!
Makefile:64: recipe for target '/home/ubuntu/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocksr-libev//shadowsocksr-libev-2.5.6-d6                                                                                                                                         3ff863800a5645aca4309d5dd5962bd1e95543/.prepared_b46ef69c1540fa1a9570362ce2977c95_6664517399ebbbc92a37c5bb081b5c53' failed
make[3]: *** [/home/ubuntu/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocksr-libev//shadowsocksr-libev-2.5.6-d63ff863800a5645aca4                                                                                                                                         309d5dd5962bd1e95543/.prepared_b46ef69c1540fa1a9570362ce2977c95_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/ubuntu/openwrt/feeds/lienol/lienol/shadowsocksr-libev'
time: package/feeds/lienol/shadowsocksr-libev/compile#6.78#0.74#14.73
package/Makefile:111: recipe for target 'package/feeds/lienol/shadowsocksr-libev/compile' failed
make[2]: *** [package/feeds/lienol/shadowsocksr-libev/compile] Error 2
make[2]: Leaving directory '/home/ubuntu/openwrt'
package/Makefile:107: recipe for target '/home/ubuntu/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/ubuntu/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ubuntu/openwrt'
/home/ubuntu/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2`

**Comment by Lienol** [comment]
./scripts/feeds clean
./scripts/feeds update -a
./scripts/feeds install -a
试试还报错不

**Comment by lbbboy** [comment]
> ./scripts/feeds clean
> ./scripts/feeds update -a
> ./scripts/feeds install -a
> 试试还报错不

试过了一样的报错

**Comment by Lienol** [comment]
> > ./scripts/feeds clean
> > ./scripts/feeds update -a
> > ./scripts/feeds install -a
> > 试试还报错不
> 
> 试过了一样的报错

我刚修复的，你再试试

**Comment by lbbboy** [comment]
> > > ./scripts/feeds clean
> > > ./scripts/feeds update -a
> > > ./scripts/feeds install -a
> > > 试试还报错不
> > 
> > 
> > 试过了一样的报错
> 
> 我刚修复的，你再试试

可以了通过了。
