### ISSUE TITLE
规则更新失败

### ISSUE THREAD

**Issue by Martin-Lau-GZ** [Lienol/openwrt-package#70]
![image](https://user-images.githubusercontent.com/41497281/70609975-b4324e80-1c3d-11ea-9b14-1009827718d9.png)

commit 3bbcf2c4bc2257a613319f1d399367be8f4021ed (HEAD -> master, origin/master, origin/HEAD)

openwrt用的是官方的19.07
commit 0bb4733e6727b05d6f6ecd82ae18b5246ad801da (HEAD -> openwrt-19.07, origin/openwrt-19.07)

科学上网正常

**Comment by Lienol** [comment]
输入命令
/usr/share/passwall/rule_update.sh
我看看
可以试试我的openwrt19源码
https://github.com/Lienol/openwrt

**Comment by Martin-Lau-GZ** [comment]
![image](https://user-images.githubusercontent.com/41497281/70612787-8bf91e80-1c42-11ea-9e1e-a9fedb09f517.png)

没有任何提示

**Comment by Lienol** [comment]
passwall日志呢

**Comment by Martin-Lau-GZ** [comment]
2019-12-11 18:27:16: 开始更新规则，请等待...
2019-12-11 18:27:16: 检测到gfwlist本地版本号和在线版本号相同，不用更新!
2019-12-11 18:27:16: 检测到chnroute本地版本号和在线版本号相同，不用更新!
2019-12-11 18:27:16: 更新进程运行完毕！

应该是能更新，只是提示信息需要完善。感谢快速回复，另外，忘了提供log信息，抱歉。
