### ISSUE TITLE
ipt2socks编译失败

### ISSUE THREAD

**Issue by ksong008** [Lienol/openwrt-package#71]
debian10编译ipt2socks失败
![image](https://user-images.githubusercontent.com/54489832/70708135-bfa47900-1d14-11ea-8fc1-b02af1e7745a.png)

**Comment by Lienol** [comment]
更新libuv包
https://github.com/Lienol/openwrt-packages/commit/4e038d844813f61d4bd22efb26bb917feec4021e

**Comment by ksong008** [comment]
明白了，谢谢
