### ISSUE TITLE
能不能把smart DNS添加回来

### ISSUE THREAD

**Issue by nchen194** [Lienol/openwrt-package#75]
原来的smart dns挺好用的，能不能加回来

**Comment by lyafancn** [comment]
> 原来的smart dns挺好用的，能不能加回来

![image](https://user-images.githubusercontent.com/53136737/70881152-a5b1b180-2006-11ea-9779-e5e9f0f21638.png)

**Comment by lllrrr** [comment]
自己git reset --hard a8631e4351d3f0d6cf2a977bea8b2123bf46cd85

**Comment by Lienol** [comment]
smartdns已开源，你可自行添加到自己的包。或等官方合并smartdns代码即可。
