### ISSUE TITLE
反馈几个问题，望大神修复。

### ISSUE THREAD

**Issue by lxhao61** [Lienol/openwrt-package#8]
借此处可以反馈，反馈几个问题，望大神修复：
1、源19.07中[softethervpn](https://github.com/Lienol/openwrt-packages/tree/19.07/net/softethervpn)插件（softether稳定版，非softethervpn5插件）无法编译，报错情况见我云编译链接：https://github.com/lxhao61/Actions-Lienol-OpenWrt/runs/4603237472?check_suite_focus=true （测试过其它其它硬件架构，都一样问题。）

2、源main编译硬路由器，缺如下交换机模块无法使用：
![image](https://user-images.githubusercontent.com/24571146/147024777-3d319c86-0f40-47e4-931f-424c90a6b1d0.png)

3、源21.01中luci-app-turboacc插件缺kmod-shortcut-fe-drv依赖，编译了此插件也无法启用。编译前报错如下：
WARNING: Makefile 'package/feeds/other/luci-app-turboacc/Makefile' has a dependency on 'kmod-shortcut-fe-drv', which does not exist。

**Comment by lxhao61** [comment]
感谢大神修复问题1，终于可以完美编译我需要的固件了。

**Comment by Lienol** [comment]
openwrt 21.02后大部分架构已经使用DSA代替swconfig交换机了。

**Comment by Lienol** [comment]
openwrt 21.02后大部分架构已经使用DSA代替swconfig交换机了。

**Comment by Lienol** [comment]
openwrt 21.02后大部分架构已经使用DSA代替swconfig交换机了。

**Comment by Lienol** [comment]
All complete.
