### ISSUE TITLE
单独拉取lienol到编译目录下

### ISSUE THREAD

**Issue by aa4851698** [Lienol/openwrt-package#80]
单独编译出来4个ipk安装到路由器上
使用之后无法上网？
以为是跟原来的ssr-plus冲突
重新再次编译正个固件去掉ssr-plus
编译好了还是不能上网 
passwall不知道是哪里问题
版本OpenWrt R9.12.03 / LuCI Master (git-19.338.43082-9e87e69)
内核4.9.205
源码基于lean

**Comment by Lienol** [comment]
没有出现过此情况，不好确定原因。
个人感觉是dns设置问题导致。
你可以试试用我的源码编译。

**Comment by aglent** [comment]
> 
> 
> 单独编译出来4个ipk安装到路由器上
> 使用之后无法上网？
> 以为是跟原来的ssr-plus冲突
> 重新再次编译正个固件去掉ssr-plus
> 编译好了还是不能上网
> passwall不知道是哪里问题
> 版本OpenWrt R9.12.03 / LuCI Master (git-19.338.43082-9e87e69)
> 内核4.9.205
> 源码基于lean

请问如何单独编译passwell？

**Comment by Lienol** [comment]
> > 单独编译出来4个ipk安装到路由器上
> > 使用之后无法上网？
> > 以为是跟原来的ssr-plus冲突
> > 重新再次编译正个固件去掉ssr-plus
> > 编译好了还是不能上网
> > passwall不知道是哪里问题
> > 版本OpenWrt R9.12.03 / LuCI Master (git-19.338.43082-9e87e69)
> > 内核4.9.205
> > 源码基于lean
> 
> 请问如何单独编译passwell？

make menuconfig 进入编译菜单，选好需要passwall的插件后保存退出
make package/feeds/lienol/luci-app-passwall/compile -j1 V=s
