### ISSUE TITLE
请教Passwall的设置问题

### ISSUE THREAD

**Issue by aglent** [Lienol/openwrt-package#82]
我用LEDE源码集成了Passwall
1、节点服务器支持simple obfs吗？
2、全局设置页面下的ChinaDNS-NG的上游服务器这个设置，是选定国外可信DNS，而国内DNS是在高级设置里指定，是这样理解吗？另外国内DNS服务器我能不能自定义为上游的smartdns，比如127.0.0.1:6053，我试了下没成功。
3、DNS转发设置里【使用7913端口的DNS服务】，这是什么，要如何使用？
4、gfwlist和chnroute 版本，点击更新，会弹出提示【错误】两字，不知道是什么原因，我只能在/etc/config/passwall_rule下更新。
5、默认设置下，只加了一个节点，启动后，有部分机场主页无法打开，比如www.maying.co、nexitally.com等。
以上是我遇到的问题，是否没设置好，请教如何解决。

**Comment by Lienol** [comment]
1.不支持，但支持V2ray-Plugin，编译时选找到V2ray-Plugin勾上
2.你应该到 网络 - DHCP/DNS - DNS 转发 添加smartdns作为上游才对
3.意思就是【使用7913端口的DNS服务】作为解决DNS污染
4.执行/usr/share/passwall/rule_update.sh 看看输出了什么
5.把maying.co和nexitally.com添加到 黑白名单 - 域名黑名单里面保存

**Comment by aglent** [comment]
rule_update.sh输出是 uci: Entry not found

**Comment by Lienol** [comment]
更新最新源码再试试

**Comment by aglent** [comment]
新版能正常更新了 谢谢

**Comment by ntgeralt** [comment]
选择7913端口启用后，smartdns再用7913会启动不了。顺序一定要反过来。

**Comment by Deleted-Account** [comment]
添加DNS服务器和端口的写法，是 IP#port
实例：127.0.0.1#6053
用 # 代替一般的 :
