### ISSUE TITLE
编译passwall的configuration里边有好多项，是不是默认勾选的就可以了

### ISSUE THREAD

**Issue by mazheng127** [Lienol/openwrt-package#83]
编译passwall的configuration里边有好多项，是不是默认勾选的5个就可以了

**Comment by Lienol** [comment]
按自己需求勾选。。。如果你设备空间大，全部勾选都可以。。。

**Comment by mazheng127** [comment]
请编译时选上"luci","luci-compat","luci-lib-ipkg"后编译
这3项搜不到，还有就是全勾选的话会不会和SSR plus+冲突
