### ISSUE TITLE
luci-app-filebrowser无法下载对应文件！

### ISSUE THREAD

**Issue by au3300** [Lienol/openwrt-package#86]
编译大雕源码增加了luci-app-filebrowser，保存好配置后点击 手动下载
提示：获取远程版本信息失败....
去官方下载对应文件放置对应目录，可运行正常。请教大神这个情况该怎么解决！！！

**Comment by lllrrr** [comment]
发错地方了吧，我编译Lienol的没问题

**Comment by Lienol** [comment]
可能没有装curl

**Comment by au3300** [comment]
> 可能没有装curl

还真是curl的问题！感谢大神回复....

**Comment by Lienol** [comment]
最新源码已经不需要curl，只需要wget

**Comment by fobenshidaodao** [comment]
au3300 请问对应的目录在哪啊

**Comment by wefuxkgfw** [comment]
@fobenshidaodao 谷歌

**Comment by wefuxkgfw** [comment]
@fobenshidaodao 谷歌

**Comment by fobenshidaodao** [comment]
我跟他一样``点击手动下载后显示  获取远程版本信息失败。

**Comment by fobenshidaodao** [comment]
不会啊`大神

**Comment by fobenshidaodao** [comment]
我不会啊`你能否教我下

wefuxkgfw <notifications@github.com> 于2020年3月5日周四 下午10:21写道：

**Comment by Lienol** [comment]
路由器自身 上不了github了，请挂代理

**Comment by wefuxkgfw** [comment]
@Lienol 套娃啊，上一级路由也爬墙

**Comment by fobenshidaodao** [comment]
感谢``开启科学上网,和路径搞定了`

wefuxkgfw <notifications@github.com> 于2020年3月5日周四 下午11:02写道：
