### ISSUE TITLE
kcptun-client在make menuconfig中的名称显示与paswall依赖中的不同

### ISSUE THREAD

**Issue by crackself** [Lienol/openwrt-package#87]
完整获取的'opennwrt-package',树莓派3B 64位target编译提示passwall的kcptun-client依赖未安装。源码目录内确实由kcptun目录及其Makefile。
其中，kcptun的Makefile：
```
...
define Package/$(PKG_NAME)-client
	SECTION:=net
	CATEGORY:=Network
	TITLE:=Kcptun is a cross-platform proxy software
	DEPENDS:=
	URL:=https://github.com/xtaci/kcptun
endef
```
但make menuconfig 界面里，Network/Web servere/Proxy目录里找不到条目，仅有**kcptun-c**及**kcpttun-s**两个。
![capture](https://user-images.githubusercontent.com/16448332/71558993-df1cff00-2a93-11ea-903f-fb666fa3396f.png)

测试结果：将passwall的Makefile 其中依赖的kcptun-client改为kcptun-c后编译通过，功能未测试。请大佬看看更改是否符合。

**Comment by crackself** [comment]
刷入系统后可看到已安装的软件包里确实有kcptun-c
![cat](https://user-images.githubusercontent.com/16448332/71559122-80f11b80-2a95-11ea-9fc3-768d4ac6ab5f.png)

**Comment by Lienol** [comment]
原因很简单，因为官方openwrt19的package合并了kcptun，但是这个kcptun包和我的包冲突了。

**Comment by Lienol** [comment]
这样这能用，不过你要把kcptun的客户端路径改成kcptun-c的路径

**Comment by crackself** [comment]
明白了
