### ISSUE TITLE
dns2socks的使用问题

### ISSUE THREAD

**Issue by aglent** [Lienol/openwrt-package#88]
全局设置 dns转发模式为chinadns-ng
chinadns-ng上游服务器为dns2socks 
然后我选择socks5的节点 其它设置默认
请问这样操作 是否国内dns用114等 国外可信dns通过socks5的节点去查询？获取的海外ip一定是正确了？

**Comment by Lienol** [comment]
不能说一定吧，具体还是得自己测试
