### ISSUE TITLE
是否可以顺便也把luci-app-pppoe-server也增强一下吗？

### ISSUE THREAD

**Issue by openwrtdiy** [Lienol/openwrt-package#9]
当前发现一个小问题是：如果自定义绑定拨号IP地址后，luci-app-pppoe-server在线用户显示IP与自定义绑定的实际IP不对！
另外luci-app-pppoe-server在线用户可否增加一格：在线账号

**Comment by Lienol** [comment]
wait.

**Comment by Lienol** [comment]
试下最新源码测试下？

**Comment by openwrtdiy** [comment]
此次更新已解决绑定自定义IP和在线用户显示问题，其它反馈问题来了：

1.用户管理：当新增或编辑时，pppoe-server死机了！先前拨号用户也没断开连接，无法上网。新增用户无法拨号！我重启服务后才可以上网和拨号。
2.用户管理：少了服务器名称，pppoe-server可以绑定不同用户的服务器名称？
3.拨号账号相同时，当前已支持踢前者下线，后者上线！如果在线账号没被盗的话，当后者拨号过程中提示当前账号在线呢？（这个问题无关紧要）
4.用户管理：自定义IP可否绑定不同的子网段呢？实现拨号账号分流
5.增设pppoe-server高级设置：可以把/etc/ppp/pppoe-server-options里面的一些设置参数移到高级设置中，方便修改！
6.不启用个别的拨号账号后，被禁用的账号在拨号过程中，在系统日志中看到ppp接口名称和自动分配的IP地址。有什么办法完全禁用没？（这个问题无关紧要）
Fri Dec 24 12:41:40 2021 daemon.info pppoe-server[19176]: Session 2 created for client d8:c4:97:5c:4d:29 (10.0.1.101) on br-lan using Service-Name ''
Fri Dec 24 12:41:40 2021 daemon.info pppd[19176]: Plugin pppoe.so loaded.
Fri Dec 24 12:41:40 2021 daemon.info pppd[19176]: PPPoE plugin from pppd 2.4.9
Fri Dec 24 12:41:40 2021 daemon.notice pppd[19176]: pppd 2.4.9 started by root, uid 0
Fri Dec 24 12:41:40 2021 daemon.warn pppd[19176]: Connected to d8:c4:97:5c:4d:29 via interface br-lan
Fri Dec 24 12:41:40 2021 daemon.info pppd[19176]: Using interface ppp1
Fri Dec 24 12:41:40 2021 daemon.notice pppd[19176]: Connect: ppp1 <--> br-lan
Fri Dec 24 12:41:42 2021 daemon.err pppd[19176]: No CHAP secret found for authenticating china
Fri Dec 24 12:41:42 2021 daemon.warn pppd[19176]: Peer china failed CHAP authentication
Fri Dec 24 12:41:42 2021 daemon.notice pppd[19176]: Connection terminated.
Fri Dec 24 12:41:42 2021 daemon.info pppoe-server[18137]: Sent PADT
Fri Dec 24 12:41:42 2021 daemon.info pppd[19176]: Exit.
Fri Dec 24 12:41:42 2021 daemon.info pppoe-server[18137]: Session 2 closed for client d8:c4:97:5c:4d:29 (10.0.1.101) on br-lan
7.这个代码提到了限速功能  root/usr/share/pppoe-server/ip-up  如何实现？
8.当前有新版本rp-pppoe-3.15 https://github.com/Lienol/openwrt-packages/blob/19.07/net/rp-pppoe/Makefile
9.这里提到了pppoe拨号存在用户数量限制，这个代码库解除了限制。https://github.com/dfskoll/rp-pppoe/commit/a460920d0d1210ca9427e5eb1493f05cc186e0fc
