### ISSUE TITLE
passwall在后台无法手动更新规则

### ISSUE THREAD

**Issue by garypang13** [Lienol/openwrt-package#94]
后台点击手动更新提示无法访问更新接口，请更新接口！已翻墙,代理正常,
在路由器ssh中执行 ./rule_update.sh 无任何报错或提示,应该是更新成功了.

**Comment by qiankun316** [comment]
请问这个怎么安装啊？求教，小白入门。

**Comment by Lienol** [comment]
/usr/share/passwall/rule_update.sh
执行后到 界面查看日志看看 是什么
如果还是“无法访问更新接口，请更新接口！”，证明路由器自身无法访问github

**Comment by Lienol** [comment]
另外，wget或curl装了吗？
