### ISSUE TITLE
请教路由器aria2下载BT时，如何避免走passwall代理?

### ISSUE THREAD

**Issue by yasum2006** [Lienol/openwrt-package#96]
请教路由器aria2下载BT时，如何避免走passwall代理?
  使用Lienol的固件才两天时间，passwall速度明显快，领教了神秘加速技术，感谢Lienol大
  passwall的本机代理模式有两个选项：默认或gfw，路由器aria2下载BT时，流量是本机代理模式吧？如何避免走passwall代理？
是否可以在本机代理模式增加选项：no，本机流量都不走passwall代理？

之前用SSR Plus+时，修改/etc/config/shadowsocksr文件，
config access_control
option router_proxy '1'  改为option router_proxy '0'
当路由器挂载硬盘下载BT时，SSR Plus+会过滤BT流量

**Comment by yasum2006** [comment]
经过一段时间的测试，Li大的passwall已经过滤了路由器bt流量，

**Comment by Lienol** [comment]
如果你的bt是挂在路由器本机，则会走本机代理流量，选默认应该不会走代理

**Comment by lostz** [comment]
我的nas 起了多个docker，其中有bt 下载，我现在希望bt 不走代理，请问该怎么配置。

**Comment by Lienol** [comment]
配合 访问控制 代理模式 代理端口 即可

**Comment by HuTao1996** [comment]
> 请教路由器aria2下载BT时，如何避免走passwall代理?
> 使用Lienol的固件才两天时间，passwall速度明显快，领教了神秘加速技术，感谢Lienol大
> passwall的本机代理模式有两个选项：默认或gfw，路由器aria2下载BT时，流量是本机代理模式吧？如何避免走passwall代理？
> 是否可以在本机代理模式增加选项：no，本机流量都不走passwall代理？
> 
> 之前用SSR Plus+时，修改/etc/config/shadowsocksr文件，
> config access_control
> option router_proxy '1' 改为option router_proxy '0'
> 当路由器挂载硬盘下载BT时，SSR Plus+会过滤BT流量

但是SSR Plus+检测谷歌连接会无效

**Comment by Rangtian** [comment]
@Lienol 你好，我用FDM下载海外BT资源时，TCP转发不管是设置为“常用端口”，还是设置为“仅网页”，P2P流量都会走代理。只有将转发模式从“大陆白名单”改为“GFW”才能避免走代理。请问该如何在“大陆白名单”模式下过滤BT流量？

谢谢你！！！

**Comment by HuTao1996** [comment]
之前我试过要改科学上网插件，原理就是软路由本身不翻墙，我现在解决办法就是买nas或者下载机，最完美。软路由挂下载还是差了点。





------------------ 原始邮件 ------------------
发件人: Rangtian <notifications@github.com&gt;
发送时间: 2020年6月28日 22:21
收件人: Lienol/openwrt-package <openwrt-package@noreply.github.com&gt;
抄送: HuTao1996 <294587434@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Lienol/openwrt-package] 请教路由器aria2下载BT时，如何避免走passwall代理? (#96)





 
@Lienol 你好，我用FDM下载海外BT资源时，TCP转发不管是设置为“常用端口”，还是设置为“仅网页”，P2P流量都会走代理。只有将转发模式从“大陆白名单”改为“GFW”才能避免走代理。请问该如何在“大陆白名单”模式下过滤BT流量？
 
谢谢你！！！
